### ISSUE TITLE
Issues/Questions

### ISSUE THREAD

**Issue by TheEpicCooldeal** [LegendOfMCPE/EssentialsPE#107]
I know it takes a long time to code plugins like this one. Take your time on adding or fixing any of these Issues and Questions. I WILL be patient. What's important to me is that you take your time :)

Additionally, I'm using the latest and greatest version of EssentialsPE (https://github.com/LegendOfMCPE/EssentialsPE/releases/tag/1.1.0) and the latest version of PocketMine (The build 1240 using API 1.12.0). and I'm not doing this to make you waste your time. I just want this plugin to be even better <3

Issues:
I've realized that when I do /tempban Guest1 25m It adds one day to the time. Does "m" stand for something else not like "minute"
When you use /mute <player> It mutes the whole chat not even a single user can talk.
When you use /seen it crashes the server!

Questions:
Will "Welcome {playername} to the server" be added and will it be customizable or not
Also this is something that I would REALLY like the Ban Notifying, Kick Notifying, and Mute Notifying for example there is a permission "essentials.ban.notify" and with this permission the user can get notified if someone got banned. (Just like in the regular essentials)
Can you add a mute notifier like when a player gets muted it tells him "You have been muted" and also if you can add a time if not then add offline support so we can unmute a user even when they're offline.
A way for a server owner to know someone's private messages xD (Just like in regular essentials) (./socialspy)

Thank you for reading, Take your time on adding or fixing!

**Comment by iksaku** [comment]
For some of the questions you have... We wil not support custom sever messages in a while, we need some more things to be added before ;)
We're aware of all the issues you have reported, thanks for writting them all in one place :D 

And for the features ou request like ``/socialspy`` and ome other permission nodes, we may add them soon ;)

**Thanks!**

**Comment by TheEpicCooldeal** [comment]
No thank you for making this plugin ;)

**Comment by BelleBeauty** [comment]
Permission node  "essentials.getpos" allows user to see other players positions as well as their own.
