### ISSUE TITLE
Homes.yml broken all commands fail

### ISSUE THREAD

**Issue by NML32** [LegendOfMCPE/EssentialsPE#108]
It happens a lot where the Homes.yml file gets corrupted and all the EssentialsPE commands stop working.  The only way I know how to fix it is create a new Homes.yml file.  Then listen to all the hate come pouring in because everyone just lost their saved Homes.

**Comment by iksaku** [comment]
Your homes file must be broken... The old and new Homes system (1.0.x and 1.1.0) is the same, there shouldn't be any issues with them

**Comment by NML32** [comment]
I don't know happens on all three servers.

**Comment by NML32** [comment]
Seems like a bug when LDX says this:
https://forums.pocketmine.net/threads/essentialspe.6028/page-13#post-91763

and this
https://forums.pocketmine.net/threads/essentialspe.6028/page-14#post-92102

**Comment by LDX-MCPE** [comment]
It is a bug. For some reason, when the array is converted to YAML, the colon isn't escaped. The easiest soulution (and best) is to use a RegExp to check the names of homes against an array of approved characters.

**Comment by NML32** [comment]
I wish I knew how because it sounds like an easy fix.
Can you suggest a Windows program and an array of approved characters?

I would like to be able to fix the Homes file instead of having to create a new one each time.

Thanks

**Comment by LDX-MCPE** [comment]
No, no, no. This feature will be built directly into EssentialsPE.

**Comment by iksaku** [comment]
This bug was fixed in a previous commit, gonna close :P

**Comment by NML32** [comment]
Has the fixed version been released yet?

**Comment by iksaku** [comment]
Not yet, but soon... We need to optimize a little bit more of code :P

**Comment by NML32** [comment]
Thanks, looking forward to the fix.

Thanks,
Guys I know you're working very hard on this project.
