### ISSUE TITLE
GM bug

### ISSUE THREAD

**Issue by Creeperface01** [LegendOfMCPE/EssentialsPE#110]
[Server thread/CRITICAL]: Unhandled exception executing command 'gm' in gamemode: Undefined offset: 0
[10:42:33] [Server thread/NOTICE]: ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/EssentialsPE (1).phar/src/EssentialsPE/Commands/Override/Gamemode" at line 73

**Comment by iksaku** [comment]
This issue must be related to the incorrect usage of the command, but we will add protection for it ;)

Thanks for the report!

**Comment by Creeperface01** [comment]
Yes i know you only add isset
And why gm 0/1/2 or. Gamemode 0/1/2 doesn't work? Only survival/creative

**Comment by iksaku** [comment]
Nope, you don't know xD and everything works as expected, just need to add some protection for people that doesn't know how to use this command :)

**Comment by Creeperface01** [comment]
So why gm 0/1 and gamemode 0/1 doesn't work?

**Comment by iksaku** [comment]
Maybe because you use slashes? XD just kidding :3 well, I'm not pretty sure... You have reported tons of things that aren't true: "Fly command doesn't exists", "Fly doesn't work", "Homes are not working", etc...

**Comment by iksaku** [comment]
And almost all of them are because of bad usage of the features by your side :$

**Comment by Creeperface01** [comment]
I run command /gamemode 0 it say specifi a valid gamemode.
 or something like that
And fly etc. Dont work because homes.yml didnt work.

**Comment by Creeperface01** [comment]
But /gamemode creative or /gm creative work
