### ISSUE TITLE
It doesnt work warp

### ISSUE THREAD

**Issue by SoyPro** [LegendOfMCPE/EssentialsPE#111]
Players have not permissions to go to warps.for example /warp staff.it says [Error]:you cant teleport to that warp.Ops can go but players have not permissions to go.please fix this.thanks!

**Comment by iksaku** [comment]
You may wish to take a look at this question in PocketMine forums, it has been answered some times, even here at some issues... Please take a look before asking something that has been answered before ;)

For warps, let's think that the warp we want to give permission to players is called ``MyWarp``, so in the config file of your permission nodes manager, you should add the node ``essentials.warps.mywarp``.

All the permission nodes for warps (apart from ``essentials.warp`` that is the command) start with the prefix ``essentials.warps.`` followed by the warp's name

**Comment by SoyPro** [comment]
Thanks very much!!!!.i love this plugin.add new things!thanks to make this plugin!
