### ISSUE TITLE
There is a problemas when players die

### ISSUE THREAD

**Issue by SoyPro** [LegendOfMCPE/EssentialsPE#114]
There is a problem.the console show me:[Server/thread/WARNING]:Cant keep up! Is the server overloaded?
[Server/thread/CRITICAL]:"Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'EssentialsPE v_1.0.0':Argument 2 passed to EssentialsPE\Loader::setPlayerLastPosition() must be an instance of pocketmine\level\Location,instance of pocketmine\level\Position given,called in phar:///storage/emulated/0/PocketMine/plugins/plugin-886.phar/src/EssentialsPE/EventHandlers/PlayersEvent.php on line 198 and defined on EssentialsPE\EventHandlers\PlayersEvents
[Server thread/NOTICE]:InvalidArgumentExecption: "Argument 2 passed to EssentialsPE \Loader::setPlayerLastPosition() must be an instance of pocketmine\level\Location,instance of pocketmine\level\Position given, called in phar:///storage/emulated/0/PocketMine/plugins/plugin-886.phar/src/EssentialsPE/EventHandlers/PlayersEvents.phar/ on line 198 and defined " (E_RECOVERABLE_ERROR)in"/plugin-886.phar/src/EssentialsPE/Loader" at line 908

**Comment by iksaku** [comment]
It appears that you're using an outdated version of EssentialsPE, please consider to update it: 
https://github.com/LegendOfMCPE/EssentialsPE/releases/latest
