### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by SonyBravia** [LegendOfMCPE/EssentialsPE#119]
Ah it keeps crashing my server... it says it caused ny essetialsPE :/

**Comment by LDX-MCPE** [comment]
Please post exactly what it says in the console.

**Comment by SonyBravia** [comment]
Ah. I cleared the log of my console everytime i check it... But can i post the crash dump text?

**Comment by SonyBravia** [comment]
Sorry, i cleared the console log... Can i post the crashdump text?

**Comment by SonyBravia** [comment]
cuz i have 2 crashdump that has the same thing that crashed my server cuz of essentialsPE

**Comment by PEMapModder** [comment]
Please provide sufficient information. 
We are interested in the main message,  the lines of code and the backtrace. Please do **not** post the crash dump (the base64 part where you can't red anything from it at all).

**Comment by iksaku** [comment]
For the crashdump, please upload it to a "Logger" website, like Pastebin and provide the link to it here

**Comment by BelleBeauty** [comment]
Permission node  "essentials.getpos" allows user to see other players positions as well as their own.
