### ISSUE TITLE
EssentialsPE disable

### ISSUE THREAD

**Issue by XEmAX32** [LegendOfMCPE/EssentialsPE#121]
I guys, when i start pocket mine it says 
[16:46:43] [Server thread/NOTICE]: ArrayOutOfBoundsException: "Undefined offset: 3" (E_NOTICE) in "/EssentialsPE_v1.1.0.phar/src/EssentialsPE/Loader" at line 437 
and it disable it 
i have the ultimate development version 
please help me D:

**Comment by iksaku** [comment]
Well, the *Ultimate Development Version* is the latest commit available in this repo, so I don't think you are using it due to the version string that the error reports::P
Also, we have fixed that issue previously, please be patient until we upload a fix to the PocketMine repo ;)
