### ISSUE TITLE
Permission node

### ISSUE THREAD

**Issue by BelleBeauty** [LegendOfMCPE/EssentialsPE#122]
Permission node  "essentials.getpos" allows user to see other players positions as well as their own.

**Comment by iksaku** [comment]
2 things:
1. DO NOT SPAM, you only need to open 1 issue to report a bug, not necessary to open 3 issues about the same, and report it everywhere in comments.
2. We're already working on fixing all the permission issues, please be patient

**Comment by BelleBeauty** [comment]
I'm really sorry about that. I was asked by the owner of a server to ask, I
didn't know where, I put it in wrong place twice then posted once but my
phone kinda glitched and sent it several times. Sorry for the inconvenience.
On 1 Jul 2015 20:20, "Jorge González" <notifications@github.com> wrote:
>
> 2 things:
> 1. DO NOT SPAM, you only need to open 1 issue to report a bug, not
necessary to open 3 issues about the same, and report it everywhere in
comments.
> 2. We're already working on fixing all the permission issues, please be
patient

**Comment by iksaku** [comment]
Well, now you know, just open an issue, write some information of the bug and its enough ;) if we need more things, we will comment them :D

**Comment by iksaku** [comment]
Sub of #120

**Comment by TheEpicCooldeal** [comment]
Just saying.... (not being rude)

If I were you and I wasn't the one who opened the "Stupid Permissions" issue. I would just reply on that issue since it's already opened.

**Comment by BelleBeauty** [comment]
Thx for being nice about this. Also, this isn't about plugins but we have
hackers that don't need to go on server, they just use a chat thing, do you
know of anything that they might be using? The owner was hacked and we need
to stop this.

**Comment by Georggi** [comment]
@BelleBeauty Don't use this as a forum please, if you want ask anythin not issue related, go to https://gitter.im/LegendOfMCPE/EssentialsPE?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge and ask there, about hacking: I know there is a plugin or smth like that for block launcher that is picking passwords from the list and trying to login with that, so if you have a weak password or someone have really big list of passwords they can hack you. 2nd thing that I saw in PC version but not on PE is that there was a plugin that had secret command which gives player full rights, so if you downloaded a plugin from untrusted website that it might be the case:)
