### ISSUE TITLE
session is cleared

### ISSUE THREAD

**Issue by sergeyvad** [LegendOfMCPE/EssentialsPE#129]
Home.yml correctly converted in the session, but the session is cleared rejoining Player

**Comment by iVertx** [comment]
yep, same here...

**Comment by iksaku** [comment]
The session should be shaven when the player quits, and re-load when joins... There must be a glitch in the "reload" part, I will look at that

**Comment by sergeyvad** [comment]
when? this critical problem.

**Comment by iksaku** [comment]
Fixed via: 1c97c1e95906362f6941eaf58ed87dfb42e0ed7b
