### ISSUE TITLE
page to development builds doesn´t work

### ISSUE THREAD

**Issue by Creeperface01** [LegendOfMCPE/EssentialsPE#131]

**Comment by LDX-MCPE** [comment]
Please be more specific in describing your issues.

**Comment by Creeperface01** [comment]
Page where i can download dev versions of essentialspe

**Comment by iksaku** [comment]
Ooops, true... We will need to fix that, thanks!

**Comment by Creeperface01** [comment]
but still doesnt work :/

**Comment by iksaku** [comment]
We don't have any builder yet :/ you will need to manually compile it with DevTools

**Comment by Creeperface01** [comment]
But i tried it and homes dont save and i think new version is needed

**Comment by PEMapModder** [comment]
I'll think of building a new builder at http://pmt.mcpe.me

**Comment by iksaku** [comment]
@PEMapModder Please make it if you can :S We really need it xD

**Comment by iksaku** [comment]
Little update, this issue is going to be solved once #169 is done, so wait for it :3
