### ISSUE TITLE
Crash again.

### ISSUE THREAD

**Issue by thedeibo** [LegendOfMCPE/EssentialsPE#134]
PocketMine-MP Crash Dump Fri Jul 17 13:51:55 UTC 2015

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__32bit
Line: 439
Type: E_ERROR

Code:
[430] 		return $this->perm->isPermissionSet($name);
[431] 	}
[432] 
[433] 	/**
[434] 	 * @param permission\Permission|string $name
[435] 	 *
[436] 	 * @return bool
[437] 	 */
[438] 	public function hasPermission($name){
[439] 		return $this->perm->hasPermission($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param Plugin $plugin
[444] 	 * @param string $name
[445] 	 * @param bool   $value
[446] 	 *
[447] 	 * @return permission\PermissionAttachment
[448] 	 */
[449] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump()
#1 /EssentialsPE.phar/src/EssentialsPE/Loader(709): pocketmine\Player->hasPermission()
#2 /EssentialsPE.phar/src/EssentialsPE/EventHandlers/PlayerEvents(36): EssentialsPE\Loader->createSession()
#3 /src/pocketmine/plugin/MethodEventExecutor(36): EssentialsPE\EventHandlers\PlayerEvents->onPlayerPreLogin()
#4 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute()
#5 /src/pocketmine/plugin/PluginManager(673): pocketmine\plugin\RegisteredListener->callEvent()
#6 /src/pocketmine/Player__32bit(1684): pocketmine\plugin\PluginManager->callEvent()
#7 /src/pocketmine/network/Network(228): pocketmine\Player->handleDataPacket()
#8 /src/pocketmine/Player__32bit(1600): pocketmine\network\Network->processBatch()
#9 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket()
#10 /src/raklib/server/ServerHandler__32bit(90): pocketmine\network\RakLibInterface->handleEncapsulated()
#11 /src/pocketmine/network/RakLibInterface(81): raklib\server\ServerHandler->handlePacket()
#12 /src/pocketmine/network/Network(146): pocketmine\network\RakLibInterface->process()
#13 /src/pocketmine/Server__32bit(2491): pocketmine\network\Network->processInterfaces()
#14 /src/pocketmine/Server__32bit(2306): pocketmine\Server->tick()
#15 /src/pocketmine/Server__32bit(2184): pocketmine\Server->tickProcessor()
#16 /src/pocketmine/Server__32bit(1784): pocketmine\Server->start()
#17 /src/pocketmine/PocketMine(464): pocketmine\Server->__construct()
#18 (1): ()
#19 (0): {main}()

PocketMine-MP version: 1.5dev #1254 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT DAMIAN-PC 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:
AdminJoin 1.3.0 by  for API(s) 1.0.0
AllServers 1.1 by hoyinm for API(s) 1.12.0
BanItem 2.1 by LDX for API(s) 1.0.0
Broadcaster 1.16 by EvolSoft for API(s) 1.12.0
ChatCensor 1.2 by EvolSoft for API(s) 1.7.1
ClearLagg 1.1.0 by LegendOfMCPE for API(s) 1.0.0
CustomAlerts 1.5 by EvolSoft for API(s) 1.12.0
EssentialsPE 1.1.0 by LegendsOfMCPE Team for API(s) 1.12.0
FastTransfer 1.0.2 by shoghicp for API(s) 1.12.0
iControlU 1.3 by Falkirks for API(s) 1.6.0
iProtector 2.0 by LDX for API(s) 1.6.0
ItemCasePE 1.0.5 by aliuly for API(s) 1.10.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
Leaderboard 1.0.0 by TheDeibo for API(s) 1.10.0
PocketGuard 2.1 by MinecrafterJPN for API(s) 1.6.0
PocketMoney 4.0.1 by MinecrafterJPN, MinecrafterJPN for API(s) 1.10.0
PopupDisplayer 2.0.1 by Heromine, Flavius12 for API(s) 1.12.0
PurePerms 1.1.6 by 64FF00 for API(s) 1.12.0
ServerStaff 1.0.0 by Gamecrafter for API(s) 1.10.0
SignPortal 1.1.2 by 99leonchang for API(s) 1.3.1
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
SimpleWarp 2.0.3 by Falkirks for API(s) 1.12.0
TimeCommander 2 by LDX for API(s) 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0
xRulesx 1.0.0 by xFlare for API(s) 1.8.0
PocketJobs 2 by MinecrafterJPN for API(s) 1.10.0
PureChat 1.2.8 by 64FF00 for API(s) 1.11.0

ive tried everything to make the plugin work on the server, i even tried getting rid of the permission plugins, and it still had this crash.

If its not my problem, then now you know, but if it is my problem, can you tell me how to fix it? 

many thanks,
TheDeibo

**Comment by OxonumX** [comment]
I have the problem too. :(

**Comment by thedeibo** [comment]
So it's not just me then :P
