### ISSUE TITLE
Granted Back command to Guest: causes error in console 

### ISSUE THREAD

**Issue by NML32** [LegendOfMCPE/EssentialsPE#135]
I granted the Back command to Guest now when people die an error is created in the console window.

Granted Back to Guests:
essentials.back: Allow the player to return to the last spot before teleporting.
essentials.back.ondeath: Allow the player to return the place where it death.

Error: 
17:38:54 [CRITICAL] "Could not pass event 'pocketmine\event\player\PlayerDeathEvent' to 'EssentialsPE v1.1.0': Argument 2 passed to EssentialsPE\Loader::setPlayerLastPosition() must be an instance of pocketmine\level\Location, instance of pocketmine\level\Position given, called in phar:///home/nml32/pocketmine/plugins/EssentialsPE.phar/src/EssentialsPE/EventHandlers/PlayerEvents.php on line 198 and defined on EssentialsPE\EventHandlers\PlayerEvents
17:38:54 [NOTICE] InvalidArgumentException: "Argument 2 passed to EssentialsPE\Loader::setPlayerLastPosition() must be an instance of pocketmine\level\Location, instance of pocketmine\level\Position given, called in phar:///home/nml32/pocketmine/plugins/EssentialsPE.phar/src/EssentialsPE/EventHandlers/PlayerEvents.php on line 198 and defined" (E_RECOVERABLE_ERROR) in "/EssentialsPE.phar/src/EssentialsPE/Loader" at line 908

**Comment by iksaku** [comment]
Issue fixed previously, it will be available in the next release ;)
