### ISSUE TITLE
Warp bug

### ISSUE THREAD

**Issue by Tolo0** [LegendOfMCPE/EssentialsPE#137]
People can do command /warp (area) (player)
And it warps that player to that area. And they can do /spawn (player).  On the code list i don't see any way of stopping this happening.  Is this a bug?  If not could you please tell me how to stop Guest on my server using /warp. As a way to warp players. I want them to use it to warp them self's to the area only lol.

**Comment by iksaku** [comment]
Sub of #103

**Comment by Tolo0** [comment]
Could u tell where I can find the 1st post of this issue?

**Comment by iksaku** [comment]
Using the ``search feature`` of the repo:
https://github.com/LegendOfMCPE/EssentialsPE/issues?utf8=%E2%9C%93&q=Warp
