### ISSUE TITLE
Ban Error

### ISSUE THREAD

**Issue by Painmcpe** [LegendOfMCPE/EssentialsPE#142]
Hi, and sorry for my bad english.
When a banned player join the server;
Server is crashing..

That is 64bit Player error

**Comment by Painmcpe** [comment]
2015-07-30 [04:16:47] [Server thread/INFO]: beko[/176.240.164.193:45329] logged out due to Kicked by admin. Reason: You have been banned
2015-07-30 [04:16:47] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by PEMapModder** [comment]
Please provide more details.

**Comment by iksaku** [comment]
Please provide more details about how this issue happen:
 - What were you doing when the server crashed?
 - What plugins you have installed alongside EssentialsPE?
 - Is a "CrashDump" file generated?

**Comment by Painmcpe** [comment]
Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 439
Type: E_ERROR

Code:
[430] 		return $this->perm->isPermissionSet($name);
[431] 	}
[432] 
[433] 	/**
[434] 	 * @param permission\Permission|string $name
[435] 	 *
[436] 	 * @return bool
[437] 	 */
[438] 	public function hasPermission($name){
[439] 		return $this->perm->hasPermission($name);
[440] 	}
[441] 
[442] 	/**
[443] 	 * @param Plugin $plugin
[444] 	 * @param string $name
[445] 	 * @param bool   $value
[446] 	 *
[447] 	 * @return permission\PermissionAttachment
[448] 	 */
[449] 	public function addAttachment(Plugin $plugin, $name = \null, $value = \null){

Backtrace:
#0 (): pocketmine\Server->crashDump()

PocketMine-MP version: 1.5dev #1258 [Protocol 27; API 1.12.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux mceu8.envioushost.com 3.10.23-xxxx-std-ipv6-64 #1 SMP Tue Mar 18 14:48:24 CET 2014 x86_64
PHP Version: 5.6.2
Zend version: 2.6.0
OS : Linux, linux

Loaded plugins:
BlockEffects 1.0.3 by GmWM for API(s) 1.12.0
ChatCensor 1.4 by EvolSoft for API(s) 1.9.0
KeepInventory 1.2.0 by boybook for API(s) 1.0.0
EconomyJob 2.0.3 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
BanItem 2.1 by LDX for API(s) 1.0.0
ServerKits 1.3 by EvolSoft for API(s) 1.11.0
ItemCasePE 1.0.5 by aliuly for API(s) 1.10.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
PeacefulSpawn 2.4 by LDX for API(s) 1.3.1, 1.4.0
DevTools 1.10.0 by PocketMine Team for API(s) 1.3.1
SimpleAuth 1.7.1 by PocketMine Team, shoghicp for API(s) 1.12.0
PocketGuard 2.1.1 by MinecrafterJPN for API(s) 1.10.0
EssentialsPE 1.1.0 by LegendsOfMCPE Team for API(s) 1.12.0
MineReset 2.0.3 by Falk for API(s) 1.0.0
SimpleMessages 1.2 by Dutok for API(s) 1.0.0
MagicTelePortal 1.3.2 by aliuly for API(s) 1.10.0
SignModifier 1.0.0 by wolfdale for API(s) 1.3.1
ChatDefender 1.1.1 by Falkirks for API(s) 1.6.0
GrabBag 2.2.7 by aliuly for API(s) 1.10.0, 1.11.0, 1.12.0
LiveSigns 1.2.1 by aliuly for API(s) 1.12.0
PaintMyLawn 1.2.0 by shoghicp for API(s) 1.0.0
FireProtection 1.0 by LDX for API(s) 1.10.0
EconomyAPI 2.0.7 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
iProtector 3.1a by LDX for API(s) 1.9.0
BasicHUD 1.0.6 by aliuly for API(s) 1.12.0
ItemCloud 1.1 by onebone for API(s) 1.4.0
EconomyLand 2.0.7 by onebone for API(s) 1.12.0
WorldEditArt 1.0.0_beta_dev_#048 by PEMapModder for API(s) 1.0.0
CommandSigns 2 by Samueljh1 for API(s) 1.0.0
Sneak 1.1 by CrazedMiner for API(s) 1.12.0
EconomyUsury 1.0.0 by onebone for API(s) 1.12.0
EconomySell 2.0.5 by onebone for API(s) 1.12.0
Popper 1.0.0 by Hoyinm14mc,PatchesMCPE for API(s) 1.12.0
PvPWorlds 1 by  for API(s) 1.0.0
PurePerms 1.1.2 by 64FF00 for API(s) 1.12.0
EconomyAirport 2.0.4 by onebone for API(s) 1.12.0
EconomyProperty 2.0.4 by onebone for API(s) 1.12.0
EconomyPShop 2.0.0 by onebone for API(s) 1.6.0, 1.7.0
EconomyShop 2.0.5 by onebone for API(s) 1.12.0
PureChat 1.2.8 by 64FF00 for API(s) 1.11.0
BattleKits 1.0.4 by Falkirks for API(s) 1.0.0
KillRate 1.2.2 by aliuly for API(s) 1.10.0

**Comment by Painmcpe** [comment]
I am sure that is EssentialsPE error

**Comment by iksaku** [comment]
I'm sure it isn't... Well, I can't test on 64bit environment, but anyways I can't reproduce it on 32bit one

**Comment by iksaku** [comment]
It seems that there are tons of issues with 64bits environments... Please try with a 32 one instead to prevent issues ;)

**Comment by PEMapModder** [comment]
I don't think it is related to 32-bit or 64-bit.

**Comment by PEMapModder** [comment]
This is a duplicated issue anyway.
