### ISSUE TITLE
Error when starting server. Plugin wont start..

### ISSUE THREAD

**Issue by mariusbjornor** [LegendOfMCPE/EssentialsPE#145]
[18:00:58] [Server thread/NOTICE]: ArrayOutOfBoundsException: "Undefined offset: 3" (E_NOTICE) in "/EssentialsPE.phar/src/EssentialsPE/Loader" at line 437

When i delete EssentialsPE folder and plugin load as new it works fine. But from before i had these files.. When i added content again after "installing" plugin over again. I restart server and it doesnt load again..

Warps.yml -> http://hastebin.com/oziruxoqap.md
Nicks.yml -> http://hastebin.com/irisokahun.hs
Homes.yml -> http://hastebin.com/zagoqiqesi.sm

**Comment by LDX-MCPE** [comment]
What version of EssentialsPE are you using?

**Comment by mariusbjornor** [comment]
Latest version 1.1.0

**Comment by iksaku** [comment]
Please use the latest release, it will fix that bug ;)

https://github.com/LegendOfMCPE/EssentialsPE/releases/latest

**Comment by mariusbjornor** [comment]
Will that version work on Poketmine dev build?
