### ISSUE TITLE
nick doesnt work

### ISSUE THREAD

**Issue by Lucario2** [LegendOfMCPE/EssentialsPE#148]
I cant do /nick

**Comment by iksaku** [comment]
check your permissions:
`essentials.nick.use`
`essentials.nick.other`

**Comment by Lucario2** [comment]
No.

**Comment by Lucario2** [comment]
Don't close this issue for thats not the freaking problem. (pardon me)

**Comment by Lucario2** [comment]
The nick command litterly doesnt work

**Comment by iksaku** [comment]
Your issue is directly related to permission nodes, so if you can't fix it just keep commenting... Or learn how to use "Permission Managers"

**Comment by Lucario2** [comment]
NO!!!!!!!

**Comment by Lucario2** [comment]
MY nick ingame doesnt work

**Comment by iksaku** [comment]
Depends on your EssentialsPE version... Please use the [latest release](https://github.com/LegendOfMCPE/EssentialsPE/releases/latest)

**Comment by Lucario2** [comment]
When I do .nick [Owner]Lucario it says u are now [Owner]Lucario but when i chat im just lucario

**Comment by Lucario2** [comment]
Yes, I have latest version.

**Comment by Lucario2** [comment]
This Is a new problem to the plugin

**Comment by Lucario2** [comment]
Please reoen this issue it isnt fixed. -_-

**Comment by Lucario2** [comment]
And help me plz

**Comment by iksaku** [comment]
Finally you provide a valid answer!
I have fixed it... update coming in a minute... maybe 1 day to forums

**Comment by Lucario2** [comment]
Im not trying to be annoying but your plugin was awesome still is just help me plz

**Comment by Lucario2** [comment]
I do some coding... I am trying to learn can u show me updated code?

**Comment by iksaku** [comment]
Look at 9c90276df49a7d737bb21d783d9fe1d3dac4ea72 (The commit that fixes everything...)

**Comment by Lucario2** [comment]
Wow you know your stuff!

**Comment by Lucario2** [comment]
Im super impressed.

**Comment by Lucario2** [comment]
Is it ok If i give u some ideas for plugins sometimes?

**Comment by Lucario2** [comment]
Is there anywhere where I can give u a plugin idea?

**Comment by iksaku** [comment]
Hmmm You can send me a message on Pocketmine forums... Or even ask me via [Twitter](https://twitter.com/iksaku2)

**Comment by Lucario2** [comment]
I got banned from there I get a little crazy sometimes

**Comment by jython234** [comment]
Heh.

On Monday, August 10, 2015, Lucario2 <notifications@github.com> wrote:

> I got banned from there I get a little crazy sometimes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegendOfMCPE/EssentialsPE/issues/148#issuecomment-129652948>
> .
>


--

**Comment by Lucario2** [comment]
What.

**Comment by iksaku** [comment]
I think I know why you got banned @Lucario2 ...

Hello @jython234!

**Comment by iksaku** [comment]
Please @Lucario2 ... this aren't forums....
