### ISSUE TITLE
I cant gamemode other people LOOK ASAP SERIOUSLY

### ISSUE THREAD

**Issue by Lucario2** [LegendOfMCPE/EssentialsPE#152]
I cant gamemode other people

**Comment by Lucario2** [comment]
There is a tremndous amount of bugs in essentials pe

**Comment by Lucario2** [comment]
Please don't close this without explaining why you are. I really cant gamemode people I cant do /gamemode 1 [Player] and I cant do /gmc [player]

**Comment by LDX-MCPE** [comment]
This is a duplicate issue.
