### ISSUE TITLE
I seriously can't gamemode people. Don't close this issue. ITS NOT FIXED

### ISSUE THREAD

**Issue by Lucario2** [LegendOfMCPE/EssentialsPE#154]

**Comment by Lucario2** [comment]
i really CAN'T GAMEMODE PEOPLE

**Comment by Lucario2** [comment]
I'll try to make a video

**Comment by DinoKill** [comment]
You'll have to give more info then that if you want help... "I REALLY CANT GAMEMODE" doesn't really tell us much. What happens when you do? Is there any crash report?

**Comment by Lucario2** [comment]
No.

**Comment by Lucario2** [comment]
It just says you don't have permission to this this or something

**Comment by Lucario2** [comment]
It's a huge problem for me. I need to gamemode my players and admin what do I do?

**Comment by LDX-MCPE** [comment]
This is a duplicate of #149. Please stop opening duplicate issues, or we will be forced to block you from the EssentialsPE repository.

**Comment by DinoKill** [comment]
This is not our problem this is a problem with your permission setup.

**Comment by 64FF00** [comment]
@Lucario2 https://github.com/LegendOfMCPE/EssentialsPE/wiki/Permission-Nodes
