### ISSUE TITLE
/condense

### ISSUE THREAD

**Issue by Falkirks** [LegendOfMCPE/EssentialsPE#157]
>This command allows you to condense items in your inventory to the more condensed form. This command by default will condense all items in your inventory that can be uncondensed using a workbench.
>
>If you use [<itemname>|<id>|hand] it will attempt to condense only items of that type, even if they cannot be easily uncondensed.
>
>If you use [inventory|all] this will condense everything in your inventory, even if they cannot be easily uncondensed.

**Comment by iksaku** [comment]
I never understood this feature :P

**Comment by Georggi** [comment]
Just a fast way of crafting blocks from diamonds\redstone\gold\etc

**Comment by iksaku** [comment]
Ohhhh! :3

**Comment by PEMapModder** [comment]
So actually you could just remove all items and add them one by one and let Inventory::addItem calculate the rest?

**Comment by iksaku** [comment]
Good suggestion @PEMapModder, I will take a deeper look inside EssPC to see how all calculations work :3

**Comment by iksaku** [comment]
Implemented with 2d0b9a5c74983218a39bacd352986eee26c33c64
