### ISSUE TITLE
Error on player death

### ISSUE THREAD

**Issue by Falkirks** [LegendOfMCPE/EssentialsPE#163]
![screenshot_2015-09-05-16-29-39_www kepfeltoltes hu_](https://cloud.githubusercontent.com/assets/5827558/9699954/77283f34-53a8-11e5-9b6e-f521ee995d12.jpg)

**Comment by iksaku** [comment]
I think this modifications could help...
_API_:
```php
/**
  * @param Player $player
  * @param Position $pos
  */
public function setPlayerLastPosition(Player $player, Position $pos{
    $this->getSession($player)->setLastPosition($pos);
}
```

_BaseSession_:
```php
/**
  * @param Position $pos
  */
public function setLastPosition(Position $pos){
    if(!$pos instanceof Location){
        $pos = Location::fromObject($pos, $this->getPlayer()->getLevel(), $this->getPlayer->getYaw(), $this->getPlayer->getPitch());
    }
    $this->lastLocation = $pos;
}
```

**Comment by Falkirks** [comment]
@iksaku I would like to figure out what is causing the issue though.

**Comment by iksaku** [comment]
It's directly relaed to PMMP API sending wrong instances... It's sometimes related to people using modified server instances or directly breaking trough plugin's API; but it's mostly related to PMMP fault

**Comment by Falkirks** [comment]
@iksaku I will implement a fix when I have a chance, if you have time, feel free to commit a fix yourself.

**Comment by iksaku** [comment]
@Falkirks I would like to fix it too, but right now I'm also busy with school :$

**Comment by pomee4** [comment]
Can it cause my e_errors in player__32 bit??

**Comment by iksaku** [comment]
@pomee4 It shouldn't, the main reason for "random crashes" still unknown... We have a theory on what it could be, but nothing confirmed yet

**Comment by pomee4** [comment]
@iksaku me and my friend realised, on pocketmine build #1244 it doesnt crash.I hope it may can me helpfull ;)
