### ISSUE TITLE
Crash Running EssentialsPE's AFKKickTask

### ISSUE THREAD

**Issue by flaxues** [LegendOfMCPE/EssentialsPE#164]
Running PocketMine 1.6 build 29
Latest EssentialsPE download able on the Pocketmine forums
version 1.1.2

Crashdump: http://pastie.org/10423848
Console error: (http://pastie.org/10423846

**Comment by Falkirks** [comment]
This is fixed in 1.1.3.

**Comment by flaxues** [comment]
Could you give me the source or .phar? or is it not done yet?

**Comment by Falkirks** [comment]
The source if on the `master` branch of this repository, there isn't a release built yet.

**Comment by flaxues** [comment]
Ok thnx :)
