### ISSUE TITLE
Error: Call to a member function hasPermission() on null

### ISSUE THREAD

**Issue by NML32** [LegendOfMCPE/EssentialsPE#165]
When running EssentialsPE my server crashes with the following error.

Error: Call to a member function hasPermission() on null
File: /src/pocketmine/Player__64bit
Line: 449
Type: E_ERROR

**Comment by PEMapModder** [comment]
Pease provide more information

**Comment by NML32** [comment]
what more info do you need

**Comment by jojoe77777** [comment]
I think this is caused when an AFK player logs out, and EssentialsPE tries to get a perm from them? I heard that somewhere on the forums.

**Comment by PEMapModder** [comment]
The full crash dump. Before we confirm that this is a new issue, closing the issue.

**Comment by Pub4Game** [comment]
@PEMapModder Please reply me on the forum about the duplicate messages

**Comment by PEMapModder** [comment]
@Pub4Game this is the EssentialsPE issue tracker. Please do not post irrelevant comments here.
