### ISSUE TITLE
Automatic PHAR builds using Travis-CI

### ISSUE THREAD

**Issue by iksaku** [LegendOfMCPE/EssentialsPE#169]
Travis-CI is capable of testing PHP code and deploy it, it's even possible to create automatic Releases and make commits. We're going to aproach these features in order to provide a better testing environment to our followers.

TO-DO list:
- [x] Rush iksaku to release his "Travis-Builder" scripts

**Comment by PEMapModder** [comment]
I am not sure about the deployment part. How can you counter fake deployments by copying your deployment code?

**Comment by iksaku** [comment]
@PEMapModder I don't understand your question... But just to be sure, it's possible to create "releases" and even push "commits" into the repo, just need some secret code and everything will be OK

**Comment by PEMapModder** [comment]
@iksaku that's exactly the problem. Where can you put some "secret code"? Unless you use a private Travis-CI repo, all code run in Travis-CI has to be public AFAIK. I don't understand how you could make it private to avoid imposers.

**Comment by iksaku** [comment]
Do you mean Github Access Token? Then let me tell you that there's a way to hide it from public viewing, so only things that the script wants to show will be shown ;)

**Comment by PEMapModder** [comment]
OK, and I want to know how :D

**Comment by iksaku** [comment]
I'm making a "Travis-Builder" project, everything to know about Travis->Github connection will be there. Also this project will be to implement in any project, just small configuration on `travis.yml`|`Travis Repo settings (Recommended)` and fork the project as a folder into your repo :3

**Comment by PEMapModder** [comment]
Oh I didn't know you can tell Travis anything apart from from .travis.yml :fearful: I was thinking that anyone can just run the commands from .travis.yml and get the same results.

**Comment by iksaku** [comment]
@PEMapModder Well, that's true, you can get the same results from running commands inside `.travis.yml` file, or go deeper using a script

**Comment by PEMapModder** [comment]
So there is security vulnerability eventually, right?

**Comment by iksaku** [comment]
Not at all, to store "secret" variables you can use Travis-built in "encrypt" command in CLI and just add it to the "variables" array inside `.travis.yml`

**Comment by PEMapModder** [comment]
Or someone can simply fork EssentialsPE, make malicious modifications and run Travis upon it. Not even any needs to modify Travis commands.

**Comment by iksaku** [comment]
Hmmm, not at all... The `travis script` will be "forked", so only we will be able to make changes to its source by updating both: the tragos-script repo and plugin's submodule reference.
Also, I made it so no other process more than the "script" itself have access to the "Github token", so no pull request will be able to get it and make bad usage out of it
