### ISSUE TITLE
Add costs to Special Signs

### ISSUE THREAD

**Issue by SoyPro** [LegendOfMCPE/EssentialsPE#172]
Can you add when you put a repair sign or a gamemode or heal sign,it has to included the money.see in the first line you put [Heal] and then in the second line $50 or more money.do you understand?.and please fix the command /heal,it doesnt work fine,because when i put /heal or other people,it doesnt heal the life,it takes you life and then kill you.

**Comment by iksaku** [comment]
First of all, money API is not yet implemented in EssentialsPE, so no money for now.

Also, as you may know, the "Heal" management has been weird since 0.11 update, I will try to fix it, but nothing guaranteed to come soon...

**Comment by SoyPro** [comment]
Ok but fix it soon the heal my vips players ask me why ocurred this

**Comment by iksaku** [comment]
Sorry but I can't provide you something right now, it may take several days to come, also no release will be done until 2.0.0 is finished :P

**Comment by SoyPro** [comment]
Ok thanks iksaku.

**Comment by Sandertv** [comment]
Economy has been almost fully implemented, and I'll try to add prices for the special signs soon.

**Comment by SoyPro** [comment]
ok @Sandertv, and update essentialspe i would lile to use it

**Comment by Sandertv** [comment]
It's implemented and added in the latest commit.

**Comment by SOF3** [comment]
@Sandertv it would be great if you specify exactly which commit when you close an issue.

It would even be better if you put in your commit message (title or body) "Fixes #172", such that GitHub would [automatically close the mentioned issue](https://help.github.com/articles/closing-issues-via-commit-messages/) as the commit is pushed to the default branch (master).

**Comment by Sandertv** [comment]
Yeah true, I just forgot this issue/request was still open.
