### ISSUE TITLE
When you add commands or features to this plugin please you have to do it not people!

### ISSUE THREAD

**Issue by SoyPro** [LegendOfMCPE/EssentialsPE#177]
Why dont you put the commands you add to this plugin yourself!!,because i dont know how to put the new commands you add,and the features,i downloaded the master-since and there are plugin.yml,.gitgore.yml,resources,src,readme,a folder call EssentialsPe and here there are the events,commands,and others,i want you to do this you,because i dont know!!!

**Comment by SoyPro** [comment]
I want the new commands,this is a fail!.So do it or i have to unistall the plugin -.-,this a great plugin!

**Comment by iksaku** [comment]
It appears that you don't understand how things work... Let me tell you that "everything unavailable" are things that "doesn't work at the moment", don't be up to every commit pushed, as it may only include important references for developers interested in the development of this plugin, either to help or expand it... 
`If you want something quick and as you want, do it by yourself`
