### ISSUE TITLE
Super dev glitch

### ISSUE THREAD

**Issue by InfornoFire** [LegendOfMCPE/EssentialsPE#180]
Essentails PE 2.0.0 has issues with warps, it is not compatible with simplewarp and will be deleted when stop and start. The stop and start is fixed in 1.3

**Comment by iksaku** [comment]
Can you provide a more explicit description on how to reproduce the error please?

**Comment by InfornoFire** [comment]
Lets see, so i make a warp with your, umm, uhh, oh yea, source code, it works great, then I /stop, and reboot and it was deleted, not the same case with the one before 2.0.0, i think it was 1.1.3

**Comment by InfornoFire** [comment]
Btw, did this died, or is it in vacation or long work mode

**Comment by iksaku** [comment]
The next release is a long-term development... Unless I get tons of time to implement missing features (=ﾟωﾟ)ﾉ

**Comment by InfornoFire** [comment]
Merry Almost Christmas man, enjoy!

**Comment by iksaku** [comment]
Fixed via 7d3d5b210ef6d6a53a45220ae52a80ad6fdd92b0
