### ISSUE TITLE
Real implementation of 'Ping' command

### ISSUE THREAD

**Issue by iksaku** [LegendOfMCPE/EssentialsPE#191]
What is needed?
* Implementation of 2 new `Data Packets`

How will it work?
* We are going to send a `Ping` packet to the user who executed the command, this when the command signal is passed to the system.
* A `Pong` packet should be send to the server when the previous `Ping` one reaches the player.
* When the `Pong` packet is received and processed by the server, the system will calculate the time elapsed since the command execution and deliver a `Text` packet to the client containing the `Ping Latency`

Useful links:
* [Ping-Pong Packets](http://wiki.vg/Pocket_Minecraft_Protocol#Ping.2FPong)

**Comment by InfornoFire** [comment]
Seems like a good idea

**Comment by PEMapModder** [comment]
Make sure that theory works? The packet isn't removed?
