### ISSUE TITLE
Bug in v 2.0.0 with /afk

### ISSUE THREAD

**Issue by SoyPro** [LegendOfMCPE/EssentialsPE#192]
[Server] [24:09:56] critical> Unhandled exception executing command 'afk' in afk: Object of class EssentialsPE\BaseFiles\BaseAPI could not converted to int
[Server] [25:15:01] notice> ClassCastException: "Object off class EssentialsPE\BaseFiles\BaseAPI could not converted to int" (E_NOTICE) in "/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseAPI" at line 261

**Comment by PEMapModder** [comment]
Duplication of #193
