### ISSUE TITLE
Conversion of BaseAPI to int

### ISSUE THREAD

**Issue by SoyPro** [LegendOfMCPE/EssentialsPE#193]
ClassCastException: Object off class EssentialsPE/BaseFiles\BaseAPI could not converted to int" (E_NOTICE) in "/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseAPI" at line 261

**Comment by InfornoFire** [comment]
I got
[(You don't need to know)] critical> "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Undefined offset: 0 on EssentialsPE\EventHandlers\OtherEvents
[(You don't need to know)] notice> ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/plugins/EssentialsPE_v2.0.0.phar/src/EssentialsPE/BaseFiles/BaseSession" at line 547
