### ISSUE TITLE
EssentialsPE and PurePerms

### ISSUE THREAD

**Issue by MilkoIvanov** [LegendOfMCPE/EssentialsPE#194]
It seems like when im using PurePerms the player homes gets deleted every time they logout from the game.EssentialsPE or PurePerms problem?

**Comment by PEMapModder** [comment]
So:

- [ ] Tested without PurePerms that homes work properly?
- [ ] Tested with PurePerms that homes don't work properly?
- [ ] Made sure that other factors didn't affect the result?
- [ ] Deleted all data (at least all homes data) on your (test) server every time before you test the above so as to confirm that it is a fair test?

**Comment by iksaku** [comment]
What version of EssentialsPE are you using? 
In version 1.13 a bug was introduced, making it so the code didn't properly "read" the homes by a player.

**Comment by MilkoIvanov** [comment]
Tested without PurePerms works perfectly,and tested with PurePerms the homes are getting erased every time.And my verison is 1.1.3

**Comment by MilkoIvanov** [comment]
Also having problems with the warp command,even if I have set perms to group/user still the same " You don't have perms..."

**Comment by iksaku** [comment]
In 1.1.3 bugs where introduced to the proper reading of `Homes`, also `Warps` had problems due to permission node registrations, they were all solved now
