### ISSUE TITLE
Add config option to disable colorMessage()

### ISSUE THREAD

**Issue by alex2534alex** [LegendOfMCPE/EssentialsPE#195]
After I install EssentialsPE on my server, players can't type any messages in chat. But, if I disable CustumChat or EssentialsPE, all be OK again :/. Please fix

**Comment by MilkoIvanov** [comment]
Check CustomChat permissions and add them to the Guest group if you haven't

**Comment by alex2534alex** [comment]
You mean PurePerm?

**Comment by MilkoIvanov** [comment]
Yeah add CustomChat permissions to your PurePerm group,I think that's the problem

**Comment by alex2534alex** [comment]
Hm, if plugin use color text, EssentilasPE sent "setCancelled()" function. As example, SimpleAuth. I use there color text. And, if player try to login, plugin must sent message "§6 Welcome!". But, EssentialsPE used "set canceled()", and login was canceled and sent player this: "You can't login on this server".
P.S.: sorry for my English, if I somesing tell wrong :З

**Comment by alex2534alex** [comment]
@MilkoIvanov , because of this, it's not only CustomChat problem :\

**Comment by alex2534alex** [comment]
Problem is in EssentialsPE

**Comment by alex2534alex** [comment]
And this problem is not just me
![screenshot_2016-02-03-10-08-40 01](https://cloud.githubusercontent.com/assets/15706847/12776389/4ffe3a80-ca5e-11e5-87b5-76fddde60f11.png)

**Comment by MilkoIvanov** [comment]
Well when a small plugin is developed like CustomChat it should be made to be compatible with almost every Big plugin like EssentialsPE. However, you sure that you can't fix this with permissions?

**Comment by alex2534alex** [comment]
Yes. Not in permissions problem

**Comment by PEMapModder** [comment]
From what I see from the current code, it wouldn't have any problems unless your chat messages contain a `&` or a color sign.

**Comment by PEMapModder** [comment]
@iksaku I would recommend allowing to disable checking color signs.

**Comment by alex2534alex** [comment]
But If I want to use § ?

**Comment by PEMapModder** [comment]
@alex2534alex then give yourself the permission.

I suggest @iksaku to add support to whitelist/blacklist certain commands/RegExp patterns that allow/disallow players to type chat with that symbol.

**Comment by alex2534alex** [comment]
@PEMapModder , what the permission?

**Comment by PEMapModder** [comment]
`essentials.colorchat`

**Comment by alex2534alex** [comment]
But I op? Why I must give me this permission?

**Comment by PEMapModder** [comment]
Are you sure you have that permission? If you do, you would not have a problem with that.

Use DevTools `/checkperm` to ensure that it does.

**Comment by alex2534alex** [comment]
@PEMapModder 
![screenshot_2016-02-03-11-46-11 01](https://cloud.githubusercontent.com/assets/15706847/12778553/ecf9405c-ca6b-11e5-9b79-f2e63425516d.png)
I'm sure —_—

**Comment by PEMapModder** [comment]
@alex2534alex oh, for that, just wait until @iksaku adds the option to disable it.

**Comment by PEMapModder** [comment]
I have not confirmed about the CustomChat issue. Could you elaborate on how players can't chat?

**Comment by alex2534alex** [comment]
That can't typing anything in chat. Because CustomChat used color prefix: §6[§1Player§6]

**Comment by alex2534alex** [comment]
Please read this
![screenshot_2016-02-03-11-55-37 01](https://cloud.githubusercontent.com/assets/15706847/12778742/1a6e4202-ca6d-11e5-8fe9-37c9fef27f26.png)

**Comment by alex2534alex** [comment]
If at least some plugin uses colored text using "§", EssentialsPE, in my opinion, sends "setCancelled ()"

**Comment by alex2534alex** [comment]
@PEMapModder , what can u say about this?

**Comment by PEMapModder** [comment]
This may have something to do with the event handler priority. The event handler should probably get a priority of `LOWEST` to make it work.

**Comment by alex2534alex** [comment]
And how can I this myself?

**Comment by PEMapModder** [comment]
@alex2534alex never mind, I have cleaned the comments in this issue.

There is an "edit" button if you use the Desktop version.

**Comment by iksaku** [comment]
Let me clear up this: 
- EssentialsPE doesn't have any string inside the code to send the "You can't login in this server", as it's not part of any feature. 
- As you say, EssentialsPE checks for § and & symbols, but in the "player message" itself, not including the player name. 
- EssentialsPE doesn't "intercept" messages by other plugins. 
Now, @alex2534alex, you arguments are "invalid" as it seems you have problems "Logging" in the server and others complain about SimpleAuth... This is a well know problem with SimpleAuth combined with any "Permission Manager" plugin, as their logic with permissions collide. 

I suggest you to try every single plugin individually in your server to be sure which is the bad one. To do so, just remove all PHAR files from the plugins folder and test the one by time.

**Comment by PEMapModder** [comment]
@iksaku but whatever, you indeed should allow toggling colorMessage.

**Comment by iksaku** [comment]
@PEMapModder it will be easily done... If/Else switch :3

**Comment by PEMapModder** [comment]
Customization is an annoying distraction always.

**Comment by iksaku** [comment]
@PEMapModder I already have the local change :) going to push in 2 more years...

**Comment by Sandertv** [comment]
I don't think this is still an issue right now. Correct me if I'm wrong.
