### ISSUE TITLE
NBT tag level name and folder name differences cause warps in that world to disappear

### ISSUE THREAD

**Issue by InfornoFire** [LegendOfMCPE/EssentialsPE#202]
Doing /warp (name) works, but trying /warp (name) (player) gives an error when its spelled correctly, and gives a professional english language of "[Error] Player nor found"

**Comment by iksaku** [comment]
Warps has been fixed in the development version, but will not be published as a PHAR file until we finish update 2.0.0

**Comment by InfornoFire** [comment]
I found out why, you see when downloading a pocketmine world and changing the name of the world and not the NBT tags, warps in that world will disappear due to not being able to register it well.

**Comment by iksaku** [comment]
You should then run again `/setwarp <name>` in the renamed world, so the location updates
