### ISSUE TITLE
what does this mean?

### ISSUE THREAD

**Issue by Tolo0** [LegendOfMCPE/EssentialsPE#205]
CRITICAL]: "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v1.1.3': Undefined offset: 0 on EssentialsPE\EventHandlers\OtherEvents 2016-02-12 [11:37:51] [NOTICE]: ArrayOutOfBoundsException: "Undefined offset: 0" (E_NOTICE) in "/EssentialsPE_v1.1.3.phar/src/EssentialsPE/BaseFiles/BaseSession" at line 515  2016-02-12 [11:37:51]

**Comment by InfornoFire** [comment]
Lol, essentials pe needs to be updated. Before I give you the fix, YOU ARE BREAKING A RULE. Now to explain, essentails pe does not support php7, now to give you the fix, come here https://github.com/LegendOfMCPE/EssentialsPE and wait until the TODO php7 is checked, and download it and you will be fine

**Comment by LDX-MCPE** [comment]
@InfornoFire By what method did you determine that this issue was caused by PHP 7 usage?

**Comment by InfornoFire** [comment]
For one, php7 is not compatible said inside the README.MD. Trust me I tried and got the same result on load up.

**Comment by PEMapModder** [comment]
And the fact is, we are talking about PHP 5 here.
