### ISSUE TITLE
Update to support PHP7 and MCPE 0.14 ?

### ISSUE THREAD

**Issue by roroB20** [LegendOfMCPE/EssentialsPE#206]
EssentialsPE plugin is unusable on PHP 7 build for 0.14 of ImagicalMine, a server software based on PocketMine with a reactive team which continue development for new MCPE version (because of low activity in PM development for now) ! So the last builds seem to working correctly so it's a good time for doing tests on it !
Then can you start updating this amazing plugin for PHP 7 and MCPE 0.14 ;) ??

**Comment by roroB20** [comment]
And a link to ImagicalMine Project ^^ : https://github.com/ImagicalMine/ImagicalMine/tree/php7-0.14

**Comment by PEMapModder** [comment]
EssentialsPE is a PocketMine plugin. It only supports and will only support the official PocketMine API.

**Comment by Lucario2** [comment]
I see negativity.

**Comment by Lucario2** [comment]
I'm not a big talker like PEMAPMODDER but, this is kinda serious...
