### ISSUE TITLE
/vanish command not working

### ISSUE THREAD

**Issue by Aericio** [LegendOfMCPE/EssentialsPE#208]
When I do /vanish, it vanishes me for 1 second but then makes me visible again.
![image](https://cloud.githubusercontent.com/assets/16523741/13166548/3069ec6c-d66d-11e5-8f8f-2f476c5a96d3.png)
(I am using the latest version)

**Comment by InfornoFire** [comment]
I believe vanish is a plugin, not a part of IM

**Comment by InfornoFire** [comment]
I have no idea

**Comment by LDX-MCPE** [comment]
@InfornoFire Then don't comment.

**Comment by Aericio** [comment]
After a phar file sent by tolo() ([In this thread](https://github.com/LegendOfMCPE/EssentialsPE/issues/211), the /vanish was fixed.

**Comment by PEMapModder** [comment]
Then that means it is still not fixed on this repo, right?

**Comment by Aericio** [comment]
On the thread he sent it in, it was an old version of EssPE. Sorry :(
