### ISSUE TITLE
CRASH on PHP 7

### ISSUE THREAD

**Issue by CyberPowerCrazii** [LegendOfMCPE/EssentialsPE#209]
ImagicalMine Crash Dump Fri Feb 19 19:08:00 AKST 2016

Error: Cannot use pocketmine\nbt\tag\String as String because 'String' is a special class name
File: /EconomyProperty_v2.0.6.phar/src/onebone/economyproperty/EconomyProperty
Line: 38
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[29] use pocketmine\level\Level;
[30] use pocketmine\level\Position;
[31] use pocketmine\math\Vector3;
[32] use pocketmine\block\SignPost;
[33] use pocketmine\block\Air;
[34] use pocketmine\tile\Sign;
[35] use pocketmine\block\Block;
[36] use pocketmine\item\Item;
[37] use pocketmine\nbt\tag\Compound;
[38] use pocketmine\nbt\tag\String;
[39] use pocketmine\nbt\tag\Int;
[40] use pocketmine\tile\Tile;
[41] 
[42] use onebone\economyapi\EconomyAPI;
[43] 
[44] use onebone\economyland\EconomyLand;
[45] 
[46] class EconomyProperty extends PluginBase implements Listener{
[47] 	/**
[48] 	 * @var \SQLite3

Backtrace:
#0 (): pocketmine\Server->crashDump(boolean)

ImagicalMine version: 1.0dev #0 [Protocol 43; API 1.14.0]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT DESKTOP-APCPU4Q 10.0 build 10240 (Windows 10) i586
PHP Version: 7.0.1
Zend version: 3.0.0
OS : WINNT, win

Loaded plugins:
AdminFun 1.0.0 by hoyinm14mc for API(s) 1.12.0, 1.13.0, 2.0.0
Alias 1.2.0 by ZacHack for API(s) 1.12.0
BuyCraft 1.0.1 by Falk for API(s) 1.0.0
Cameraman 1.1 by ChalkPE for API(s) 1.12.0, 1.13.0, 2.0.0
CrateKeys 1.0.5 by CDFalcon, CDFalcon for API(s) 1.13.0
CustomAlerts 1.6 by EvolSoft for API(s) 1.12.0
DDNSUpdater 1 by Falk for API(s) 1.2.0
EconomyAPI 2.0.9 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyAuction 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyCasino 2.0.2 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyJob 2.0.4 by onebone for API(s) 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.4.0, 1.4.1
EconomyLand 2.0.9 by onebone for API(s) 1.12.0

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrdWgtz27aW/isY5c406YiyXn6p47vr2s7ebJ1YjZ3NzlZ3PCAJSaxJgiVAy2qn/32/cwBSlGyn
vunu7NzNJBEBHByc8+G8APK3jk0y1ZkMxvv7x+PB8Kjf7aiy1GVn8lvHrgsMdS5uz67eT99dXtxe
fPx49bHT7WTKGLmgsTOZ59qKyihR6OhO2SzJ1WyWh3Y2s3Ixm13bMskXQhrhn0IVSSL/xrW/EYkR
UphCRYlMRZRKY0QuIVO3M09SWmPvItK5ztbTUheqtOvb+2Gv3zvoFUtZ7pky2tO5CvFvTzm6wtPt
zgPHFNJ1JqOj37udIq0WSd6Z2LJS3U6kY0UqD4+x4K42qbpX6Wx2ST/fgcuo/zzRVJvEJjpnusET
dJm0y9nsP1RkdTliquETVGGKBtBLFjk4WqYbPU93mpRMMn6CxAJFx4lJ9p/n8j39MNHBE0SJVdls
9g7/M8nhEySbbT/TWaGrPGbSoy+SOjtgwuMvEr7LGYdx/1klb/A/kxDw9FtD6y1kNvMmIotkNvPm
cTp9x3NGfs74mTmpzONm0qV0uo33/SxCzBnvjtUJ9WBVHhsxZYP7XoJ1khWpylRujbhMDIZV+Rsx
IUxndu/bb6lxxA3xrfjXe1kK4PTjJbZg1IHt2lJGMNefOq/64vWbyRYS16q8V2Xw16iUZnleZcXr
UOtUyfxN5+/dzoLWkimZOqgMDBWrDHr9WN1jzbBK0rgzQQyAD1kdaRCOR90O4GKywbjXB9kisWj2
X/gHE0p5lyYhzekdMYeKPXzS+ZzksV4Z8eFGnF9c/3BzNQ1Op2fTT+MfxaDf6wsWCI/DMRStiQf9
NyLZPzoAn2JZgMshwsEArV+BM5ojNPtu8FYbWuXdhw836ODGCk7fuL8hIE5jIPe2yunZy9V0dbdh
Yr6ysktdGsJ/qddJng3GWUTgMkw/EU5DJsTDiB+GPBMUKpdhqiDkXKYGYSdWBdkGZmHQ6Lk9b3dk
kgJUIwzcfCNWqiXpOr26vvl89fHyHF0rFSL2QPy8SlOoeJom0rSV4va2RsNdjf5LRn+T0d1jdb5a
elp1NnuP1hn5x8tk/75an5VyblviN127ezLY1uCtTLfF/zPYh9U6okURHDfLv0D+M8hcyky2jWrT
t63BjvxnSygwvfhfNKiIVpjNoloehOuWaF/SrrO0tpjs7TGHHqoDUrWUVv2g1m1T2/Ttbtb+jrLn
2C4ETPQ2j1uKj/6Eno0UzvxeopuBcghvyyrsRTrbq2XamzYRNng/DaY+eJD2lbE6O00R6rcAaHdv
Y3CwjcDFvU6vocD/nMe118bWbkviEbi+Of1482n61N6uVqueglDEvmfvSMnz8w/Xn4oYaJYtHdu9
LRUHX/bGP6NZHOemcivOZtvLv8AnN/m+pUSrs71N5GDH2xvl64FHoYXd0v8Om98B/458e+TbY98e
o/21IPxBLfOPYVFFlhV+hIcf2MVk+H+ISXuv/hF8nCobjBrVXo7TmTRJrh/D5Pv/H6AUsSYNSI1i
L8fo33X4GCDq3EVn/M/hVz/rsIHDqfFyLOh48BgM7v2KKPPH2eArN/3RkeYlSlLxLFEsKATeGlI+
c/T8wTtRVGe/mjYtcabzebIQdJ6flbP81XWVi7cqFIeo5SeD8QTV/ekP1zdi2B8cEIHjFxB6J5/X
eMzF35LFsjVU6NKeDI4Ho1GrMynQBRM5OILhHNJApjJdroM0yRKQ4xjxnnoXkvpjddJnGvkQFKlc
Q5uTEfeYQq7ygI5AikPFiZNqtQQI4GXsiZ7PqcdtSPBLpcr1CULMpqsEpjVVpm28qwZdm1R5pPzK
gYyWibp3Z0LPSaapXgXzFDOaBZ1kMk8yWMB2Z6bDpmeuS7Bu1HT8lrKMI12qmqi4L+rHOJnPk6hK
7fpkwADxKdHqMjDKWpzOzQl18xWH25VrWnPTZ5SKWyR0cXTy9vL0hroIil6Byn+ly/jkW/4D7Sqr
AyPva+lKFaNOQXkVoeCqUsm4u6E4MYxpqhdkQbXQdMJrqrLeOkvJ6AQVeiJie6tK5sJmJwCJcEXc
e1fEsSGKm6XCebzWUshSCbvks7/Bg7QichdcIQ7teZRWsYrxIB4ZvON2rTPMnROLXa5GzlVXaIyU
hpiKsFTyTqx1VXpuIpkLbFcyT3gNbFUJ80vXjvUHtWoY7sVqLrFbRqx0/o0VsiiULAVBmkFlIJiu
oQLESIzTfrVUuaiKRSljMOgRS+c3juGEGuLVzbJUgBmdkAaxYVHJhRJ0NcbweS8zCdqpxirJrwyw
m3y2VJHXZ3sqBKkra5X3VsldUqg4kT1dLvaotUdXILd6fvvu+ur2YHQcDG9pHkPasJqIGcLfYtZx
i31eKkJSWA2p8lhAY2H4HgnbVsrcwICAIg8ztiwvZMGTsrzFsbpPIiWWiHopb3rGrJ3rbJblUMsj
ZlnZWJOnudtPEmlW9fvycOx+0s9kMEvajVzF/zIDxtwv3Y/2VO6CBuLqwohMrmFaOTZ3rqStSlVr
eEreLyjY0KWpv60Q94kUP1K0YSKOO4Efmwi6yXSTr5eYK8kNjIZyXmBnBdIzoztbAxQKWBmDhdwB
SiSi2EG/GQogb6iNai9xwXGu5gUQBcUWAY+AwfE971p4M+UJPi42421kX31OsH86h9XKOBalMs64
SVyY8x3EkgbYUHSk6+JQETbYS/VLJVPa5UVyD9p7mVZKvPbLIpu8YfZuTcRkRVkjgJksFqqcYNyt
/qHKQmwI/PbUrPPoRpo7OFZ5B0/tOYpPBviQC9TqEt2yRNqsYG+gN12akcbCR054RReAZEDQUK5n
gJBGqS+rcrgokXju12yRdA1eQNQHxHarAAXUYm/KG/EI4Vqkd3MKB0REbt8Vif0GGNqS58WKMheb
+c5s8Rpa0O3m0GHDmgRe2wnzqoODy50+NPxbqkNATYWFcAOCkyoFw0wtZLi2EE1cO5H6LIQL23Vo
gX6rhEVk+AUlN5+efZdhlOYJzAjxEYkkZ2ZzBKV6TWcSUKtig15oaKTJmwg/XmnBgrqMPxH9Whnx
ihODRYST8T+BGlSwPaHEVJWJ5gxEfmGIb8Rx1zNubH8A64D7x26XmSag25Da6n3M1jnCC3wG0pLP
PqeMUwL1T8rhnLzPkTnujgt8YeNbjXO7ha7Itym/8aze4xnk1r68Bfz0MmiecApWgsR2++PmNrog
hCqE0EbnUd8rbd48I5eHYLSBYCHLEFsQRDpNXbHnDP5JqHlPSSQ/S/hZcKlM5hWn3bY0KEwq2NOb
bu2qjwzKW5QLffN57bTZxlZ74splOm4ZZCFdpXEjSgLXXuViI74zH1Gw9G3bEa/eskk+Cl1sRG5+
o9i81FkdA91sTxG0A8YmH9TK+M18bCNPmNbObCrDo2WV35l6By7ZMylycTfJSYcT0k24srnLXlOi
IDGOKKBqgCqcDTfHrDYA71KDNi7n2k3e3VaK21RFuanbfNxqnvDP4rDtLJxIUAbD0Gso6grYr0pD
7fz5x0zpX64sbVur1oMtpS6vhdLiAEKFhqQSGekMBuiDIfuuq2j9qIuAoWoynIpbmcybeT1GwaNc
W+LeFcGg5QEuk/HSga3FmYCmDk6b9MnHCspbsYudfpvdZHR6wXp8vgLwJ6ikYexn009dzIUQIcLY
Kont0oVcHx+aBQJeAJGhyfebWsAwQi3injiN4YlLmc7p1bMrUWIFi/SLYVlnqTpvu3Ir4ba4bRVC
Fw/kuFTnyLTrwgIt7t989QQMS7EjUAr/NM2ndQGwqfupxqFJKxz3mGlV5EXgO7YLLz5cqbBaTJqa
4q9iQLWE22FDZSQT1CWk4Xi4VHVp6Wp0h92gXRgasWcsClpY0t4iquFGlIzNtrfU58edg4iqi0dS
Bcq5wxgTe/MjBNgWImBrvQX6SYGbNHETerG0jYL8up/Ev6cLcRfo5NYiiMd04rMtGQCyfSwSe7ff
1lcfrm4uJoKjOf5GFQ5vOQ5vzKp53eul9Ks3UrYM4HRrLyOcThCPvNpsZ5z4IA/ZlSXbGvZ9gqKw
6PKfMzQ6YNOIT3pN6b49UEfEuhi+Jv8mZUN6Ub1Z8vUATvXEWl0xxMDgqQFlo94b7+NGtWXxpnJD
3Ono5q9fhEJkc2tSxeG2l4/Mm7M0xQ4+GlGp5CKITFdybRx/z2nHyLdyg7ex00xXeTu9GF+o1cKQ
KsTTnSEQ86kBoL40XZb00YPTw/HZzW2++HiCARtfrtyxNVSOYajmFMj4iocCHu1Mi7G7+mkFz9G+
30Z5r+izGkQTOqcrOp4Va3834dNdU1NxjJlLYxloBqmJg/MqZUJtYM0B+XQSuRTFB7SSrgJgMWBc
4/azphOScyAjMzKizAdcSlwNEO0o4DaIAN5s0Hv5IOQuSDggRZxwNraysz/7Ht+PMk4q05rq90Z6
Qdmp6+neNmkGOLioRvdugXvb1LYnEaVKusX4LvApRTanwI0uvcfK+Fi6kgkf8nGcr5TffM/BBwwe
CQz2cSIOvpJjoYsqbTj6FqW+NvP9Wg/25gCoOgXcjWPA5gYwxn0HcoYsYOlKyPcPmgBDN3uQte8J
/c7TZyhVMRHH/ab+chbMQaiudjxX46tX4VfftFf0zi/Y7ZVZmMBlIEWjBYc6d+yf1OGNbiro0xjh
+l1292ZVG74/ibSCJrlFQNdSu31N5trpL5ZFks9123CWmqyFF++1bi5RlzXy5jpfZ3RgYUcz2AXT
EpwOY55AbAhYAVipFHKxKHGIdbcPzS0PVbT0wdDd89o5yYileU4yQtK/ep08wwW25Cgm9TaVeeAL
hRaZ69fF1o3VGd2I8qWcSnVBubKLNnSie0e7qRZRNc1R8StsBnJjTnUHkTXpvTL8tWGbkfDvW1p1
TYUS2ViXXuuo6vm5HXQE9RrmEVT0jvwZoOhzl7pwRz0nKffXTSqosJYXaFJL5gfhMnQpOBE/0WOA
NNflW8K/17xd2N3USO07ZlasPg25Q2p9ic+nz6curflsz9nUcCVDUGQocBKI7IuOLTX8yiyGfxZ0
808BYezbzaoTQS8AJsPvDrv7xw+D7uhh1B1+N/guRnXgYuNrWyo0EMFOjvpiAb8wrjXef+Mv+OHh
C6qFNlf8/tUXf1RH2PFHF2fIka3vwMKIPrJsddDdbx7Lst3lP26t22S3reY8Sfljh6ZjCa91n7CQ
WFTBtQZ/Nv7bDvceMovKdWFb49fTy1ariLak/ajm/rTZ6jTucNDusZJUiFtd2dr8kvInb/5J7NPI
MID1i4Depu33x/1DPP7lHTbpUB0O58cHx/1wMD4+koMQZ5JDeTA6jEYjeTQaRP14OD/Y3xd/AW+r
71SOnNDG4NekcB8sudevv7pv+upRtB74JUwDqc7oHWe/PxoMhvSac3p+1RqeLnlD6vfl11wl/+f7
NlLb/FZx/LA9SKeqLQnRtyqT7Z1DLZ7ugpa0gUWTvqukrxMPA/chpGHfNu1poXu/0OpaSxaPv8X6
eMafI/pbGv4IccDfOuHUcxtriwjRmrlo7+JnJe8Q1Xj9EaD4/ff/BtbrgCw=
===END CRASH DUMP===

**Comment by CyberPowerCrazii** [comment]
I know you will update this plugin to php 7 but I just providing you some information to what needs to fix.

**Comment by PEMapModder** [comment]
No thanks, we know what are the changes and this issue is duplicated.

Also, ImagicalMine is not supported.

**Comment by Georggi** [comment]
Also, why are you posting issues about Economy plugin here?

**Comment by iksaku** [comment]
In deed, this report doesn't inclue EssentialsPE in any ways... Not even installed in the server
