### ISSUE TITLE
/tpa Bug

### ISSUE THREAD

**Issue by AndreySK4** [LegendOfMCPE/EssentialsPE#211]
I have a problem./tpa not works.do the same thing as /tpahere

**Comment by Tolo0** [comment]
Lol that's a weird bug. Are u using some other plugin that has tp commands?

**Comment by AndreyR0** [comment]
No

**Comment by Tolo0** [comment]
What version of EssentialsPE are u using? What pocketmine.phar version php5 or 7? Maybe show ur plugins. One could be conflicting with it.

**Comment by AndreyR0** [comment]
I  use EssentialsPE 2.0.0 and Genisys 1.1 PHP7

**Comment by Tolo0** [comment]
Try this version. 

[EssentialsPE-edit.phar.zip](https://github.com/LegendOfMCPE/EssentialsPE/files/143325/EssentialsPE-edit.phar.zip)

**Comment by Aericio** [comment]
Oh. Im having that same bug. Does that edited phar work?

**Comment by PEMapModder** [comment]
@Tolo0 please, if you have fixes, create pull request rather than redistributing phar files of custom edits.

**Comment by Tolo0** [comment]
Sorry PEMapModder won't happen again.

**Comment by Aericio** [comment]
Wait... The file is just an old version of EssentialsPE though...
![image](https://cloud.githubusercontent.com/assets/16523741/13370166/4c4ff0ba-dca4-11e5-9978-483e6cb7d223.png)
So its not really a fix? Just an older version? (unless he edited the older version)

**Comment by iksaku** [comment]
Could somebody confirm that this bug is present in latest `Development0 builds?`

**Comment by LordJoshie** [comment]
Wait. what 'edited phar'  I also use Genisys & have the same TPA issue

**Comment by Aericio** [comment]
Im pretty sure the "edited phar" is literally an older version of essentials.

**Comment by Sandertv** [comment]
Duplicate of other issues.
