### ISSUE TITLE
Incompatible API 2.0.0

### ISSUE THREAD

**Issue by InfornoFire** [LegendOfMCPE/EssentialsPE#215]
The new PHP7 compatible plugin.yml does not work, I tried the old one and it did. I think something had to be change when changing the code to 2.0.0

**Comment by iksaku** [comment]
You should make sure that you're using the latest PocketMine-dev version

**Comment by PEMapModder** [comment]
You mean you only changed the plugin.yml? o.O

**Comment by iksaku** [comment]
Which server software and version are you using?

**Comment by InfornoFire** [comment]
Ima give ul the project, so yea...
