### ISSUE TITLE
Update to PHP7

### ISSUE THREAD

**Issue by Iparft** [LegendOfMCPE/EssentialsPE#216]
Hi

I' have one server on MCPE working on php7 

EssansialPE Is not working on PHP7 
Please adding PhP7 on plugin

AkramYTa

**Comment by iksaku** [comment]
We're already updating to support PHP7, but we may not release the update soon as many optimization checks are need to be performed

**Comment by IrishChevron** [comment]
Any ETA on when release with PHP7 optimization ?

**Comment by iksaku** [comment]
Development versions are already being worked on, but official (final) release may take a while.
You can now download _Develpment PHAR_ files, there is a link in repo's README ;)

BTW: First _Beta 2.0.0_ is coming...

**Comment by thebigsmileXD** [comment]
PHP7 version: is it stable yet?

**Comment by Dog2puppy** [comment]
Can I download the PhP7 and see if it works with my Genisys?

**Comment by iksaku** [comment]
PHP7 is stable... EssPE isn't

**Comment by thebigsmileXD** [comment]
Current bug: client can't join

**Comment by Sandertv** [comment]
This works alright in PHP7
