### ISSUE TITLE
Why i cant download Zip?

### ISSUE THREAD

**Issue by SoyPro** [LegendOfMCPE/EssentialsPE#217]
When the Server enable the plugin it throw: [Server] [23:09:06] [Server thread/CRITICAL]: "Could not load source for EssentialsPE:Incompatible API version
Maybe you are working to update to php7,but im using php5,pls let me download EssentialsPE v2.0.0,because v1.1.3 have bugs,i prefer use v2.0.0

**Comment by Aericio** [comment]
Try updating your Pocketmine version. Not to php7, just a newer version oh php5.

**Comment by PEMapModder** [comment]
@Aericio this is not a correct solution. Please don't turn things opposite.
