### ISSUE TITLE
Cannot /tempban offline user.

### ISSUE THREAD

**Issue by markkrueg** [LegendOfMCPE/EssentialsPE#219]
With earlier versions of EssentailsPE, you could tempban a user even if they had gone offline (say right after they were swearing).

Now, if you do something like:

```
/tempban player 1day swearing
```

It works unless they are offline. If they are, you get this in console:

```
[Server thread/CRITICAL]: Error: "Call to a member function getName() on boolean" (EXCEPTION) in "/EssentialsPE_v2.0.0.phar/src/EssentialsPE/Commands/TempBan" at line 48
```

**Comment by markkrueg** [comment]
Just a quick comment on why it is so important this works:

The primary method of banning players on MANY servers is /tempban. This is because players need to be punished for bad behavior; but a permanent ban is overly harsh.

Unfortunately once players realize /tempban will only work if they are online; they just do their swearing/spamming and then immediately log off before the Mod has the chance to /tempban them. Then the Mod is stuck with errors trying to ban the player that has already logged out.

So it is absolutely critical to the functionality of /tempban that it works for offline players. And I am pretty sure it used to work this way in an older version of EssentialsPE.

Thank you for your consideration and all the hard work in developing and maintaining this excellent plugin!

**Comment by iksaku** [comment]
You got the point! Thanks for your suggestion, I'll be adding this feature soon! ;)

**Comment by markkrueg** [comment]
Thank you so much for this fix!
