### ISSUE TITLE
Set Shop

### ISSUE THREAD

**Issue by roberto12b** [LegendOfMCPE/EssentialsPE#224]
Brother, Type I searched a lot , but I found this plugin anywhere you're looking for a store to set plugin .
Type / setshop [player name ]
there is another player entered / shop [player name ]
I think it's a very simple plugin, with only 3 commands ,
/ setshop
/ store
/ delshop
That would be a privilege for VIPs , and each vip could have only one store ..... brother if you have to bring will be very grateful ....

**Comment by Sandertv** [comment]
Shops and sell posts are being worked on.

**Comment by Sandertv** [comment]
Buy and sell signs have been implemented.
