### ISSUE TITLE
Placing Block

### ISSUE THREAD

**Issue by Marttinek** [LegendOfMCPE/EssentialsPE#225]
Hello, I'm search EssentialsPe 1.1.3 php 7. I changed the API and crash, EssentialsPe 2.0.0 is bugged powertool, the placing blocks = Unkown command,sorry for English.

**Comment by jojoe77777** [comment]
Re-worded: With the latest version of EssentialsPE, whenever anyone tries to place a block, it gets cancelled and says "Unknown command. Try /help for a list of commands.". I haven't used powertool at all, and this is on my private test server.

**Comment by iksaku** [comment]
Duplicated of #220
