### ISSUE TITLE
BaseSession.php error 

### ISSUE THREAD

**Issue by Tolo0** [LegendOfMCPE/EssentialsPE#232]
![screenshot_2016-04-05-00-52-46](https://cloud.githubusercontent.com/assets/13458191/14267523/febd27e4-fac8-11e5-9620-df80e483667d.png)

**Comment by iksaku** [comment]
Which EssentialsPE version are you using?

**Comment by iksaku** [comment]
Is this still happening in latest versions?

**Comment by MajorPlayz** [comment]
I have same problem. The version I have is available here:
http://www.mediafire.com/?kfeldmwywhxuu97
Any suggestions?

**Comment by Sandertv** [comment]
Same problem here

**Comment by MajorPlayz** [comment]
[Look](https://github.com/LegendOfMCPE/EssentialsPE/issues/286)

**Comment by Sandertv** [comment]
This has been fixed.
