### ISSUE TITLE
/tpa teleports the other player to you instead of vice versa 

### ISSUE THREAD

**Issue by Skyladd** [LegendOfMCPE/EssentialsPE#234]

**Comment by dktapps** [comment]
Confirmed this issue with newest commit (still!)

**Comment by Crypthu** [comment]
PLEASE FIIIIIIIIIIIIIIIIIIIIIIIIIIX ><

**Comment by Sandertv** [comment]
Aware of this problem and looking for a fix.

**Comment by Infernus102** [comment]
still not fixed

**Comment by Sandertv** [comment]
I know, didn't find out what the problem is yet.

**Comment by Sandertv** [comment]
I think I found out... Let me try to test if that is the problem.

**Comment by Sandertv** [comment]
It should be fixed. I do not recommend updating yet, I'll test it first.

**Comment by Infernus102** [comment]
did you test it?

**Comment by Sandertv** [comment]
Yeah it didn't fix it yet. I think I found out what the problem is, I just have to find a clever way to fix it.

**Comment by Sandertv** [comment]
You could update though, /tpa works good now, just /tpahere is reversed now.

**Comment by Infernus102** [comment]
Why is this so hard? Even experts cant solve this?

**Comment by Sandertv** [comment]
The way you get the information whether it is a tphere or tpa request is hard to obtain if you don't know who the sender was when doing /tpaccept. It's saved in a way you need the requester's name to find out what the request was. So I have to find a good way for it.

**Comment by Sandertv** [comment]
I think it might in fact work right if you would add the name of the requester in your tpaccept, for example:
/tpaccept steve

**Comment by Infernus102** [comment]
But that would be boring

**Comment by Sandertv** [comment]
Yep, that's why I still have to find a good way to fix it.

**Comment by Sandertv** [comment]
Could you try it with the latest commit? It might work.

**Comment by Infernus102** [comment]
i am working on something else, sorry :( will take me some time!

**Comment by Sandertv** [comment]
Any results yet @Infernus102 or someone else?

**Comment by Infernus102** [comment]
can't confirm, i made my own /tpa and /tpahere

**Comment by Sandertv** [comment]
Ah okay, I'll try and check myself.

**Comment by Sandertv** [comment]
It seems in fact that it is all working! After like a year of this not working I finally fixed it!

**Comment by Sandertv** [comment]
It works as of this commit: 2e5394d2b942193ee694455fdb8fcf6bdcd16b72

**Comment by Infernus102** [comment]
**SanderFTW** 👍
