### ISSUE TITLE
Cannot use "Float"

### ISSUE THREAD

**Issue by TheEpicCooldeal** [LegendOfMCPE/EssentialsPE#246]
I've been getting this for a while which forced me to remove EssentialsPE, due to the fact that it crashes the server/ doesn't allow it to start. Here's all the proof I was able to get:

I'm using Genisys so that I'm able to get 0.14.1 users to join, however, when using this on the 0.14.0 official build, it gave an "Outdated" error. Please fix ASAP! Please ignore the "AST" timezone, I'm using a VPN cause of an incident that happened a while back...

![capture](https://cloud.githubusercontent.com/assets/10473651/14685407/3443593a-073d-11e6-8427-14387968b587.PNG)
![capture](https://cloud.githubusercontent.com/assets/10473651/14685505/6aff1658-073d-11e6-8fbd-0353d4fa7964.PNG)

**Comment by iksaku** [comment]
You are using and old version of EssentialsPE, which is not updated to support PHP7 (nor likes modded versions of PocketMine)

**Comment by TheEpicCooldeal** [comment]
"Old version of EssentialsPE" huh? Which one am I supposed to use? The PocketMine one or the Github one?

**Comment by TheEpicCooldeal** [comment]
I'm using 1.1.3 so this is DEFINITELY VALID....

**Comment by Tolo0** [comment]
I'm using EssentialsPE on genisys. and all works fine

**Comment by TheEpicCooldeal** [comment]
Mind telling me which version?

**Comment by Tolo0** [comment]
same as u.

**Comment by TheEpicCooldeal** [comment]
....

**Comment by TheEpicCooldeal** [comment]
Same Genisys and EssentialsPE?!

**Comment by Tolo0** [comment]
yep

**Comment by Tolo0** [comment]
join my server and u can see lol

**Comment by TheEpicCooldeal** [comment]
Send me both of them..

**Comment by Tolo0** [comment]
I'm not aloud. msg me on kik. tolo000

**Comment by TheEpicCooldeal** [comment]
you sure that you're using PHP 7?

**Comment by Tolo0** [comment]
yes I'm using php7 with genisys phar

**Comment by TheEpicCooldeal** [comment]
gonna add u on kik

**Comment by TheEpicCooldeal** [comment]
And Thanks @iksaku for your amazing help! Gotta love it
