### ISSUE TITLE
Not creating/opening config files

### ISSUE THREAD

**Issue by Bidou0418** [LegendOfMCPE/EssentialsPE#254]
[09:03:01] [Server thread/INFO]: This server is running Genisys version 1.1dev-353 "Ikaros" (API 2.0.0)

[09:00:25] [Server thread/INFO]: 开启中... EssentialsPE v2.0.0
 
Warning: file_put_contents(/home/tcagame_svc1323/stever/1323/plugins/EssentialsPE/Kits.yml): failed to open stream: No such file or directory in phar:///home/tcagame_svc1323/stever/1323/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208
 
Warning: file_put_contents(/home/tcagame_svc1323/stever/1323/plugins/EssentialsPE/Warps.yml): failed to open stream: No such file or directory in phar:///home/tcagame_svc1323/stever/1323/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208
[09:00:25] [Server thread/INFO]: [EssentialsPE] Loading...

**Comment by iksaku** [comment]
Does your `Kits.yml` and `Warps.yml` exists?

**Comment by Bidou0418** [comment]
when i first install essentialspe.phar and start the server, i get the following web console errors;

[13:53:05] [Server thread/INFO]: Enabling EssentialsPE v2.0.0
 
Warning: file_put_contents(/home/tcagame_svc1323/stever/1323/plugins/EssentialsPE/Kits.yml): failed to open stream: No such file or directory in phar:///home/tcagame_svc1323/stever/1323/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208
 
Warning: file_put_contents(/home/tcagame_svc1323/stever/1323/plugins/EssentialsPE/Warps.yml): failed to open stream: No such file or directory in phar:///home/tcagame_svc1323/stever/1323/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208
[13:53:05] [Server thread/INFO]: [EssentialsPE] Loading...

when i go to my to my plugins folder, i see a new essentialspe folder with kits.yml and config.yml.
if i proceed to restarting my server, i dont get these warning messages anymore

however, home and warp functions dont appear to save, because when i restart my mcpe client i get home doesnt exist and warp doesnt exist???

i run genisys 1.1 dev-version 363
but i have had these issues since quite a while

**Comment by Bidou0418** [comment]
i am thinking i do not have the proper latest version even if my web console says i do.
could you provide me a link with a updated working .phar so i can test again?
