### ISSUE TITLE
Homes not being saved

### ISSUE THREAD

**Issue by Bidou0418** [LegendOfMCPE/EssentialsPE#259]
i noticed you fixed the warp command issues.
thank you btw

i am having similar issues with the home command not saving after i restart my mcpe client.
i get the message... home doesnt exist

**Comment by iksaku** [comment]
Are you following our Development channel?

**Comment by Bidou0418** [comment]
What do you mean by development channel?
I update daily through the auto update since i reset everyday.

btw my web console just advised me essentialspe was updated when restarting my server.
So i went ahead and re-tested the home and warp commands and none are working now after i restart the server.?

**Comment by Bidou0418** [comment]
this is my web console display when i use the link for the latest development built;
Warning: file_put_contents(/home/tcagame_svc1323/stever/1323/plugins/EssentialsPE/Kits.yml): failed to open stream: No such file or directory in phar:///home/tcagame_svc1323/stever/1323/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208
 
Warning: file_put_contents(/home/tcagame_svc1323/stever/1323/plugins/EssentialsPE/Warps.yml): failed to open stream: No such file or directory in phar:///home/tcagame_svc1323/stever/1323/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 208
[20:09:46] [Server thread/INFO]: [EssentialsPE] Loading...

**Comment by GlitchPlayer** [comment]
Seems to fine with me.

**Comment by iksaku** [comment]
The file issue has been fixed by commit e7028bed8cab68eb51494ec50e8072f4fa9df734, I'm still interested in knowing if your homes are not saving...

**Comment by Bidou0418** [comment]
i tested home and warp commands and they are now saving and functioning properly.
