### ISSUE TITLE
Disabling?

### ISSUE THREAD

**Issue by GlacierShard92** [LegendOfMCPE/EssentialsPE#260]
I was wondering for a future update, could you in config be able to disable the up coming Economy and the /warps?

**Comment by iksaku** [comment]
We will, but first we would like to update our configuration files to a new system in order to support future `Multi-language` system

**Comment by Sandertv** [comment]
I'll add this fairly soon, it's quite easy to do actually.

**Comment by Sandertv** [comment]
Added the option to do disable various parts, feel free to try it out and tell me if it works.
