### ISSUE TITLE
Update Wiki for Warp permission nodes

### ISSUE THREAD

**Issue by GlacierShard92** [LegendOfMCPE/EssentialsPE#261]
the title of this issue says it all. when i set this permission it doesnt work. example: /setwarp test. /setgperm Mod essentials.warp.test. Doesn't work. ive tried it for about a hour, several restarts and it doesnt work.

**Comment by iksaku** [comment]
Version of EssentialsPE?

**Comment by GlacierShard92** [comment]
v2.0.0 EssentialsPE

**Comment by iksaku** [comment]
Are you sure you created the warp "Test"?

**Comment by GlacierShard92** [comment]
yes. i created the warp.

**Comment by GlacierShard92** [comment]
now its working....lol

**Comment by GlacierShard92** [comment]
i found out why-
Your wiki says essentials.warp
its actually essentials.warps

**Comment by iksaku** [comment]
Our wiki still not finished :$ We sorry for the incovenience

**Comment by GlacierShard92** [comment]
its alright! ^-^

**Comment by Mike4l6** [comment]
Can't you just make it in the config to turn the permission on and off ? l'm getting this problem too

**Comment by iksaku** [comment]
@Mike4l6 What do you mean?

**Comment by Mike4l6** [comment]
Like /warp
Permission:
Every Player: True or False

**Comment by Sandertv** [comment]
Might just improve the Wiki if I feel like it.
