### ISSUE TITLE
The warp command has a bug, in pocket mine with plug pe you can't warp and can't add it with the spp command and it says it not a plugin command, please make this not require op

### ISSUE THREAD

**Issue by Tylerpad** [LegendOfMCPE/EssentialsPE#262]
The warp command is not available to the default group and when you add it in for the pocket mine default group it does not say it is a plugin command, please make it not require op.

**Comment by iksaku** [comment]
To use the command: `essentials.warp.use`
To _actually_ access a warp with the command: `essentials.warps.[warp name]`
