### ISSUE TITLE
Other players cant use /warp?

### ISSUE THREAD

**Issue by MhikeiMPC** [LegendOfMCPE/EssentialsPE#264]
Other players cant use /warp. I tried using pureperms to set other players to be able to use /warp, but they still cannot use it/

**Comment by iksaku** [comment]
You must give people access to the `/warp` command with the permission node `essentials.warp.use` and then allow them to access specific warps with `essentials.warps.[warp name]`, or all of them with `essentials.warps.*`

**Comment by Bidou0418** [comment]
@iksaku 
check out issue 265
I have same problem but i adjusted all the permissions, yet i still have the problem

**Comment by MhikeiMPC** [comment]
Yes i gave all the groups essentials.warp yet noone can use the warps.

**Comment by MhikeiMPC** [comment]
i finally got the warps to work, but i have to give the group permission for each warp separatly
