### ISSUE TITLE
only op player can use warp signs???

### ISSUE THREAD

**Issue by Bidou0418** [LegendOfMCPE/EssentialsPE#265]
I set the the permissions to the following but regular players still get the message: You cant teleport to that warp. 
Why can only op players use the warp signs if I properly set the permissions???
EssentialsPE v2.0.0 and SignWarp_v1.6.0

essentials.sign.use.teleport:
                                default: true
                                description: "Allow to use Teleport signs"
essentials.sign.use.warp:
                                default: true
                                description: "Allow to use Warp signs"
essentials.warp:
                default: true
                description: "Teleport to a warp"
                children:
essentials.warp.use:
                        default: true
                        description: "Teleport to a warp"
essentials.warp.other:
                        default: true
![warp](https://cloud.githubusercontent.com/assets/14065245/15374968/bc5b1838-1d01-11e6-8c26-4cbb2b4445c6.jpg)

**Comment by iksaku** [comment]
You must add permission node `essentials.warps.[warp name] in this case, warp name will be `Bidous`, so permission node will be: `essentials.warps.Bidous`

**Comment by Bidou0418** [comment]
is there a way to bypass adding extra permission nodes for every warp sign?
I just want everybody to have access to use warp signs...

**Comment by iksaku** [comment]
It's not about "each warp sign" is about "each existing warp", if you want all your users to be able access ALL warps available just use `essentials.warps.*`

**Comment by Bidou0418** [comment]
i see, but i thought i did;

       essentials.warp:
                default: true
                description: "Teleport to a warp"
                children:
                    essentials.warp.use:
                        default: true
                        description: "Teleport to a warp"
                    essentials.warp.other:

**Comment by Bidou0418** [comment]
I re-downloaded essentialspe and did a fresh install.
now everything works like i wanted.

**Comment by iksaku** [comment]
Nope, we link to original Essentials' permissions :P

**Comment by Mike4l6** [comment]
setgperm Guest essentials.warps.* NewSpawn
I did this command and it doesn't work :/
