### ISSUE TITLE
Disposal Sign Feature Request

### ISSUE THREAD

**Issue by Edwardthedog2** [LegendOfMCPE/EssentialsPE#267]
The Bukkit Essentials plugin has a feature where you can tap a sign that says [Disposal] at the top, and it opens up a menu like a chest. The only difference is that after you put items in this menu from your inventory, they disappear after you close the menu. I just thought this would be a useful feature for this plugin.

**Comment by iksaku** [comment]
The actual obstacle of this implementation is opening "virtual inventories", which is not yet possible in PocketMine, we do not know if it is a server-side or client-side lack of implementation
