### ISSUE TITLE
Warps don't save on my server

### ISSUE THREAD

**Issue by jasonwynn10** [LegendOfMCPE/EssentialsPE#269]
When I restart my server, the warps don't save to the file they are supposed to. I look in the file to see it empty between restarts and reloads. It happens on the plugin version 1.1.3

**Comment by Tolo0** [comment]
that can happen when using pc maps.

**Comment by iksaku** [comment]
We already fixed this issue in development versions, but update will not be available soon

**Comment by jasonwynn10** [comment]
what commit is the fix in? I can just modify the version i'm using to work

**Comment by iksaku** [comment]
That fix is kinda old, you can surf in the repo commits and look for it ;)
