### ISSUE TITLE
Warp Signs not working

### ISSUE THREAD

**Issue by snooblife** [LegendOfMCPE/EssentialsPE#276]
When clicking a warp sign it does not move the player and the console shows

INFO Notice: Undefined offset: 0 in phar:///plugins/EssentialsPE.phar/src/EssentialsPE/BaseFiles/BaseSession.php on line 515

**Comment by emiel2210** [comment]
It is for me..

**Comment by snooblife** [comment]
It was all working ok for me until I updated to the latest version then rolled back because tpa does not work, now on the latest version and the previous I get that error.. So I have had to give everyone perms to use the warp command which I dont really want to do. That iss the error which appears when I or someone else tries to use the signs, the signs can be created etc but not used

**Comment by emiel2210** [comment]
I will send you the working .Phar im using

**Comment by MajorPlayz** [comment]
Hi, I have the same problem i'm on php7 api 2.0.0 and I get the same error. Could you send me the file aswell please? @emiel2210 
Thanks,
MajorPlayz

**Comment by emiel2210** [comment]
There :)
http://www.mediafire.com/?kfeldmwywhxuu97

**Comment by MajorPlayz** [comment]
Thankyou I will drop this into /PocketMine/plugins folder right away

**Comment by MajorPlayz** [comment]
I have just tried it and thankfully the sign works however when I try /tpa it gives me an error
@emiel2210 
I will send a error message fron console.

**Comment by MajorPlayz** [comment]
Sorry my mistake tpa is working, thanks for the phar!

MajorPlayz

**Comment by snooblife** [comment]
Using the phar that you posted did not solve the warp problem, although I did not get a message in the console. The tpa also tp the player to you and not you to the player.

**Comment by MajorPlayz** [comment]
@snooblife are ypu sure bevause this worked for me...

**Comment by MajorPlayz** [comment]
@snooblife Do these steps:
Stop your server
Remove the current EssentialsPE
Download new phar
Drag it to the plugins folder
Rename it to EssentialsPE.phar
Start your server

It should now work @snooblife

**Comment by snooblife** [comment]
I have tested the phar on my main server and test servers, with my plugins loaded and tested again with only essentials loaded. Using genisys the warp sign does not work. Using pocketmine-mp and the phar posted with no other plugins it does not allow me to join the server as there is a login timeout. I managed to get it to work with Pocketmine-mp.phar but this is loading the server without any plugins and droping the plugin into the plugins folder an then using the reload command. Then it works, but that is a hassle.

**Comment by emiel2210** [comment]
Im not using warp signs or /tpa on my server but i can try to fix it

**Comment by MajorPlayz** [comment]
My warps and tpa are working however I get this error:
INFO Notice: Undefined offset: 0 in phar:///plugins/EssentialsPE.phar/src/EssentialsPE/BaseFiles/BaseSession.php on line 515
Just as @snooblife 
Does anybody have any ideas @emiel2210 @LDX-MCPE @leedm777 @onebone

**Comment by Sandertv** [comment]
Should be fixed now.

**Comment by HiggsInc** [comment]
#### Versions
* Server software: Clearsky ver 1.0.3
* EssentialsPE: EssentialsPE v2.0.0
* Game version: Pocket Edition
Server: CentOS 6.8

![essentialspe-warp signs not working](https://cloud.githubusercontent.com/assets/19491166/22980197/8098ba72-f3a1-11e6-8739-ffe3c44c4e17.PNG)

Hi,

Warp commands work but the signs dont. I've recently moved over to clearsky from genisys. As a result my warp signs dont work and console produces errors as seen in the attachment.

Please advise?

**Comment by Sandertv** [comment]
This is due to the next line on special signs after the required lines having to be a number, which is used as a price for using the sign. I'll fix the problem soon, by checking if the line is numeric.
