### ISSUE TITLE
Uncaught Error

### ISSUE THREAD

**Issue by GlitchPlayer** [LegendOfMCPE/EssentialsPE#281]
Fatal error: Uncaught Error: Call to a member function getName() on null in phar://C:/Users/glitc/Documents/DarkPvP Network/Genisys.phar/src/pocketmine/level/Level.php:3007
Stack trace:
#0 phar://C:/Users/glitc/Documents/DarkPvP Network/plugins/EssentialsPE_v2.0.0.phar/src/EssentialsPE/BaseFiles/BaseAPI.php(187): pocketmine\level\Level->getName()
#1 phar://C:/Users/glitc/Documents/DarkPvP Network/plugins/EssentialsPE_v2.0.0.phar/src/EssentialsPE/BaseFiles/BaseAPI.php(76): EssentialsPE\BaseFiles\BaseAPI->encodeWarps(true)
#2 [internal function]: EssentialsPE\BaseFiles\BaseAPI->__destruct()
#3 {main}

  thrown in phar://C:/Users/glitc/Documents/DarkPvP Network/Genisys.phar/src/pocketmine/level/Level.php on line 3007
zend_mm_heap corrupted

This shows me when I stopped the server...
No wonder how I did get it...

**Comment by Sandertv** [comment]
EssentialsPE does not always support forks from PocketMine, and might have compatibility issues.
