### ISSUE TITLE
RESET BUG

### ISSUE THREAD

**Issue by ItzRadius** [LegendOfMCPE/EssentialsPE#283]
Hey i have this bug where if you make a warp or a home and relog, it disappears. How to fix?

**Comment by Sandertv** [comment]
Can confirm this

**Comment by Sandertv** [comment]
Currently investigating.

**Comment by Sandertv** [comment]
Does anybody else experience this issue in the latest version? It doesn't happen to me.

**Comment by Sandertv** [comment]
It seems you've been using a very old version of EssentialsPE, this doesn't happen in the newer versions anymore.
