### ISSUE TITLE
warps only are allowed for op

### ISSUE THREAD

**Issue by YanSoo123** [LegendOfMCPE/EssentialsPE#287]
I have set permissions in plugin.yml to prove code below
`essentials.warp:
                default: true
                description: "Teleport to a warp"
                children:
                    essentials.warp.use:
                        default: true
                        description: "Teleport to a warp"
                    essentials.warp.other:
                        default: op
                        description: "Teleport other players to a warp"`
but player still find that when they are doing /warp Plots they do not have the permission
Also how do you create a warp sign

**Comment by YanSoo123** [comment]
Also adding the permission node essentials.warp.* or essentials.warp.Arena do not work when added to permission nodes with Pure Perms

**Comment by YanSoo123** [comment]
and they also do not work when added to permission nodes in the plugin.yml

**Comment by YanSoo123** [comment]
Anyone?

**Comment by GlacierShard92** [comment]
I've come across this before, this is how you fix it.
Your putting essentials.warp.warpname
the correct way is essentials.warps.warpname
Basically, you need to add a S

**Comment by Sandertv** [comment]
^
For example, essentials.warps.testwarp

**Comment by Sandertv** [comment]
The comment from GlacierShard is right.
