### ISSUE TITLE
Please add feature

### ISSUE THREAD

**Issue by MajorPlayz** [LegendOfMCPE/EssentialsPE#288]
Could you write a plugin that is just /spawn 
Because I don't want all the other parts of essentials just /spawn and /nick

Thanks :D

**Comment by Sandertv** [comment]
There's plenty plugins with that feature. Try using something like MSpawns for example.

**Comment by MajorPlayz** [comment]
But I don't want one of them I just want that and that only because it is
efficient...

On 30 Oct 2016 8:18 a.m., "Blabla" <notifications@github.com> wrote:

There's plenty plugins with that feature. Try using something like MSpawns
for example.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/LegendOfMCPE/EssentialsPE/issues/288#issuecomment-257138193>,
or mute the thread

**Comment by Sandertv** [comment]
Guess I could write a quick plugin for that...

**Comment by Sandertv** [comment]
Tell me if you really need a plugin for it and I'll see if I can find some time for you.
