### ISSUE TITLE
loop

### ISSUE THREAD

**Issue by seetch** [LegendOfMCPE/EssentialsPE#291]
mute and tempban in minutes or hours? help

**Comment by Sandertv** [comment]
* Rules:
         * Integers without suffix are considered as seconds
         * "s" is for seconds
         * "m" is for minutes
         * "h" is for hours
         * "d" is for days
         * "w" is for weeks
         * "mo" is for months
         * "y" is for years

**Comment by Sandertv** [comment]
you would have to put the letter right behind the number, without the space. For example: /mute seetch 10m would mute 10 minutes yep.
