### ISSUE TITLE
Server crashes if player is vanished and warps to world

### ISSUE THREAD

**Issue by tiNsLeY799** [LegendOfMCPE/EssentialsPE#293]
When this worked for 1.5 (had to abandon it on 1.6, it didn't work..) my staff would often teleport to players as a joke, but the entire server would crash. 
It gets better. They did this a lot, despite me telling them that it crashed the server, I would get an excuse of "oh, i forgot vanish crashes when i tp to < insert worldname here>".

If you want to recreate this:
Use /vanish
Teleport to a different world.
Record outcome

**Comment by Sandertv** [comment]
Could you tell me what the crashdump says? I'll try to help you.

**Comment by Sandertv** [comment]
If you can't get it I'll investigate myself.

**Comment by Sandertv** [comment]
This seems to have magically fixed itself. I can't manage to reproduce it.

**Comment by tiNsLeY799** [comment]
For some reason I wasn't getting notifications for this.
I'll dig around. I'm sure I have this dump file somewhere.
