### ISSUE TITLE
Float Issue

### ISSUE THREAD

**Issue by SuperDude36** [LegendOfMCPE/EssentialsPE#294]
When I enable it it says this: Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///Users/superserver/ServerTest/plugins/EssentialsPE_v1.1.3.phar/src/EssentialsPE/Loader.php on line 106

**Comment by Sandertv** [comment]
Are you using the master version? I don't see any code that could cause this error to occur.

**Comment by seetch** [comment]
@Sandertv for a long time all the tags in the genesis on Float -> FloatTag and ... Enum -> ListTag

**Comment by Sandertv** [comment]
Could you please tell me if this error still happens in the latest version? Thanks!

**Comment by flaxues** [comment]
He has an really old version.

**Comment by Sandertv** [comment]
Yeah that's what I was thinking. There isn't any code at line 106.
