### ISSUE TITLE
More /repair Bugs

### ISSUE THREAD

**Issue by SuperDude36** [LegendOfMCPE/EssentialsPE#297]
#### Description
It says the error below and it disables EssentialsPE.

#### Versions
* EssentialsPE: v2.0.0
* Game version: PE/W10

#### Crashdump or console errors
[07:53:17] [Server thread/CRITICAL]: ParseError: "syntax error, unexpected '{'" (EXCEPTION) in "/EssentialsPE-master/src/EssentialsPE/Commands/Repair" at line 33

**Comment by Sandertv** [comment]
Oh my god, that's really bad of me, sorry.

**Comment by Sandertv** [comment]
Sorry for that, it's fixed.

**Comment by SuperDude36** [comment]
I think it works. Im just trying to get on my server (aka crashing 24/7)
