### ISSUE TITLE
CRITICAL ERROR

### ISSUE THREAD

**Issue by WiliRodin** [LegendOfMCPE/EssentialsPE#298]
08.11 18:21:40 [Server] Server thread/INFO Disabling EssentialsPE v2.0.0
08.11 18:21:40 [Server] Server thread/CRITICAL Error: "Call to a member function getName() on array" (EXCEPTION) in "/EssentialsPE.phar/src/EssentialsPE/Loader" at line 243
08.11 18:21:40 [Server] Server thread/INFO [EssentialsPE] Loading...
08.11 18:21:40 [Server] Server thread/INFO Enabling EssentialsPE v2.0.0

**Comment by Sandertv** [comment]
Sorry for that, I'll fix it quickly.

**Comment by Sandertv** [comment]
Has been fixed, sorry for inconvenience.
