### ISSUE TITLE
TEST YOUR FUCKING CODE BEFORE COMMITTING

### ISSUE THREAD

**Issue by NoHaxJustTryHqrd** [LegendOfMCPE/EssentialsPE#299]

**Comment by NoHaxJustTryHqrd** [comment]
LIKE SERIOUSLY COME ON

**Comment by NoHaxJustTryHqrd** [comment]
An Issue That is currently happening shouldve never passed and be pushed to the repo

**Comment by NoHaxJustTryHqrd** [comment]
This is by far the dumbest mistake ever made.

**Comment by Sandertv** [comment]
What is it then? Sorry.

**Comment by Sandertv** [comment]
It has been fixed. Lower your temper next time and nobody's told you that the patest version on github is stable. This is what the release tab is for.
