### ISSUE TITLE
Other Error

### ISSUE THREAD

**Issue by WiliRodin** [LegendOfMCPE/EssentialsPE#300]
09.11 05:54:37 [Server] Server thread/CRITICAL ParseError: "syntax error, unexpected 'new' (T_NEW), expecting ']'" (EXCEPTION) in "/EssentialsPE.phar/src/EssentialsPE/Loader" at line 210
09.11 05:54:37 [Server] Server thread/CRITICAL Unhandled exception executing command 'reload' in reload: syntax error, unexpected 'new' (T_NEW), expecting ']'
09.11 05:54:37 [Server] Server thread/INFO An unknown error occurred while attempting to perform this command
09.11 05:54:37 [Server] Server thread/INFO Loading EssentialsPE v2.0.0

**Comment by Sandertv** [comment]
I already fixed this, try the newest version.
