### ISSUE TITLE
command near does not work

### ISSUE THREAD

**Issue by Andrew1481432** [LegendOfMCPE/EssentialsPE#308]
command near does not work

**Comment by Andrew1481432** [comment]
command near does not work

**Comment by Sandertv** [comment]
What does it say then? Any errors in console?

**Comment by Andrew1481432** [comment]
when near must be pishish inscription ** There are no players near to ". $ who. TextFormat :: GRAY."! ** And there usage: / near <player>

**Comment by Sandertv** [comment]
Well are there any players near you?

**Comment by Andrew1481432** [comment]
no

**Comment by Sandertv** [comment]
It won't do anything if there are no players nearby...

**Comment by Andrew1481432** [comment]
I understand :)
