### ISSUE TITLE
/msg + /m commands  not work

### ISSUE THREAD

**Issue by andris155** [LegendOfMCPE/EssentialsPE#309]
#### Description

/msg + /m not work

#### Versions
* Server software: https://github.com/iTXTech/Genisys/tree/55ae11e5acf93b753129343a3888cd4cf007da05
* EssentialsPE: https://github.com/LegendOfMCPE/EssentialsPE/tree/33623687658fcb8714cedb2bf95b62fb7fcbcdef
* Game version: W10

#### Crashdump or console errors

![kepkivagas](https://cloud.githubusercontent.com/assets/8324198/20459407/84c5ab62-aec0-11e6-802c-5d5efdc95f9e.PNG)

**Comment by andris155** [comment]
EssentialsPE 1.1.3 - works this commands

**Comment by Sandertv** [comment]
Try putting a dot in front of the command. A bunch of commands don't work correctly since 0.16, it's a server software thing. Try doing this:
./msg <player> <message>

**Comment by andris155** [comment]
EssentialsPE 1.1.3 + 0.16 Genisys - works /msg, /t, /m.
Why is it server szoftver thing?

**Comment by Sandertv** [comment]
Just relog with version 2.0.0 and those commands would work too. It is not within my power to fix this, as it is a MCPE => server software bug. Not just EssentialsPE has that problem in 0.16, a lot of plugins do.
