### ISSUE TITLE
error mute

### ISSUE THREAD

**Issue by Andrew1481432** [LegendOfMCPE/EssentialsPE#310]
[Server thread/CRITICAL]: Error: "Call to undefined method EssentialsPE\Loader::switchMute()" (EXCEPTION) in "/EssentialsPE_v1.phar/src/EssentialsPE/Commands/Mute" at line 46

**Comment by Sandertv** [comment]
Thanks for reporting, I'll fix that.

**Comment by Sandertv** [comment]
You're using a very outdated version, EssentialsPE isn't version 1 for a long time anymore. That could explain /near not working too. Please do not just delete the whole issue template. It's there for a reason.
