### ISSUE TITLE
Only ops can use warp command and warp signs

### ISSUE THREAD

**Issue by poustmal** [LegendOfMCPE/EssentialsPE#313]
#### Versions
* Server software:Genisys
* EssentialsPE:latest.I updated today.
* Game version: PE/W10
Non-op players can't use warp command or warp signs:it says [Error] You can't teleport to that warp.
I changed in plugin.yml some permissions.I set them to true e.g.warp,warp.use etc. but I'm having again the same problem.please fix it,I want this plugin.

#### Crashdump or console errors:nothing

**Comment by Sandertv** [comment]
This is intended. Just give the players essentials.warps.use.* to use all warps, or essentials.warps.use. <warpname> to just let them teleport to one warp.

**Comment by poustmal** [comment]
I have done this but it didnt work

**Comment by poustmal** [comment]
Maybe I should add warp permissions to my groups?Or no

**Comment by Sandertv** [comment]
Warp signs need the permission `essentials.sign.use.warp` too.

**Comment by poustmal** [comment]
I will try again.
