### ISSUE TITLE
Close the issue after answer my question

### ISSUE THREAD

**Issue by poustmal** [LegendOfMCPE/EssentialsPE#314]
Pls send me a correct plugin.yml with warp.use true permission I tried to set all the permissions I needed,but it gives me the same message:[Error] You can't use that warp.Don't tell me you must accept the rules,pls I want this plugin with correct perms.I want to fix my problems in my server and I can't.

**Comment by Sandertv** [comment]
The correct permissions are not located in the plugin.yml. These permissions are required:
`essentials.warp.use`
`essentials.warps.*` to give permission to use all warps, or `essentials.warps.<warpname>` for a specific warp.
