### ISSUE TITLE
Fix Bug

### ISSUE THREAD

**Issue by SuperDude36** [LegendOfMCPE/EssentialsPE#316]
#### Description
When I do /fix alone (not doing /fix hand or /fix all) it gives me this: "/Server/plugins/EssentialsPE-master/src/EssentialsPE/Commands/Repair.php on line 36" When I do "/fix hand" it says successfully fixed but it doesn't fix
#### Versions
* Server software: Elywing
* EssentialsPE: idk
* Game version: PE/W10

#### Crashdump or console errors
/Server/plugins/EssentialsPE-master/src/EssentialsPE/Commands/Repair.php on line 36

**Comment by Sandertv** [comment]
Putting down EssentialsPE version 'idk' is not valid. I fixed this in a commit quite some time ago, so try to use the latest version. If you use repair hand and it seems like it does nothing, just tap the ground with the item and it will be repaired. The item just needs an update.

**Comment by Sandertv** [comment]
If you're experiencing this on the latest build, please change the version to the commit and notify me.
