### ISSUE TITLE
Home's Reset 

### ISSUE THREAD

**Issue by Tolo0** [LegendOfMCPE/EssentialsPE#317]
I have no idea how this is happening but iv had alot of player's complain that after a server reboot there homes have been reset. 😕

**Comment by Sandertv** [comment]
Could you please fill in the issue format next time? It's not there to just delete. What server software do you use? Do you have any PC / ported worlds?

**Comment by Sandertv** [comment]
It's got to do with a missing permission it seems like. Do you have the latest version?

**Comment by Akuroma** [comment]
I've also had the same issue. But now it works for me. Don't know what happened but now it works without an update.

**Comment by Sandertv** [comment]
I must say I had the same issue some time ago, but I can't seem to reproduce this anymore. Is anybody else able to?

**Comment by Sandertv** [comment]
@Tolo0 Because you didn't provide the essentialsPE version I can't do anything. Could you tell me the version?

**Comment by Sandertv** [comment]
#325
