### ISSUE TITLE
Float Issue

### ISSUE THREAD

**Issue by SuperDude36** [LegendOfMCPE/EssentialsPE#319]
#### Description
When I turn the server on it has an error.
#### Versions
* Server software: 1.9.1
* EssentialsPE: 1.1.3
* Game version: PE/W10

#### Crashdump or console errors
Fatal error: Cannot use pocketmine\nbt\tag\Float as Float because 'Float' is a special class name in phar:///Users/superserver/ServerEssTest/plugins/EssentialsPE_v1.1.3.phar/src/EssentialsPE/Loader.php on line 106

**Comment by SOF3** [comment]
You're using an outdated version.

We have always been telling users not to use plugins of incompatible API version...

**Comment by SuperDude36** [comment]
It's the newest one on releases page.

**Comment by Sandertv** [comment]
You should click the link `Get the latest development build HERE` at the main page.

**Comment by SOF3** [comment]
@Sandertv development build and release are different...

**Comment by Sandertv** [comment]
Changed 👍
