### ISSUE TITLE
Multiworld Homes

### ISSUE THREAD

**Issue by AppleDevelops** [LegendOfMCPE/EssentialsPE#321]
#### Description

Homes are not multiworld, and I think it would be a good feature to teleport the players to their homes if they are in a different world. If it is possible could it be taken into consideration and added?
#### Versions
* Server software: Genisys + Tesseract
* EssentialsPE: https://github.com/LegendOfMCPE/EssentialsPE/commit/1142bf8976e57ee55f8b380c469e54a2723b5e85
* Game version: PE/W10

#### Crashdump or console errors

```
```

**Comment by Sandertv** [comment]
I think multiworld homes are there in fact, but it might not work if the level is loaded. I'll look into it.

**Comment by Sandertv** [comment]
Homes and warps are both multiworld, I'm not sure why they wouldn't be. Try loading the level using the pocketmine.yml or some other plugin that loads worlds.
