### ISSUE TITLE
Several items return air when tapping an economy sign

### ISSUE THREAD

**Issue by caspervanneck** [LegendOfMCPE/EssentialsPE#322]
#### Description

if you use some item id like 5 with
 economy sign
you get air

#### Versions
* Server software: pmmp
* EssentialsPE: v2.0.0
* Game version: PE/W10

#### Crashdump or console errors

```
```

**Comment by Sandertv** [comment]
What do you mean exactly?

**Comment by caspervanneck** [comment]
if i use the item id 5 i get air

**Comment by caspervanneck** [comment]
and some other ids

**Comment by Sandertv** [comment]
But when? Command? Sign?

**Comment by caspervanneck** [comment]
sign economy

**Comment by Sandertv** [comment]
Tried putting down just wooden planks?

**Comment by Sandertv** [comment]
Okay I tried reproducing and you're right. I'm not entirely sure how to fix this, but I'll have a try.

**Comment by caspervanneck** [comment]
👍 i wanth help but i have no time now @Sandertv

**Comment by Sandertv** [comment]
Could you try making a [free] sign with wooden planks and see if the same happens?

**Comment by caspervanneck** [comment]
i try it already but it keeps air

**Comment by Sandertv** [comment]
Okay. Let's see...

**Comment by Sandertv** [comment]
It seems that using Item::fromString($name) can not always be found with $item->getName(). I guess using Item::__toString() would be the best way to do this?

**Comment by SOF3** [comment]
__toString uses the value from getName, except it is not affected by custom name...
fromString is not the reverse of the magic method __toString. It uses class constants from Item and it's superclasses, so you should use ReflectionClass::getConstants. Note that getConstants seems (according to documentation) to return defined constants only, so you might have to merge superclass constants too.

**Comment by Sandertv** [comment]
Okay then. I'll wait with doing anything before the rewrite is going to happen anyways.

**Comment by SOF3** [comment]
You meant with**out**?
