### ISSUE TITLE
API 3.0 and MCPE 1.0: Players Unable To Connect

### ISSUE THREAD

**Issue by markkrueg** [LegendOfMCPE/EssentialsPE#323]
#### Description
Many plugins are working with the [new 1.0.0 compatible version of PocketMine-MP](https://github.com/pmmp/PocketMine-MP/tree/mcpe-1.0-dimensions). However, the API is going through some changes (3.0). For some reason players are unable to connect to a 1.0.0 server when EssentialsPE is installed after "3.0.0-ALPHA1" is added to API in plugin.yml. No error is given; and I am unable to determine the cause of the problem. 

#### Versions
* Server software: PocketMine-MP 1.6.2dev
* EssentialsPE: Build from current source as of 1142bf8
* Game version: iOS and Android tested

#### Crashdump or console errors
No errors reported. Player data seems to be initialized by PE, but the player is booted from the server without connecting. When EssentialsPE is removed the player can connect successfully.

I realize that this bug report is against a development version of PocketMine-MP, but since MCPE 1.0.0 is not released; it seems useful to start reporting against this.

**Comment by caspervanneck** [comment]
I don't have this I use 1.0.0 branch I can join fine

**Comment by Sandertv** [comment]
Did EssentialsPE work on older versions for you? Just asking this to make sure it did work before 1.0.

**Comment by Sandertv** [comment]
I'll be making a 1.0 version ranch soon.

**Comment by markkrueg** [comment]
> I don't have this I use 1.0.0 branch I can join fine

As soon as I saw this post I rebuilt the server from source and also re-built EssentialsPE from source. Now it is working! I apologize for the false issue. My source must have been corrupt.

**Comment by SOF3** [comment]
This issue cannot be confirmed resolved or invalid, because the API 3.0.0 is not finalized yet. No plugin should be assumed stable to work with API 3.0.0 before the API is finally released.
