### ISSUE TITLE
Home reset

### ISSUE THREAD

**Issue by iawsomecreeper** [LegendOfMCPE/EssentialsPE#325]
#### Description

Players report when they leave the servers homes gets reset. We imported a map from PC
#### Versions
* Server software: Elywing-1.0 php 7.0.10
* EssentialsPE: 2.0.0
* Game version: PE/W10

#### Crashdump or console errors

```no erros
```

**Comment by Sandertv** [comment]
I've heard this issue has existed for a very long time. Do you know if the world that players want to teleport to with homes is loaded or not?

**Comment by iawsomecreeper** [comment]
Homes Does not get saved

**Comment by Sandertv** [comment]
Okay I think this is in fact the permission issue then. Let me quickly search the permissions.

**Comment by iawsomecreeper** [comment]
No, this is not a permission issue but send me a permission so i can try it

**Comment by iawsomecreeper** [comment]
because OP's homes does not get saved either.

**Comment by Sandertv** [comment]
Could you set a home and look in the session file of your name, then send me a picture from it?

**Comment by iawsomecreeper** [comment]
Um, how can i send pictures i got Twitter @exepx dm me and ill send u pic

**Comment by Sandertv** [comment]
You can upload files by clicking on `selecting them,` at the bottom when posting a comment.

**Comment by iawsomecreeper** [comment]
![bug](https://cloud.githubusercontent.com/assets/10277156/21472912/1a0402e2-caa4-11e6-998c-27e37d4fefdd.png)

**Comment by Sandertv** [comment]
Okay, so it just doesn't save it AT ALL... Hm...

**Comment by iawsomecreeper** [comment]
Yes it does not Saved at all

**Comment by Sandertv** [comment]
I think this might have to do with the level folder name not being the same as the level.dat name, causing issues and making the home not valid, thus deleting it. Could you check if the folder name is the same as the name of the original imported world?

**Comment by iawsomecreeper** [comment]
can you explain it more on what i have to do?

**Comment by Sandertv** [comment]
Okay so basically, in the PocketMine API, there's a $level->getName() function, which returns the level.dat name, and $level->getFolderName(), which returns the folder name from the world. Can you remember if you have a different name for the folder than the original name from the world, which it was called when you originally imported it from PC? You could try fixing the level.dat name with a plugin like ManyWorlds (if I'm correct...) so that might work.

**Comment by iawsomecreeper** [comment]
well, the world name is world i changed it

**Comment by Sandertv** [comment]
Yeah okay, you should try what I said then. Try installing a plugin like ManyWorlds and use a command to fix the level.dat name.

**Comment by iawsomecreeper** [comment]
okay, ill try that thank you sorry for late respond.

**Comment by iawsomecreeper** [comment]
yes, it is now fixed thank you

**Comment by Sandertv** [comment]
Alright! Great!
