### ISSUE TITLE
Mute permission

### ISSUE THREAD

**Issue by NycuRO** [LegendOfMCPE/EssentialsPE#327]
#### Description

Permission not work ..

- essentials.mute
#### Versions
* Server software: Genisys
* EssentialsPE: https://github.com/LegendOfMCPE/EssentialsPE/commit/746d7e16c24ff0e698ca5031f50799f99f4f19ce
* Game version: PE/W10 : all

#### Crashdump or console errors

```
```

**Comment by Sandertv** [comment]
What part of it doesn't work?

**Comment by NycuRO** [comment]
If i'm used in pureperms , permission: essentials.mute, command not work..

Permission not work for command
