### ISSUE TITLE
Loose types widely used in EssentialsPE

### ISSUE THREAD

**Issue by andris155** [LegendOfMCPE/EssentialsPE#332]
> Note from SOFe: This issue was initially reported for specific problems in elywing, but it turns out that this issue is valid and covers major problems in EssentialsPE. Blame @iksaku for not checking types properly. 

Below is a list of issues associated with loose types. They may cause server crashes in PMMP API 3.0.0

- [x] TypeError: "Argument 1 passed to pocketmine\item\Item::setDamage() must be of the type integer, string given, called in phar:///plugins/EssentialsPE.phar/src/EssentialsPE/BaseFiles/BaseAPI.php on line 936" (EXCEPTION) in "/src/pocketmine/item/Item" at line 851
- [x] TypeError: "Argument 2 passed to EssentialsPE\BaseFiles\BaseAPI::addToPlayerBalance() must be of the type integer, string given, called in phar:///home/pi/tespe/Tesseract/plugins/EssentialsPE-PHP7-3.0.phar/src/EssentialsPE/EventHandlers/SignEvents.php on line 318" (EXCEPTION) in "/plugins/EssentialsPE-PHP7-3.0.phar/src/EssentialsPE/BaseFiles/BaseAPI" at line 476

**Comment by Sandertv** [comment]
Have you made sure the sign is written correctly? (Documentation is in wiki)

**Comment by andris155** [comment]
The signs already placed and works perfectly in Genisys 0.16.2.
I updated server to Elywing 1.0.0 and sign stopped working write linked error.

**Comment by Sandertv** [comment]
I'll look into it.

**Comment by Sandertv** [comment]
Could you upload a screenshot here of one of your non-working signs?

**Comment by andris155** [comment]
![screenshot_20170105-130045](https://cloud.githubusercontent.com/assets/8324198/21679978/2be81150-d347-11e6-8d05-a25f2e9cc00c.png)

**Comment by SOF3** [comment]
Elywing...

**Comment by andris155** [comment]
https://github.com/H4PM/Elywing/pull/303

**Comment by SOF3** [comment]
@Sandertv I believe that if you have read the error message, you don't need to ask for any screenshots etc. at all.

**Comment by Tolo0** [comment]
None of the signs are working

**Comment by Tolo0** [comment]
![screenshot_20170107-192101](https://cloud.githubusercontent.com/assets/13458191/21744528/42439acc-d50f-11e6-8006-f0652fd481db.png)

**Comment by Sandertv** [comment]
EssentialsPE version?

**Comment by Tolo0** [comment]
Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Argument 2 passed to EssentialsPE\BaseFiles\BaseAPI::hasPlayerBalance() must be of the type integer, string given, called in phar:///home/tolo/mc2/plugins/EssentialsPE-fix.phar/src/EssentialsPE/EventHandlers/SignEvents.php on line 235 on EssentialsPE\EventHandlers\SignEvents
20:33:32 | Elywing thread:CRITICAL > TypeError: "Argument 2 passed to EssentialsPE\BaseFiles\BaseAPI::hasPlayerBalance() must be of the type integer, string given, called in phar:///home/tolo/mc2/plugins/EssentialsPE-fix.phar/src/EssentialsPE/EventHandlers/SignEvents.php on line 235" (EXCEPTION) in "/plugins/EssentialsPE-fix.phar/src/EssentialsPE/BaseFiles/BaseAPI" at line 564

**Comment by Tolo0** [comment]
this is the latest version. I downloaded it 10 min ago

**Comment by Sandertv** [comment]
Did creating the signs even EVER work with Elywing?

**Comment by andris155** [comment]
My created signs works perfectly. Thanks!

**Comment by andris155** [comment]
Create new signs - not work.

**Comment by Tolo0** [comment]
they worked fine with a older version of Elywing

**Comment by Falkirks** [comment]
Elywing has just decided to strictly enforce types on common API calls, which is kind of a cruddy move.

**Comment by SOF3** [comment]
This is going to happen in API 3.0.0 as well, so this issue is valid. 
Reopening this issue to fix all loose types.

**Comment by Tolo0** [comment]
I had to switch back to a old version of Elywing.  can't run a server with out working warp signs. the plugin really is essential 😅

**Comment by Sandertv** [comment]
@Tolo0 the signs not updating is completely an Elywing issue, which we can not fix. It is up to them to fix that, and looking at their issue tracker I can see it's already reported.

**Comment by SOF3** [comment]
Or simply don't use Elywing.

**Comment by Sandertv** [comment]
Preferable that ^

**Comment by Tolo0** [comment]
I have to use Elywing theys no alternative for what I need 😔 Elywing is full of bugs. I'm just going to stay with the build that works with EssentialsPE.

**Comment by andris155** [comment]
@Tolo0 Same problem. :'(

**Comment by SOF3** [comment]
Note that Elywing is not supported by EssentialsPE. Several of us have decided to use "Ignore the existence of Elywing and close any Elywing issues" as our policy towards Elywing. This issue exists here not for Elywing, but for some problems that EssentialsPE internally has.

**Comment by Sandertv** [comment]
EssentialsPE 3.0.0 will have strict types enforced, and so does PocketMine now. I'm closing this issue as most of these issues have been fixed, or will be fixed in 3.0.0.
