### ISSUE TITLE
Invalid entity coordinate

### ISSUE THREAD

**Issue by Adam1609** [LegendOfMCPE/EssentialsPE#337]
#### Description

Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Invalid entity coordinates on EssentialsPE\EventHandlers\SignEvents
It never happened before @@

#### Versions
* Server software: Elywing
* EssentialsPE: 2.0.0
* Game version: PE/W10: 1.0.0

##Step to reproduce in PocketMine
Step 1: Put PureEntitiesX into the server
Step 2: Find any mob (if possible)
Step 3: The bug will show off when touching every mob!
#### Crashdump or console errors

Elywing thread:CRITICAL > "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Invalid entity coordinates on EssentialsPE\EventHandlers\SignEvents

```
```

**Comment by SOF3** [comment]
Please provide steps to reproduce in PocketMine. Elywing is not explicitly supported.

**Comment by Adam1609** [comment]
Putting every mob plugin or a mob spawner and watch!

**Comment by Adam1609** [comment]
This error kept my server stopping all the time!!!!!

**Comment by SOF3** [comment]
Closing for insufficient information. Will be reopened if sufficient information to reproduce the issue as well as detailed information are provided.

**Comment by dktapps** [comment]
@SOF3 you didn't actually, um, _close_ it...

**Comment by SOF3** [comment]
@dktapps thanks for reminding me :stuck_out_tongue_winking_eye:
