### ISSUE TITLE
Warping results in not being able to log back in

### ISSUE THREAD

**Issue by Dblcut3** [LegendOfMCPE/EssentialsPE#338]
#### Description
 When a user warps, then logs out, they cannot log back in. It just gives an wndless "building terrain" message. 

#### Versions
* Server software: PMMP
* EssentialsPE: API 3.0
* Game version: PE

#### Crashdump or console errors

```
```

**Comment by Akuroma** [comment]
Are you sure that this is a Essentials Reason?

**Comment by Dblcut3** [comment]
Well, it is a warp issue and warps are a part of essentials so I am just assuming it has to be from Essentials.

**Comment by Sandertv** [comment]
I can not seem reproduce this. It might be an issue with all the chunk things in Pocketmine not being entirely stable yet.

**Comment by Dblcut3** [comment]
I did more research. That is probably it. You can close this if you are confident that it doesnt involve the plugin.

**Comment by Sandertv** [comment]
I'll leave this open for the time being, just in case it does not get fixed by PocketMine.

**Comment by Sandertv** [comment]
I tried to reproduce this in any way possible using the latest PocketMine build, and I can't seem to be able to. If this issue isn't fixed with the latest build, please tell us.
