### ISSUE TITLE
Can't sell to [Sell] sign?

### ISSUE THREAD

**Issue by nopenothing** [LegendOfMCPE/EssentialsPE#339]
Running tesseract server software, fork of pocketmine

#### Description

I get the error below in console when i try to sell item to admin shop. Does not happen if i do not have the item for that specific sign

#### Versions
* Server software:
* EssentialsPE: lastest commit
* Game version: PE 1.0.2

#### Crashdump or console errors

CRITICAL> TypeError: "Argument 2 passed to EssentialsPE\BaseFiles\BaseAPI::addToPlayerBalance() must be of the type integer, string given, called in phar:///home/pi/tespe/Tesseract/plugins/EssentialsPE-PHP7-3.0.phar/src/EssentialsPE/EventHandlers/SignEvents.php on line 318" (EXCEPTION) in "/plugins/EssentialsPE-PHP7-3.0.phar/src/EssentialsPE/BaseFiles/BaseAPI" at line 476

**Comment by Sandertv** [comment]
Relates to #332

**Comment by Sandertv** [comment]
Try the commit I referenced above, it should fix this issue.
