### ISSUE TITLE
Warps

### ISSUE THREAD

**Issue by TheClimbing** [LegendOfMCPE/EssentialsPE#341]
#### Description

Whenever I try to warp to any of the created warps the following error occurs 
`[Error] You can't teleport to that warp`
I know you'll say we don't support Genisys but maybe that's a problem at PocketMine too?

#### Versions
* Server software:Genisys 1.0.0.16
* EssentialsPE:v2.0.0
* Game version: PE

#### Crashdump or console errors

```
```
None

**Comment by Sandertv** [comment]
This is due to the level not being loaded. Try adding the level in the pocketmine.yml to auto-load on startup to fix this.

**Comment by TheClimbing** [comment]
Thanks for the quick response but that didn't solve my issue.Every world I have is loaded and still when I try to warp to some of the warps the same Error ossurs

**Comment by Sandertv** [comment]
Alright, I'll try to investigate this issue.

**Comment by TheClimbing** [comment]
Just to mention if it helps.When i warp myself trough Console it works flawlessly

**Comment by Sandertv** [comment]
Okay, thanks.

**Comment by TheClimbing** [comment]
@Sandertv So Simple Warp overrides Essentials and that solved the issue if you can use both and compare them

**Comment by Sandertv** [comment]
Are you sure you even have the required permissions for warping? Do you have pureperms installed by any chance? It could explain why warping from the console does work.

**Comment by TheClimbing** [comment]
Yes I'm quite sure that I have the permissions,  I searched a lot for warping issues and their solutions before opening new issue. So PurePerms is installed and the respective permission for warping is "essentials.command.warp.use" I tried if adding "essentials.command.warp*"  will fix it but sadly no.

**Comment by Sandertv** [comment]
Try giving yourself the permission `essentials.warp.use` and `essentials.warps.*`.

**Comment by TheClimbing** [comment]
I gave myself those permissions and it didn't helped.I went up and tried to OP myself ignoring PurePerms
and that worked.

**Comment by Sandertv** [comment]
Guess so!

**Comment by HimbeersaftLP** [comment]
Can you show all the warp permissions you gave to yourself again?

**Comment by Sandertv** [comment]
Try giving yourself the permission `essentials.warps.<warpname>`.

**Comment by TheClimbing** [comment]
Wow thanks that fixed my issue.I've  never expected perms being created for each warp.

**Comment by Sandertv** [comment]
I'm not sure why the * wouldn't work though... I'll have to check that.

**Comment by TheClimbing** [comment]
Should I close now?

**Comment by Sandertv** [comment]
I'll leave it open for a bit.

**Comment by TheClimbing** [comment]
I can't use /world even when I have the perms for it  `essentials.world.ExampleWorldName` and `essentials.world`

**Comment by TheClimbing** [comment]
Says again that I can't teleport to that warp

**Comment by Sandertv** [comment]
give yourself the permission essentials.worlds.<world> or essentials.worlds.*

**Comment by NycuRO** [comment]
Wtf, close that issue ,is permission problem.

**Comment by Sandertv** [comment]
No issues anymore? I'll close this issue then.
