### ISSUE TITLE
[Free] sign issue

### ISSUE THREAD

**Issue by mote166** [LegendOfMCPE/EssentialsPE#342]
#### Description

i was using an old server version which uses api 2.0.0 and created [Free] signs and they worked just fine but now when i updated the server to elywing ( uses api 2.0.0 and 3.0.0-ALPHA1 ) i can't place [Free] signs and when i tap the ones that ive created before updating nothing shows up and i get this console error
#### Versions
* Server software: linux (Elywing)
* EssentialsPE: v2.0.0
* Game version: PE

#### Crashdump or console errors

```Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Argument 1 passed to pocketmine\item\Item::setDamage() must be of the type integer, string given, called in /plugins/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseAPI.php on line 904 on EssentialsPE\EventHandlers\SignEvents 12.02 03:58:15 [Server] CRITICAL TypeError: "Argument 1 passed to pocketmine\item\Item::setDamage() must be of the type integer, string given, called in /plugins/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseAPI.php on line 904" (EXCEPTION) in "/src/pocketmine/item/Item" at line 834 12.02 03:58:15 [Server] CRITICAL "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Argument 1 passed to pocketmine\item\Item::setDamage() must be of the type integer, string given, called in /plugins/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseAPI.php on line 904 on EssentialsPE\EventHandlers\SignEvents
```
Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Argument 1 passed to pocketmine\item\Item::setDamage() must be of the type integer, string given, called in /plugins/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseAPI.php on line 904 on EssentialsPE\EventHandlers\SignEvents 12.02 03:58:15 [Server] CRITICAL TypeError: "Argument 1 passed to pocketmine\item\Item::setDamage() must be of the type integer, string given, called in /plugins/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseAPI.php on line 904" (EXCEPTION) in "/src/pocketmine/item/Item" at line 834 12.02 03:58:15 [Server] CRITICAL "Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Argument 1 passed to pocketmine\item\Item::setDamage() must be of the type integer, string given, called in /plugins/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseAPI.php on line 904 on EssentialsPE\EventHandlers\SignEvents

**Comment by TheClimbing** [comment]
Relates #339

**Comment by Sandertv** [comment]
For this specific issue, just get the latest version. It should fix it. There are more of these issues with other signs though.
