### ISSUE TITLE
Homes do not save!

### ISSUE THREAD

**Issue by austina1212** [LegendOfMCPE/EssentialsPE#348]
#### Description

When a player sets a home with /sethome (name) and re-log, it disappears...

#### Versions
* Server software: Tesseract-1.1.0 Ruby
* EssentialsPE: Lastest
* Game version: PE/W10 Both

#### Crashdump or console errors

*None*
```
```

**Comment by Sandertv** [comment]
Sorry, but we don't support Tesseract.

**Comment by caspervanneck** [comment]
@Sandertv its on pmmp to so open?

**Comment by Sandertv** [comment]
Do you have imported any maps? See #325

**Comment by caspervanneck** [comment]
@Sandertv  no  i tested on new map with pmmp
