### ISSUE TITLE
Permissions issues

### ISSUE THREAD

**Issue by flaxues** [LegendOfMCPE/EssentialsPE#349]
#### Description
Many commands lack proper permissions for example `/back` or `/heal`. They all check if the player has perrmision essentials.*.use but not essentials.back.ondeath or essentials.heal.other. And these 2 commands are not the only one.

But the command `/mute` does check for these kind of perms

#### Versions
* Server software: PMMP
* EssentialsPE: 8ba714b
* Game version: PE/W10

#### Crashdump or console errors

```
```

**Comment by Sandertv** [comment]
I'll work on some permission stuff soon, to add the proper permissions for those.

**Comment by Sandertv** [comment]
essentials.back.ondeath has never really been implemented. There's no current way to check if the last teleport location was the death location at the moment.
