### ISSUE TITLE
Request update to API 3.0.0-ALPHA5

### ISSUE THREAD

**Issue by dino147** [LegendOfMCPE/EssentialsPE#352]
Please update your plugin to API 3.0.0-ALPHA5 (pocketmine for mcpe 1.0.5) and give me a phar link or a zip to phar convertor.

**Comment by SOF3** [comment]
> give me a phar link or a zip to phar convertor.

There is Poggit-CI.

3.0.0-ALPHA5 will see very breaking changes soon. Shouldn't update to it right now.
