### ISSUE TITLE
Improper Config loading

### ISSUE THREAD

**Issue by jasonwynn10** [LegendOfMCPE/EssentialsPE#354]
#### Description

The config file becomes blank after the initial creation
#### Versions
* Server software: PMMP master branch poggit build 542
* EssentialsPE: e89d942
* Game version: N/A
* Operating System: Windows 10

#### Crashdump or console errors

![img_0788](https://cloud.githubusercontent.com/assets/16521025/26510155/f2e936ac-4229-11e7-930a-8e4c9a5869a3.PNG)

There is an outputted error that the yaml_parse() failed

**Comment by SOF3** [comment]
Sounds this becomes more frequently heard recently... Probably something to do with PMMP?

**Comment by Sandertv** [comment]
Perhaps it is. @jasonwynn10 bump, could you upload the error?

**Comment by Sandertv** [comment]
@SOF3 I had the same issue with another plugin when calling $this->saveDefaultConfig() in a PluginBase class. The config file got created, but without any text, even though the resources folder contained a filled config.yml

**Comment by SOF3** [comment]
Is this completely random?

**Comment by Sandertv** [comment]
I suspect this happens only when running on Windows systems. I've never seen it on a different operating systen than Windows.

**Comment by SOF3** [comment]
This would either be a failure in stream_copy_to_stream() or in fclose() :thinking:

**Comment by Sandertv** [comment]
Turns out this isn't just windows. yaml_parse: end of stream reached without finding document 0 in Config.php line 142. This happens with only saveResource() too. See code used for creating the config file in my KillCounter plugin.

**Comment by SOF3** [comment]
@Sandertv do you reproduce this **every time** or just occasionally?

**Comment by Sandertv** [comment]
Every time. Perhaps this is just because of incorrectly formatted yaml files?

**Comment by SOF3** [comment]
I don't think so. It doesn't parse the YAML at all.
@Sandertv could you var_dump() the return values of stream_copy_to_stream() and fclose() (both of them) in the PluginBase.php saveResource() function by modifying the source code?

**Comment by Sandertv** [comment]
Sure thing, I'll try it out shortly.

**Comment by Sandertv** [comment]
Actually, through further testing, I figured out this is simply because $this->getConfig() is called before $this->saveDefaultConfig() or $this->saveResource(), and creates an empty configuration file because of that. If no additional parameter is passed to saveResource() the config file will not be overwritten and will remain empty. Perhaps it's more appopriate to throw an exception if no configuration file could be found?

**Comment by Sandertv** [comment]
That does not explain this issue though. I haven't been able to reproduce it with EssentialsPE either.

**Comment by SOF3** [comment]
@dktapps ^

**Comment by kenygamer** [comment]
The error is clear, there is a problem parsing the **YAML**
Update: Warning
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Sandertv** [comment]
@kenygamer we're not blind. We can **see** there is an error, we're wondering about what **causes** it.

**Comment by SOF3** [comment]
@kenygamer it is not. The config is copied before it is parsed, and it is copied wrongly.

**Comment by dktapps** [comment]
The referenced commit should resolve this issue.

**Comment by Sandertv** [comment]
👍
