### ISSUE TITLE
Item count /item

### ISSUE THREAD

**Issue by HipsterAF** [LegendOfMCPE/EssentialsPE#355]
#### Description

See the pic, what muqsit said on playervault's issue
![screenshot_20170502-123854 01](https://cloud.githubusercontent.com/assets/25702950/25607526/838bb9ae-2f34-11e7-9851-b395c9e92c8b.png)

#### Versions
* Server software: PMMP 1.0.7 
* EssentialsPE: 2.0.0
* Game version: PE/W10 any

#### Crashdump or console errors

```
None
```

**Comment by Sandertv** [comment]
This issue doesn't have a particularly high priority, but I can confirm it. For now, I'm going to leave it, as I'm working on a rewrite.

**Comment by Assblocker** [comment]
Okay

**Comment by Sandertv** [comment]
This is actually an intended feature. The oversized stacks feature.
