### ISSUE TITLE
Block/Item Direction Bug

### ISSUE THREAD

**Issue by infinity-pe** [LegendOfMCPE/EssentialsPE#356]
#### Description
Signs, Ladders or ItemFrames, they cannot be placed on walls – they jump off.
Things like Signs or Stairs they are not showing into the direction of the player when placing.
Also, doors are glitching a lot.
I know it must be a problem with this plugin. I tried removing this plugin from my server, and everything was working again.
#### Versions
* Server software: PocketMine-MP 1.6.2 'Unleashed'
* EssentialsPE: v2.0.0
* Game version: MineCraft 1.0.7

#### Crashdump or console errors

No errors or crashdumps.

**Comment by Sandertv** [comment]
I've tested the latest version and can't seem to be able to reproduce the issue. Is there anybody else who experiences this issue?

**Comment by infinity-pe** [comment]
I hope this can be fixed or lots of blocks and items won't anymore on my server.

**Comment by infinity-pe** [comment]
Hi, I found out this: if I'm an OP (if my name is on ops.txt), this bug happens. If I'm not an OP, this bug is gone.
It must be EssentialsPE, because I tried removing it, and this bug completely disappeared. But if I turn on EssentialsPE on again, the bug is back for OPs again.
I also tried installing an older version of this, turned off the auto updater and test it again. No difference, the bug is still there. I can remember that everything was still working perfectly before April 2 (the day when the small update came). But then after that day, when the update came, this bug appeared.
But the strange thing is, that why does the older version not fix the problem? When the bug came after the update (and before that update everything was still working), why does the old version not undo that update and give me back the working version?

**Comment by Sandertv** [comment]
Do you (or don't you) have PurePerms installed on the server?

**Comment by infinity-pe** [comment]
Yes, I have. I set `- '*'` for these groups: Owner, CoOwner and Admin.

**Comment by Sandertv** [comment]
I just set up a server to test this issue, but I am unable to reproduce it. On a PMMP server using the latest PM-3.0.0 branch commit this issue does not occur. I've tested it both WITH PurePerms and without, but this does not seem to make a difference. I am quite confident this is not an EssentialsPE issue...

**Comment by infinity-pe** [comment]
I tested something again. I made my test account an OP and tried placing a sign. It works, no more bug. But  only my original account has this bug. I looked if it can be the problem of EssentialsPE or PurePerms, but I cannot find anything.
I don't know why this happens, I can also hardly believe it's the update, because the older version doesn't fix it. And I'm not sure if it's PurePerms, because if I remove the EssentialsPE plugin, the bgug is gone. If I turn EssentialsPE back on again, the bug's back.
If this is only for my original owner account, there MUST be something set to the name of my account.

**Comment by Sandertv** [comment]
I suspect the cause of this is the /unlimited command. Could you try executing it and see if it enables/disables it, then try to place a sign for example?

**Comment by infinity-pe** [comment]
Oh, yes, it fixed the problem. Can you look at that command again and fix the bug with the signs?

**Comment by Sandertv** [comment]
The latest commit should have fixed this issue. Please try it again.

**Comment by infinity-pe** [comment]
Shall I use _master_ branch now or _PM-3.0.0_? Because `/vanish` won't work with the _master_ branch.

**Comment by jasonwynn10** [comment]
the master branch is for PM before API 3

**Comment by Sandertv** [comment]
Excuse ne, let me merge it.

**Comment by infinity-pe** [comment]
I got this error in console:
http://i.cubeupload.com/zubbz9.png

Plus, don't want to open a new issue again for this: the `/fix` command isn't working. It doesn't repair the item.

**Comment by Sandertv** [comment]
/fix does work. Just tap the item on the ground. I'll fix it properly once I'm home, give me some time.
