### ISSUE TITLE
/vanish Command Error

### ISSUE THREAD

**Issue by infinity-pe** [LegendOfMCPE/EssentialsPE#357]
#### Description
When running the `/vanish` command, the console gets an error:
`[Server thread/CRITICAL]: Unhandled exception executing command 'vanish' in vanish: Class pocketmine\network\protocol\MobEffectPacket not found
[Server thread/CRITICAL] ClassNotFoundException: "Class pocketmine\network\protocol\MobEffectPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144`

#### Versions
* Server software: VPS Control, Debian 8.0 + MCPE Server
* EssentialsPE: v2.0.0
* Game version: PE v1.0.7.0

#### Crashdump or console errors

`[Server` thread/CRITICAL]: Unhandled exception executing command 'vanish' in vanish: Class pocketmine\network\protocol\MobEffectPacket not found`
`[Server thread/CRITICAL] ClassNotFoundException: "Class pocketmine\network\protocol\MobEffectPacket not found" (EXCEPTION) in "/src/spl/BaseClassLoader" at line 144`

**Comment by Sandertv** [comment]
Simply bumping the API is not going to work. Please download EssentialsPE from the PM-3.0.0 branch.
