### ISSUE TITLE
kits

### ISSUE THREAD

**Issue by DerddyDert** [LegendOfMCPE/EssentialsPE#359]
any way to disable kits would be lovely.

#### Versions
* Server software:
* EssentialsPE:
* Game version: PE/W10

#### Crashdump or console errors

```
```

**Comment by Sandertv** [comment]
Hi @DerddyDert, at the moment I'm not going to work on the main branch too much. I'm currently working very hard on a rewrite of the complete plugin, where you can enable/disable every command and the seperate modules like economy. This is a planned feature for that rewrite. For now, you could disable the command in the pocketmine.yml by adding an alias called kit with no commands to execute.
