### ISSUE TITLE
Error in /vanish command

### ISSUE THREAD

**Issue by infinity-pe** [LegendOfMCPE/EssentialsPE#377]
#### Description
I'm getting this error in console when doing the /vanish command. I disappear, but I cannot make me appear again.
Screenshot of Error: http://i.cubeupload.com/Y5UTTf.png

#### Versions
* Server software: Debian 8.0
* EssentialsPE: v2.0.0
* Game version: PE

#### Crashdump or console errors
`[Server thread/CRITICAL]: Unhandled exception executing command 'v' in vanish: Argument 1 passed to pocketmine\utils\Binary::writeUnsignedVarLong_64() must be of the type integer, null given, called in phar:///home/mcpe/PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 689`
`[Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\utils\Binary::writeUnsignedVarLong_64() must be of the type integer, null given, called in phar:///home/mcpe/PocketMine-MP.phar/src/pocketmine/utils/Binary.php on line 689" (EXCEPTION) in "/src/pocketmine/utils/Binary" at line 728`

**Comment by Sandertv** [comment]
Got it, give me a minute.
