### ISSUE TITLE
/fix not working

### ISSUE THREAD

**Issue by infinity-pe** [LegendOfMCPE/EssentialsPE#378]
#### Description
The `/fix` command isn't working. I'm getting a console error.

#### Versions
* Server software: Debian 8.0
* EssentialsPE: v2.0.0
* Game version: PE

#### Crashdump or console errors

`[Server thread/CRITICAL]: Unhandled exception executing command 'fix' in repair: Undefined variable: a`
`[Server thread/CRITICAL]: ErrorException: "Undefined variable: a" (EXCEPTION) in "/EssentialsPEPlugin/src/EssentialsPE/Commands/Repair" at line 36`

**Comment by kenygamer** [comment]
@infinity-pe **$a** will not be defined unless argument *0* is set (*hand* or *all*, respectively).
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by infinity-pe** [comment]
It's not fixing the item.

**Comment by kenygamer** [comment]
@infinity-pe I said, **$a** needs to be defined.
Until it isn't, fixing won't work
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by kenygamer** [comment]
@infinity-pe Try using `/fix <hand|all>`. Does that yet return errors in console?
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by kenygamer** [comment]
@infinity-pe #382 cf548e3c063bc8a0f26edb219d6b1aed20293856 May give the solution.
