### ISSUE TITLE
Console Bug

### ISSUE THREAD

**Issue by StormCraftMCPE** [LegendOfMCPE/EssentialsPE#379]
#### Versions
* Server software: Pocketmine-MP
* EssentialsPE: New
* Game version: PE/W10

#### Crashdump or console errors

[Server thread/CRITICAL]: Could not pass event 'pocketmine\event\player\PlayerInteractEvent' to 'EssentialsPE v2.0.0': Trying to get permissions of closed player on EssentialsPE\EventHandlers\OtherEvents

**Comment by SOF3** [comment]
`EssentialsPE: New`?

**Comment by StormCraftMCPE** [comment]
Version 2.0.0 xD

**Comment by Sandertv** [comment]
PlayerInteractEvent with closed player? How's that supposed to work?

**Comment by SOF3** [comment]
Please set `debug`.`level` in pocketmine.yml to 2 and test again.

**Comment by Sandertv** [comment]
Due to a lack of information we can not resolve your issue. If you think you've provided enough information, please ask to re-open.
