### ISSUE TITLE
strtolower() home's and remove characters that doesn't follow regex

### ISSUE THREAD

**Issue by kenygamer** [LegendOfMCPE/EssentialsPE#380]
#### Description

Use regexs when setting homes in order to allow a-z0-9.
#### Versions

* PocketMine Version: Ubuntu 16.04
* EssentialsPE Version: v2.0.0
* Game Version: PE

#### Crashdump or console errors

```
```

**Comment by Sandertv** [comment]
https://github.com/LegendOfMCPE/EssentialsPE/blob/master/src/EssentialsPE/BaseFiles/BaseSession.php#L339

**Comment by kenygamer** [comment]
@Sandertv Oh ok, I appreciate you taking a minute to give me the line number for reference (where validation is made).
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ
