### ISSUE TITLE
/v error

### ISSUE THREAD

**Issue by Dearkungchannel** [LegendOfMCPE/EssentialsPE#381]
#### Versions

* PocketMine Version (Please copy 'git commit hash'):
* EssentialsPE Version:
* Game Version: PE / Windows 10

#### Crashdump or console errors

```
```

**Comment by Sandertv** [comment]
We can not resolve your issue if you don't provide sufficient information for us to fix your issue. Please comment once you've given enough information so we can open your issue again.
