### ISSUE TITLE
Latest Pocketmine changes breaks Essentials with Declaration errors

### ISSUE THREAD

**Issue by ZizzyZizzy** [LegendOfMCPE/EssentialsPE#385]
dktapps added some code that breaks many plugins:
https://github.com/pmmp/PocketMine-MP/commit/08e9c0572b6b63a833dbde0568ca8d93b58ccaec#commitcomment-22939072

#### Description
Error: Declaration of EssentialsPE\Commands\AFK::execute(pocketmine\command\CommandSender $sender, string $alias, array $args): bool must be compatible with pocketmine\command\Com
mand::execute(pocketmine\command\CommandSender $sender, $commandLabel, array $args)
File: EssentialsPE.phar/src/EssentialsPE/Commands/AFK
Line: 10
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EssentialsPE v2.0.0

#### Versions
* PocketMine Version: PocketMine-MP version 1.6.2dev "Unleashed" (API 3.0.0-ALPHA6)
(Built from source on 2017-07-06)
* EssentialsPE Version: 
name: EssentialsPE
version: 2.0.0
api: [3.0.0-ALPHA6, 3.0.0-ALPHA7]
author: LegendsOfMCPE Team
website: https://github.com/LegendOfMCPE/EssentialsPE
(Build from source on 2017-07-06)
* Game Version: PE

#### Crashdump or console errors
PocketMine-MP Crash Dump Thu Jul 6 12:07:49 MDT 2017

Error: Declaration of EssentialsPE\Commands\AFK::execute(pocketmine\command\CommandSender $sender, string $alias, array $args): bool must be compatible with pocketmine\command\Com
mand::execute(pocketmine\command\CommandSender $sender, $commandLabel, array $args)
File: EssentialsPE.phar/src/EssentialsPE/Commands/AFK
Line: 10
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EssentialsPE v2.0.0

Code:
[1] <?php
[2] namespace EssentialsPE\Commands;
[3]
[4] use EssentialsPE\BaseFiles\BaseAPI;
[5] use EssentialsPE\BaseFiles\BaseCommand;
[6] use pocketmine\command\CommandSender;
[7] use pocketmine\Player;
[8] use pocketmine\utils\TextFormat;
[9]
[10] class AFK extends BaseCommand{
[11]     /**
[12]      * @param BaseAPI $api
[13]      */
[14]     public function __construct(BaseAPI $api){
[15]         parent::__construct($api, "afk", "Toggle the \"Away From the Keyboard\" status", "[player]", true, ["away"]);
[16]         $this->setPermission("essentials.afk.use");
[17]     }
[18]
[19]     /**
[20]      * @param CommandSender $sender

Backtrace:

PocketMine-MP version: 1.6.2dev #0 [Protocol 113; API 3.0.0-ALPHA6]
Git commit: 0000000000000000000000000000000000000000
uname -a: Linux zornas2 2.6.32-696.3.2.el6.x86_64 #1 SMP Tue Jun 20 01:26:55 UTC 2017 x86_64
PHP Version: 7.0.19
Zend version: 3.0.0
OS : Linux, linux

Loaded plugins:
SimpleAuth 1.7.2-php7 by PocketMine Team, shoghicp for API(s) 2.0.0
SimpleAuthHelper 2.0.4vgphp7 by aliuly for API(s) 1.12.0
EssentialsPE 2.0.0 by LegendsOfMCPE Team for API(s) 3.0.0-ALPHA6, 3.0.0-ALPHA7

https://pastebin.com/Wht3hgac

**Comment by Sandertv** [comment]
This is actually on a seperate branch, which is currently supported on the master branch of EssentialsPE. I actually added support for that already. Download an EssentialsPE version 2 commits back for your current PocketMine version please.

**Comment by ZizzyZizzy** [comment]
@Sandertv Which build are you referring to? Every build I've tried either crashes when the player joins (plugin.yml shows ALPHA5) or crashes during startup (plugin.yml shows ALPHA6,ALPHA7)

I tried all of them back to build d6d17c0.  That version (and older) errors when the server starts, then disables the plugin:

06.07 14:13:37 [Server] Server thread/CRITICAL Error: "Undefined class constant 'pocketmine\block\Block::STANDING_SIGN'" (EXCEPTION) in "EssentialsPE.phar/src/EssentialsPE/Loader" at line 95
06.07 14:13:37 [Server] Server thread/INFO Disabling EssentialsPE v2.0.0
06.07 14:13:37 [Server] Server thread/CRITICAL TypeError: "Return value of EssentialsPE\Loader::getAPI() must be an instance of EssentialsPE\BaseFiles\BaseAPI, null returned" (EXCEPTION) in "EssentialsPE.phar/src/EssentialsPE/Loader" at line 402

**Comment by Sandertv** [comment]
Ugh... It's so hard to keep up with the branches mess in PocketMine. I'll make some releases for every version I can.

**Comment by ZizzyZizzy** [comment]
No doubt. If Microsoft/Mojang would quit updating every other day, maybe we would have mobs in Pocketmine already!

**Comment by Sandertv** [comment]
Please try the API3/MASTER-ALPHA-6 branch.

**Comment by ZizzyZizzy** [comment]
Almost:

06.07 18:32:19 [Server] Server thread/CRITICAL TypeError: "Argument 4 passed to EssentialsPE\BaseFiles\BaseCommand::__construct() must be of the type string, null given, called in phar:///plugins/EssentialsPE.phar/src/EssentialsPE/Commands/Back.php on line 15" (EXCEPTION) in "EssentialsPE.phar/src/EssentialsPE/BaseFiles/BaseCommand" at line 26

06.07 18:32:19 [Server] Server thread/INFO Disabling EssentialsPE v2.0.0

**Comment by Sandertv** [comment]
Oops... My bad, fixing it in a second.

**Comment by Sandertv** [comment]
Okay. Hopefully it should work just fine now. Sorry for the inconvenience.

**Comment by Matthww** [comment]
```
Error: Declaration of EssentialsPE\BaseFiles\BaseCustomEvent::getPlugin(): EssentialsPE\Loader must be compatible with pocketmine\event\plugin\PluginEvent::getPlugin(): pocketmine\plugin\Plugin
File: plugins/EssentialsPE-master/src/EssentialsPE/BaseFiles/BaseCustomEvent
Line: 0
Type: E_COMPILE_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: EssentialsPE v2.0.0

Code:
[1] <?php
[2] namespace EssentialsPE\BaseFiles;
[3] 
[4] use EssentialsPE\Loader;
[5] use pocketmine\event\plugin\PluginEvent;
[6] 
[7] abstract class BaseCustomEvent extends PluginEvent{
[8]     /** @var BaseAPI */
[9]     private $api;
[10] 
```
I'm using api3/blocks

**Comment by Sandertv** [comment]
Òops didn't notice that one! On it.

**Comment by Matthww** [comment]
@Sandertv Already had it fixed myself just wanted to let you know :)

**Comment by Sandertv** [comment]
Alright, thanks either way ;)

**Comment by ZizzyZizzy** [comment]
@Sandertv Bazinga! Thanks! Working like a charm now.

**Comment by Sandertv** [comment]
Awesome, glad it works again.
