### ISSUE TITLE
Warps get deleted after restart

### ISSUE THREAD

**Issue by XDqrkneZ** [LegendOfMCPE/EssentialsPE#386]
#### Description

Warp gets deleted after restart
#### Versions

* PocketMine Version: PocketMine-MP 1.6.2dev-154 「Unleashed」 implementing API version 3.0.0-ALPHA5 for Minecraft: PE v1.1.0.55 (protocol version 113)
* EssentialsPE Version: 2.0.0
* Game Version: PE / Windows 10 W10/mobile

#### Crashdump or console errors

``` no errors
``` no errors
<!--- Issues that do not follow this template will get closed immediatly. -->

**Comment by Sandertv** [comment]
Without knowing the git hash from the commit you downloaded this version from, I can not resolve your issue. Just click the commit you downloaded a phar file from on Poggit and you should see the git commit hash.
