### ISSUE TITLE
AFK Error

### ISSUE THREAD

**Issue by VoliPlays** [LegendOfMCPE/EssentialsPE#388]
#### Description

When I start the server on the last pocketmine, I get this error.
#### Versions

* PocketMine Version:7288515
* EssentialsPE Version:84a8829
* Game Version: PE / Windows 10
PE
#### Crashdump or console errors

Fatal error: Declaration of EssentialsPE\Commands\AFK::execute(pocketmine\command\CommandSender $sender, string $alias, array $args): bool must be compatible with pocketmine\command\Command::execute(pocketmine\command\CommandSender $sender, $commandLabel, array $args) in /home/felix/plugins/EssentialsPE-master/src/EssentialsPE/Commands/AFK.php on line 10

**Comment by Sandertv** [comment]
Please use the Master-ALPHA-6 branch.
