### ISSUE TITLE
[Feautre Request] Fly And Teleport

### ISSUE THREAD

**Issue by AffanStarPure** [LegendOfMCPE/EssentialsPE#393]
Hey i have Requested for fly can u try add when change world fly automatically off then PvP hit player automatically off too and down to ground

What about teleport TPA and tpahere i want request too  player on world survival do /tpahere still have time to be accepted then go world Prison blocked /tpyes u not allow accepted teleport that world Because my server have prison and faction i can't set no permission /tpahere is kinda annoying because people cheating by /tpahere only

**Comment by Sandertv** [comment]
This is something that should not be managed by EssentialsPE. We can not change EssentialsPE in such ways that it's no longer usable by other servers.
