### ISSUE TITLE
Issues with latest api3/block branch

### ISSUE THREAD

**Issue by optimusprime338** [LegendOfMCPE/EssentialsPE#401]
#### Versions

* PocketMine Version:
* EssentialsPE Version:
* Game Version: PE / Windows 10

#### Crashdump or console errors

```
```

using EssentialsPE: Dev build #76  with PMMP #1243 
console error:- 
INFO Fatal error: Declaration of EssentialsPE\Commands\AFK::execute(pocketmine\command\CommandSender $sender, $alias, array $args): bool must be compatible with pocketmine\command\Command::execute(pocketmine\command\CommandSender $sender, string $commandLabel, array $args) in /plugins/200-EssentialsPEAPI3_BlockBranch-7f419/src/EssentialsPE/Commands/AFK.php on line 10

**Comment by Sandertv** [comment]
https://github.com/LegendOfMCPE/EssentialsPE/tree/API3/blocks
