### ISSUE TITLE
AFK BUGGGGGG

### ISSUE THREAD

**Issue by TaiXeko** [LegendOfMCPE/EssentialsPE#403]
Fatal error: Declaration of EssentialsPE\Commands\AFK::execute(pocketmine\command\CommandSender $sender, string $alias, array $args): bool must be compatible with pocketmine\command\Command::execute(pocketmine\command\CommandSender $sender, $commandLabel, array $args) in phar://C:/Users/Administrator/Desktop/SkyBlock/plugins/EssentialsPE.phar/src/EssentialsPE/Commands/AFK.php on line 10

**Comment by Sandertv** [comment]
You're using an outdated PocketMine version.

**Comment by TaiXeko** [comment]
Give me Link Please

Vào 22-07-2017 17:59, "Sandertv" <notifications@github.com> đã viết:
