### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TaiXeko** [LegendOfMCPE/EssentialsPE#404]
] Error: "Undefined class constant 'pocketmine\block\Block::SIGN_POST'" (EXCEPTION) in "/plugins/EssentialsPE.phar/src/EssentialsPE/Loader" at line 97
12:35:07 [INFO] Disabling EssentialsPE v2.0.0
12:35:07 [CRITICAL] TypeError: "Return value of EssentialsPE\Loader::getAPI() must be an instance of EssentialsPE\BaseFiles\BaseAPI, null returned" (EXCEPTION) in "/plugins/EssentialsPE.phar/src/EssentialsPE/Loader" at line 405

**Comment by Sandertv** [comment]
Without knowing your PocketMine version, we can not resolve your issue. For the second time, the issue template is there so you can easily provide the required data.

**Comment by TaiXeko** [comment]
Im update Ver ALPHA 6

Vào 22-07-2017 18:41, "Sandertv" <notifications@github.com> đã viết:

**Comment by Sandertv** [comment]
https://github.com/LegendOfMCPE/EssentialsPE/tree/API3/blocks
