### ISSUE TITLE
AFK cmd bug

### ISSUE THREAD

**Issue by ondraczsk** [LegendOfMCPE/EssentialsPE#407]
#### Description

bug when start server
#### Versions

* PocketMine Version: genisys pro
* EssentialsPE Version: latest zip
* Game Version: PE+W10

#### Crashdump or console errors

EssentialsPE] Loading...

Fatal error: Declaration of EssentialsPE\Commands\AFK::execute(pocketmine\command\CommandSender $sender, string $alias, array $args): bool must be compatible with pocketmine\command\Command::execute(pocketmine\command\CommandSender $sender, $commandLabel, array $args) in phar:///root/serverNormal/plugins/EssentialsPE_v2.0.0.phar/src/EssentialsPE/Commands/AFK.php on line 10
[17:10:24] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[17:10:24] [Server thread/EMERGENCY]: Please upload the "/root/serverNormal/crashdumps/CrashDump_Sat_Jul_22-17.10.24-CEST_2017.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.

**Comment by Sandertv** [comment]
Please search the issue tracker for previous issue reports before submitting a new one. You're using an outdated PocketMine version. Please update your PocketMine version or download an older EssentialsPE version.

**Comment by ondraczsk** [comment]
i have latest genisys

**Comment by ondraczsk** [comment]
pro*

**Comment by Sandertv** [comment]
GenisysPro is not supported here.

**Comment by dktapps** [comment]
**claps slowly**

**Comment by eDroiid** [comment]
^
