### ISSUE TITLE
Guests cannot use /warp command

### ISSUE THREAD

**Issue by LightningCrafter** [LegendOfMCPE/EssentialsPE#409]
Ppl cannot use /warp

**Comment by Sandertv** [comment]
This is intended. You're supposed to give them the `essentials.warp` permission, then `essentials.warps.<warpname>` for an individual warp, or `essentials.warps.*` for permission to all warps.

**Comment by Yvar192** [comment]
I know this is invalid, but how do i give someone the permissions to warp?

**Comment by Sandertv** [comment]
Read my comment please.

**Comment by Yvar192** [comment]
I did read it, but i am a noob. How do i do the stuff you said?

**Comment by HimbeersaftLP** [comment]
@Yvar192 Use PurePerms (or any other permission manager of your choice if there is any)
