### ISSUE TITLE
Homes Reset On Player Leave

### ISSUE THREAD

**Issue by PotatoeTrainYT** [LegendOfMCPE/EssentialsPE#413]
**Homes Reset On Player Leaves**
Im Hosting A Factions Server And Im Almost Finished, Bit The Last Thing I Need To Do Is Working Homes! I Tried Out Your Homes Amd I Thought It Worked But When I Rejoined, My Homes Disappeared! Can You Possibly Fix This Thanks? 

Im Using Newest Version Of EssentialsPE:
-05 [14:12:32] [Server thread/INFO]: [EssentialsPE] No new version found, you're using the latest version of EssentialsPE

**Comment by Sandertv** [comment]
Duplicate of #370
