### ISSUE TITLE
Errors. Essentials not work!

### ISSUE THREAD

**Issue by S3nS3IW00** [LegendOfMCPE/EssentialsPE#432]
#### Description

Essentials is Red in plugin list(/pl)

#### Versions

* PocketMine Version: 1.12
* EssentialsPE Version: Latest on github. 
* Game Version: PE / Windows 10

#### Crashdump or console errors

```
 [Server] Server thread/CRITICAL TypeError: "Return value of EssentialsPE\Loader::checkConfig() must be an instance of EssentialsPE\void, none returned" (EXCEPTION) in "EssentialsPE_v2.0.0/src/EssentialsPE/Loader" at line 402
 [Server] Server thread/CRITICAL TypeError: "Return value of EssentialsPE\Loader::getAPI() must be an instance of EssentialsPE\BaseFiles\BaseAPI, null returned" (EXCEPTION) in "EssentialsPE_v2.0.0/src/EssentialsPE/Loader" at line 408
```

**Comment by jasonwynn10** [comment]
lmao how did you even get the first error?

**Comment by Sandertv** [comment]
Yeah... no. This plugin is not going to work on whatever modified version of PocketMine you're using.

**Comment by jasonwynn10** [comment]
I'd say outdated php with updated PocketMine

**Comment by S3nS3IW00** [comment]
Oh it is really sad :/ Which server file is better or the best?

**Comment by Sandertv** [comment]
I recommend you to update your PHP to 7.2 and use one of the latest builds of PocketMine.

**Comment by S3nS3IW00** [comment]
Thank you.
