### ISSUE TITLE
Permission

### ISSUE THREAD

**Issue by andrearizzello** [LegendOfMCPE/EssentialsPE#58]
how can i set the permission? or edit them?

**Comment by TheEpicCooldeal** [comment]
I don't think PurePerms should be recommended...

http://timings.aikar.co/?url=11738733

**Comment by 64FF00** [comment]
@TheEpicCooldeal Whatever

**Comment by 64FF00** [comment]
@TheEpicCooldeal I'm gonna try to resolve that issue after I finish my finals. #reallygotupsetbecauseofyouronestarrating

**Comment by TheEpicCooldeal** [comment]
@64FF00 No no no, You said "whatever" didn't you. Don't waste your time trying to fix it. I'll make my own plugin better than yours :P

**Comment by iksaku** [comment]
@TheEpicCooldeal I want to see that xD

**Comment by TheEpicCooldeal** [comment]
Sure, when it's done @iksaku

**Comment by TheEpicCooldeal** [comment]
See the plugin?

**Comment by LDX-MCPE** [comment]
@TheEpicCooldeal Yes. :P

**Comment by TheEpicCooldeal** [comment]
1) I don't even know you...
2) I don't like giving away plugins that are on my server that aren't even made by me. 
3) You, yourself have your own custom plugins.... Why would you even care to see mine? Or are you just saying or thinking that I'm a liar huh?

**Comment by 64FF00** [comment]
@TheEpicCooldeal Meh. Let me see if you can make a better one than mine :P
