### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by Codmadnesspro** [LegendOfMCPE/EssentialsPE#62]
20:32:49 [CRITICAL] Could not pass event pocketmine\event\player\PlayerInteractEvent to EssentialsPE v1.0.2: fopen(/home/playmcpe/test/worlds/survival/region/r.-23.-60.mcr): failed to open stream: Too many open files on EssentialsPE\EventHandler
20:32:49 [WARNING] RuntimeException: "fopen(/home/playmcpe/test/worlds/survival/region/r.-23.-60.mcr): failed to open stream: Too many open files" (E_WARNING) in "/src/pocketmine/level/format/mcregion/RegionLoader" at line 60
20:32:50 [CRITICAL] Could not pass event pocketmine\event\player\PlayerInteractEvent to EssentialsPE v1.0.2: touch(): Unable to create file /home/playmcpe/test/worlds/survival/region/r.4.61.mcr because Too many open files on EssentialsPE\EventHandler
20:32:50 [WARNING] RuntimeException: "touch(): Unable to create file /home/playmcpe/test/worlds/survival/region/r.4.61.mcr because Too many open files" (E_WARNING) in "/src/pocketmine/level/format/mcregion/RegionLoader" at line 59
20:32:50 [WARNING] RuntimeException: "file_put_contents(/home/playmcpe/test/players/the_ugly_fries.dat): failed to open stream: Too many open files" (E_WARNING) in "/src/pocketmine/Server" at line 817
20:32:50 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump

**Comment by iksaku** [comment]
This is a System error, this may appear randomly, but resides in your OS

**Comment by PEMapModder** [comment]
I want the crash dump please.

**Comment by iksaku** [comment]
There are no crash dumps, he is complaining because "EssentialsPE generates world files"... But be just walk without doing anything more and he get them, it's weird :/

**Comment by PEMapModder** [comment]
No, I mean I want a stack trace. People say this error happens during a call in PlayerInteractEvent, so I want to know which API call it is.

**Comment by iksaku** [comment]
Oh sorry xD this issue was done by other plugins, EssentialsPE doesn't have this issue :P

**Comment by PEMapModder** [comment]
Then how do you explain this issue only happens in the call stack in EssentialsPE?
