### ISSUE TITLE
Tempban, not doing their time.

### ISSUE THREAD

**Issue by Codmadnesspro** [LegendOfMCPE/EssentialsPE#63]
tempban tester 240
07:19:25 [INFO] tester[/xx.xx.xx.xx:52919] logged out due to Kicked by admin. Reason: Banned until Tuesday, January 13, 2015 at 07:1am
07:19:25 [INFO] CONSOLE: Banned player tester
07:19:31 [INFO] tester[/xx.xx.xx.xx:59818] logged in with entity id 3118 at (survival, 157.9088, 84, 177.6309)
07:19:46 [INFO] asus was killed by seryes
07:19:50 [INFO] <IRONLISTIKQQ> sky
tempban tester 10000000000
07:20:03 [INFO] tester[/xx.xx.xx.xx:59818] logged out due to Kicked by admin. Reason: Banned until Tuesday, January 13, 2015 at 07:1am
07:20:03 [INFO] CONSOLE: Banned player tester
07:20:08 [INFO] tester[/xx.xx.xx.xx:52743] logged in with entity id 3135 at (hubbeta, 161.5019, 4, 54.3897)

Tempban doesn't set their time and they can join back right after running tempban.

**Comment by iksaku** [comment]
:/ I will look at it, thanks!

**Comment by iksaku** [comment]
Have you used the 'Time' tags? ('Seconds', 'Years', etc...)

**Comment by Codmadnesspro** [comment]
No I just typed a number no actual time label

**Comment by Georggi** [comment]
@Codmadnesspro I updated wiki with time labels as it defined in command, try to use them.

**Comment by LDX-MCPE** [comment]
Use this to fix the time display. Sorry it's procedural, it's from a web app I made.
```
function addzero($i) {
  if($i < 10) {
    return "0$i";
  } else {
    return "$i";
  }
}
```

**Comment by PEMapModder** [comment]
@LDX-MCPE 

```php
function wrapText(&$text, $minLength, $prefixChar){
  $diff = $minLength - strlen($text);
  if($diff > 0) $text = str_repeat($prefixChar, $diff) . $text;
}
```

**Comment by iksaku** [comment]
Can you try again @Codmadnesspro with the latest Beta?

**Comment by iksaku** [comment]
Well, this was fixed with [Beta 4](https://github.com/LegendOfMCPE/EssentialsPE/releases/tag/1.1.0b4) :3 Closing...
