### ISSUE TITLE
[UPDATER] Issues with Github's API

### ISSUE THREAD

**Issue by iksaku** [LegendOfMCPE/EssentialsPE#65]
The main objective of this updater, it to let users to update their EssentialsPE version to the latest one, between the *Stable* and *Beta* channels; *Development* versions will not be provided yet, due to they're mainly for the team to make crazy experiments and add experimental code into the plugin, and those may put in risk production servers.

=

> For the '*Stable*' releases, it uses [PocketMine Forums' *Specific* API](http://forums.pocketmine.net/api.php?action=getResource&value=886) to get all the information about the plugin release.

> For the '*Beta*' releases, it **will** use [Github Releases' API](https://api.github.com/repos/LegendOfMCPE/EssentialsPE/releases) to get the information about **Pre-Releases _ONLY_**.

=

The updater is now semi-functional, the only problem that it has it's that the *Beta* channel is not working, there are errors while getting the information and decoding it with the ``json_decode`` function.

The main problem is always pointed at [this line](https://github.com/LegendOfMCPE/EssentialsPE/blob/master/src/EssentialsPE/Tasks/Updater/UpdateFetchTask.php#L45) of the code.

**Comment by Falkirks** [comment]
Just a question, why can't the beta channel just get the latest GitHub release?

**Comment by iksaku** [comment]
Remember that we also publish the final releases on here :P just in case that someone wants to get it from here xD

**Comment by Falkirks** [comment]
But what if someone is subscribed to beta, they can also get stable builds.

**Comment by iksaku** [comment]
Yes, I know, but for the stable releases I prefer to download them from the PocketMine-MP repository xD just for them not to complain xD =

**Comment by Falkirks** [comment]
I am not able to reproduce the errors as of yet.

**Comment by iksaku** [comment]
Modify the API xD I hide the code to switch between channels xD

**Comment by Falkirks** [comment]
I did that.

**Comment by iksaku** [comment]
Well, just revealed the code again xD try again.. I get issues :(

**Comment by PEMapModder** [comment]
@iksaku the User-Agent header is required to use the GitHub API. Could that be the problem?

**Comment by Falkirks** [comment]
@iksaku Maybe you should use `Utils::getURL()`

**Comment by iksaku** [comment]
Well, I don't know guys xD can you help me?

**Comment by LDX-MCPE** [comment]
http://stackoverflow.com/questions/2107759/php-file-get-contents-and-headers
Sounds better to me.

**Comment by iksaku** [comment]
The Beta channel is now partially working... The only thing that left to fix is the downloaded files, they're corrupted xD

**Comment by iksaku** [comment]
This issue was fixed already xD Sorry :P
