### ISSUE TITLE
Too many open files isn't a System error

### ISSUE THREAD

**Issue by llj070** [LegendOfMCPE/EssentialsPE#66]
Too many open files isn't a System error , you need to update your code .

Fixes "Too many open files"(by shoghicp ) :
This fixes issues with not closing resources given by PocketMine, causing a crash at a later stage.
Users usually blame PocketMine for this, but it's entirely a plugin's fault.
This code was found via GitHub search, please review your code for usage of:
* `Plugin->getResource()` without `fclose()` calls later
* Not needed `Plugin->getResource()` calls
* `fopen()` calls without `fclose()`
* `popen()` calls without `pclose()`

example :simpleAuth
```php
$this->database->query(stream_get_contents($resource));
fclose($resource);//------------------need this
```

example: EconomyS :
```php
$content = stream_get_contents($resource);
@fclose($content);
return $content;

@mkdir($this->getDataFolder());
if(!file_exists($this->getDataFolder())){
mkdir($this->getDataFolder());
}

$this->property->exec(stream_get_contents($resource = $this->getResource("sqlite3.sql")));
@fclose($resource);

**Comment by PEMapModder** [comment]
Thanks, but this isn't our case, because we already closed every resource opened by methods abovementioned.

**Comment by PEMapModder** [comment]
It isn't our issue. It is other plugins occupied the allowed opened files, then when we open them correctly, there are not enough places for us to.
