### ISSUE TITLE
SimpleAuth Broken after reboot

### ISSUE THREAD

**Issue by patrickt1220** [LegendOfMCPE/EssentialsPE#68]
Players are unable to login after a reboot.  My server reboots every 30 mins so after nobody can login.  I deleted the config folder and reloaded then I could login....

**Comment by iksaku** [comment]
I'm so sorry but this is not our problem, please ask the developer of SimpleAuth to fix it's errors, we can't do anything

**Comment by patrickt1220** [comment]
Lol no worrys!  This is actually only affective from the version I downloaded from pocketmine!  This version from GitHub works fine :+1:

**Comment by iksaku** [comment]
I don't know why that happens but is great to hear that! Thanks :3
