### ISSUE TITLE
Temp ban critical error

### ISSUE THREAD

**Issue by Codmadnesspro** [LegendOfMCPE/EssentialsPE#70]
20:37:24 [CRITICAL] Unhandled exception executing command 'tempban doodoodooo 1 d test' in tempban: DateInterval::__construct(): Unknown or bad format (P1S)
20:37:24 [CRITICAL] Exception: "DateInterval::__construct(): Unknown or bad format (P1S)" (EXCEPTION) in "/EssentialsPE.phar/src/EssentialsPE/Commands/TempBan" at line 43

This only happens when a player is offline, is there a way of banning someone offline too?

**Comment by Codmadnesspro** [comment]
Needed the letter next to the number.

**Comment by iksaku** [comment]
You wrote "1 d", you shouldn't add spaced between the quantity and the time measure, use "1d" instead... 
Also, TempBan doesn't handle offline players currently, I will add it later
