### ISSUE TITLE
NickNames

### ISSUE THREAD

**Issue by patrickt1220** [LegendOfMCPE/EssentialsPE#72]
In general /nick works like a charm...but players can easily make their name look like staff.... would it be possible to add a ~ Before every nickname?

**Comment by iksaku** [comment]
That isn't our part, you may need to add a chat plugin with support to our nicknames and ask the developer to add "protection" against this

**Comment by PEMapModder** [comment]
@iksaku possibly, we may do this:

/nick-addperm <pattern> <op|notop|true|false>

* registers a permission node
* every time a player sends a chat message that matches the pattern <pattern> (by RegExp or by stripos()), deny if permission is false

**Comment by jython234** [comment]
@iksaku Meh, why not do ~ like PC Essentials does? You could enable/disable in the config.

**Comment by iksaku** [comment]
Okey, I may add it :3 thanks!

**Comment by nookm** [comment]
I can't use the command "/afk" ,it shows error log, please fix the codes  (sorry for my eng

**Comment by iksaku** [comment]
Please specify what version do you use

**Comment by nookm** [comment]
You mean the minecraft pe version or pocketmine version?

**Comment by nookm** [comment]
If you meant the pocketmine version, i am using 1.4 916 (API 1.10.0)

**Comment by PEMapModder** [comment]
* which EssentialsPE version
* which PocketMine version
* what is the log

**Comment by nookm** [comment]
EssentialsPe ver v1.0.2

PocketMine ver  1.4 916 (API 1.10.0)


the log:
00:14:25 [CRITICAL] Unhandled exception executing command 'afk nookm' in afk: Argument 1 passed to EssentialsPE\Loader::isAFK() must be an instance of pocketmine\Player, instance of pocketmine\command\ConsoleCommandSender given, called in phar://E:/PocketMine-MP/plugins/EssentialsPE.phar/src/EssentialsPE/Commands/AFK.php on line 41 and defined
00:14:25 [NOTICE] InvalidArgumentException: "Argument 1 passed to EssentialsPE\Loader::isAFK() must be an instance of pocketmine\Player, instance of pocketmine\command\ConsoleCommandSender given, called in phar://E:/PocketMine-MP/plugins/EssentialsPE.phar/src/EssentialsPE/Commands/AFK.php on line 41 and defined" (E_RECOVERABLE_ERROR) in "/EssentialsPE.phar/src/EssentialsPE/Loader" at line 498

**Comment by nookm** [comment]
I don't even edit the file ......

**Comment by Georggi** [comment]
@nookm I believe it's fixed in 1.1.0 Beta, try use it after I add some messages to /afk.

**Comment by PEMapModder** [comment]
Also next time please create a new issue.

**Comment by iksaku** [comment]
@Georggi after you add some messages? What does that mean? 

BTW: Critical errors that appear on 1.0.2 will be fixed in 1.1.0

**Comment by nookm** [comment]
@Georggi   As iksaku says, what does "try use it after I add some messages to /afk." mean?

**Comment by iksaku** [comment]
He wanted to modify the new way that EssentialsPE broadcast the player AFK status, but I already talked to him xD so don't worry, I will try to accelerate the deceptive of v1.1.0 to publish it as soon as possible

**Comment by nookm** [comment]
@iksaku  So you mean the code that need to be fixed right?  so that is the plugin bug not my personal problem? (and I also sorry about my terrible eng again ....

**Comment by iksaku** [comment]
Hahaha don't worry, it was a big from the plugin itself, and it was fixed a few weeks ago, so don't worry, the upcoming version will fix it ;)

Oh! And I also have a terrible English xD so I understand how you feel xD

**Comment by iksaku** [comment]
This will be part of other plugin, so I will close this for now
