### ISSUE TITLE
I can't ban admins ......

### ISSUE THREAD

**Issue by nookm** [LegendOfMCPE/EssentialsPE#73]
I have only installed  EssentialsPE and I can't ban admins (include me
For example I banned my brother (He was an admin)
And he was kicked by the banning command but after the kick, he could stil join the server ,

Please fix this damn bug, thank you

**Comment by Georggi** [comment]
Which command are you entering? Do you have permission manager? Because by default ops have essentials.ban.exempt which prevents ban.

**Comment by nookm** [comment]
I used "/ban [playname] " this one

**Comment by iksaku** [comment]
EssentialsPE has a permission nose that prevent any kind of ban, please remove it using a Permission Manager: 
essentials.ban.exempt
