### ISSUE TITLE
The plugin are generating useless mcr files on my world folder

### ISSUE THREAD

**Issue by iVertx** [LegendOfMCPE/EssentialsPE#76]
I facing a very annoying issue using this plugin and i really need this to be fixed!
Well, EssentialsPE is generating massive .mcr dummy files on my world folder, and when i say massive is about thousand of files, now i have 22.896 mcr files in about 1 month that the server is running (and only 40- are true region files)... I tested with all my plugins, one per time and i confirmed and have sure that EssentialsPE are the problem, these files have 8kb and are composed with 3 random letters sequence, like "IGF IGF IGF IGF" (i see that opening with notepad) and it make so much difficult to manage my server files! Wonder if you have to transfer more than 40000 files (including player files) using an slow FTP? Please fix it, really

**Comment by iksaku** [comment]
As I already told you, EssentialsPE is not related to this issue, we do not convert worlds nor generate them, so please check carefully your other plugins before saying bad things of one of them...

**Comment by iksaku** [comment]
Oh and the "random" words are because the encoding of the file, that you're saying it's "MCRegion" :P

**Comment by iVertx** [comment]
@iksaku EssentialsPE is related to this issue! I think you don't understand exactly what i tried to mean, but watch this video:
https://www.dropbox.com/s/w3dezkdhkq96o4p/SCR_20150401_170447.mp4?dl=0
And after watch  tell me if it's a EssentialsPE issue or not... --" i know, this plugin doesn't generate anything, how you said.. BUT something in this plugin is wrong and have this problem... Please reopen this issue and don't ignore this problem... Sorry if i said something bad, but i really don't want to have this problem on my server... xD

**Comment by iksaku** [comment]
2 things: 
 1. I will not reopen this 
 2. It appears that you have tons of other plugins, also, I'm not sure about the "EssentialsPE" plugin you have, it appears to be edited, so I can do nothing with it... Also remember... The worlds are "ENCRYPTED" that's why you can't read it, and all the files are part of the "world"

**Comment by iVertx** [comment]
https://www.dropbox.com/s/ld2kb3idssezeon/SCR_20150401_172805.mp4?dl=0

And now...

**Comment by iksaku** [comment]
No, the "useless" files are the ones that are empty, because they contain nothing

**Comment by iVertx** [comment]
See the time that the file goes modified and see the clock of my phone, these "strange" files are recently generated, after install Essentials... Try yourself reproduce this issue, i not will post anything more here because i'm scared, but anyway these issue exists and probaly I will not be the last guy to report this...

**Comment by iksaku** [comment]
Please try with a newly generated world, also, EssentialsPE has not been tested Mobile servers, so we can't warranty anything

**Comment by PEMapModder** [comment]
It seems like this issue may be related to EssentialsPE loading more chunks.

**Comment by iksaku** [comment]
But EssentialsPE doesn't load chunks :(

**Comment by PEMapModder** [comment]
Maybe in things like jump, etc.?

I want someone to link me to one of those possibly related crash dumps, please.

**Comment by jython234** [comment]
It probably does, how many players go on the server?

On Wednesday, April 1, 2015, Jorge González <notifications@github.com>
wrote:

> But EssentialsPE doesn't load chunks :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LegendOfMCPE/EssentialsPE/issues/76#issuecomment-88672117>
> .
>


--

**Comment by Freggrayver** [comment]
Well same here

My main wörld folder have 17000 rëgion files
My server have 100 slots and run from my Ubuntu 14 64 bits desktop

It never happened beföre install essential

**Comment by PEMapModder** [comment]
Please turn on debug in pocketmine.yml and paste the stack trace here when that happens.

**Comment by Freggrayver** [comment]
How to enable ?
My setting are on level 2 but does not show nothing on cōnsole

**Comment by iksaku** [comment]
Taking the example of the video you provided, EssentialsPE doesn't do anything, you didn't execute any command that involves the world, so I can't say that EssentialsPE is causing this issue

**Comment by PEMapModder** [comment]
@iksaku It is the event handlers.
