### ISSUE TITLE
join messages

### ISSUE THREAD

**Issue by patrickt1220** [LegendOfMCPE/EssentialsPE#77]
Join messages always appear when I use this plugin... Would it be possible to disable them?  This is the only reason why this plugin isn't in my server.

**Comment by iksaku** [comment]
Not right now... But hopefully soon...

**Comment by patrickt1220** [comment]
Could I just delete the code?  I've done this before but it seems to increase the load of mY server.

**Comment by iksaku** [comment]
One message can't increase the load of your server... But yes, you can edit the code ^_^

**Comment by patrickt1220** [comment]
Alright thank you

**Comment by LDX-MCPE** [comment]
This was fixed in https://github.com/LegendOfMCPE/EssentialsPE/commit/c4dadbfa3178a2b74ee8b49eb701cec6fc7a8009.
