### ISSUE TITLE
The permissions for the commands dont work. 

### ISSUE THREAD

**Issue by sergeyvad** [LegendOfMCPE/EssentialsPE#78]
/heal (essentials.heal)
/repair (essentials.repair.armor)
/back (essentials.back)

**Comment by iksaku** [comment]
You should write them correctly for the purpose you want

**Comment by sergeyvad** [comment]
What I wrote is wrong?
I wrote what the team is responsible enough rights.
And I have added permissions for PurePerms.
For example, the command /god is configured in the same way and it works.

**Comment by iksaku** [comment]
Please be more explicit in your issue

**Comment by cloud9350** [comment]
@sergeyvad This is a PurePerms problem.
Please write down here the Permission Node.

**Comment by sergeyvad** [comment]
Configure PurePerms groups.yml
Guest:
  isDefault: true
  inheritance: []
  permissions:
  - -pocketmine.command.me
  - essentials.home
  - essentials.pvp
  - essentials.sethome
  - essentials.warp
  - essentials.warps.*
  - mspawns.spawn
  - pocketmine.command.list
  - pperms.command.ppinfo
  - simpleauth.command
  - simplewarp.warp
  - touchit.sign.use
  - universe.cmd.tp
VIP:
  inheritance:
  - Guest
  permissions:
  - essentials.back.ondeath
  - essentials.clearinventory
  - essentials.god
  - essentials.heal
  - essentials.pvp
  - essentials.repair.armor
  - essentials.suicide
  worlds: []
Commands /god, /pvp et al. works!
Commands /heal, /back, /repair not works! (in Chat: "you do not have permission")

**Comment by iksaku** [comment]
Please tell what version of EssentialsPE you're running and what version (and API if possible) of PocketMine-MP you're using

**Comment by sergeyvad** [comment]
/esspe
You're using EssentialsPE v1.0.2
    /version
 This server is running PocketMine-MP version 1.4.1-981
(Implementing API version 1.11.0 for Minecraft: PE v0.10.5 alpha protocol version 20)

**Comment by cloud9350** [comment]
@sergeyvad open pocketmine.yml and edit
debug=1 -> debug=3

And try to reproduce.

**Comment by JayFayCake** [comment]
Sphere command no work

**Comment by LDX-MCPE** [comment]
There is no sphere command...

**Comment by iksaku** [comment]
@JayFayCake Before saying anything, be complety sure that the "Feature" you're reporting is "implemented" and should work... In casde of the sphere command... there is no such command in this plugin xD

**Comment by JayFayCake** [comment]
Sorry But When I Downloaded This Plugin For My Youtube Vids When I Went
Into World It Said I Dont Have Permission But I Have The Permission Plugin.
On 6 May 2015 21:39, "Jorge González" <notifications@github.com> wrote:
>
> @JayFayCake Before saying anything, be complety sure that the "Feature"
you're reporting is "implemented" and should work... In casde of the sphere
command... there is no such command in this plugin xD

**Comment by iksaku** [comment]
Please read the [Wiki](https://github.com/LegendOfMCPE/EssentialsPE/wiki) before saying anything...

**Comment by JayFayCake** [comment]
I READ THE WIKI

**Comment by iksaku** [comment]
Then you're doing something wrong, we can't help you if you can't give more information... Like the version of the plugin you use, the version of pocketmine.. Other plugins that you use...

**Comment by JayFayCake** [comment]
Id Like To Talk To Someone Else About This Because Ur Not Helping

**Comment by iksaku** [comment]
Please go to our public chat to discuss about this:
https://gitter.im/LegendOfMCPE/EssentialsPE

**Comment by JayFayCake** [comment]
LISTEN ON MY POCKETMINE IT KEEPS SAYING NO VERSION FOUND YOU ARE USING THE
LATEST VERSION OF ESSENTIAL PE REPLY!!! IM A YOUTUBER WHO NEEDS TO MAKE VID

**Comment by iksaku** [comment]
@JayFayCake We sorry, but if you don't know how to use the plugin, it means that you haven't read the wiki... You need to execute the command ``/essentialspe`` To see the version you're currently using, as well you need to provide the version of Pocketmine

**Comment by JayFayCake** [comment]
I READ THE WIKI ALL THE CRAP IT SAID WERE COMMANDS

**Comment by JayFayCake** [comment]
HOW DO I EXECUTE THE COMMAND /ESSENTIALSPE THEN????????????

**Comment by iksaku** [comment]
You need to be OP to be able to execute all the commands, or add the corrsponding "Permission Nodes" if you use a permission manager and run them

**Comment by JayFayCake** [comment]
I Am Op But How Do U Execute???

**Comment by LDX-MCPE** [comment]
@JayFayCake Chill. Go to your server's console, then type `essentialspe` and press enter. Copy what it tells you, then paste it here.

**Comment by JayFayCake** [comment]
[EssentialsPE] No new version found, You're using the latest version of
EssentialsPE.

**Comment by PEMapModder** [comment]
@JayFayCake sphere command is not in EssentialsPE. The only plugin with sphere command I had heard of is from my WorldEditArt plugin. Please use bug reporting properly.

**Comment by PEMapModder** [comment]
If you want to report a bug, please [create a new issue](new) instead.

**Comment by iksaku** [comment]
@sergeyvad Can you confirm this bug on latest Beta 7?

**Comment by iksaku** [comment]
Could anyone confirm if this bug is still present in latest ``Beta 7``?

**Comment by sergeyvad** [comment]
I'm using the beta 6, so as soon as it works correctly. I confirm this bug, teams /heal, /repair, /back - do not have permission to use it
