### ISSUE TITLE
problem with warps

### ISSUE THREAD

**Issue by fycarman** [LegendOfMCPE/EssentialsPE#81]
Hi,I have a problem with warps. I do /setwarp <warpname> and it say it is added. Next I do /warp <warpname> but it say it doesn't exist (if i do /warp it show me the warp that I've created). Sorry for my english but I'm italian

**Comment by cloud9350** [comment]
@fycarman Check enter command
/setwarp [warp name] and /warp [warp name]

**Comment by fycarman** [comment]
Yes I do /setwarp [warp name] and /warp [warp name] but it doesn't work,it say "Warp doesn't exist"

**Comment by iksaku** [comment]
There shoud be something wrong with your server :/

**Comment by MCPEPIG** [comment]
It happened to me until I started using the beta versions that are available

**Comment by iksaku** [comment]
Can you confirm this bug on latest beta 7?
