### ISSUE TITLE
AFK spam

### ISSUE THREAD

**Issue by LDX-MCPE** [LegendOfMCPE/EssentialsPE#82]
![](http://i.imgur.com/h3VRPvh.png)

**Comment by matcracker** [comment]
Me too! D:

**Comment by LDX-MCPE** [comment]
Every 30 seconds, the AutoAFKSetter is setting everyone to AFK, regardless of when they were last active.

**Comment by LDX-MCPE** [comment]
@iksaku, I have no idea what is causing this, I've scoured the code but came up empty. My players are getting anxious to have their home and TPA commands back.

**Comment by iksaku** [comment]
Well, API allow you to hide messages, probably in next release I will implement it in config

**Comment by LDX-MCPE** [comment]
But hiding the messages won't fix it...

**Comment by iksaku** [comment]
Possibly fixed in latest commit :P Test it out :P

**Comment by LDX-MCPE** [comment]
This is an issue with the timer, though...

**Comment by cloud9350** [comment]
I have a tip on this matter already gitter.

**Comment by iksaku** [comment]
Please test with latest beta...

**Comment by matcracker** [comment]
For me is fixed! Thank you!

**Comment by iksaku** [comment]
Fixed via 5fc8f64fe42606474b3377cc52891ff9a6148f1e
