### ISSUE TITLE
[Heal] Sign; Error

### ISSUE THREAD

**Issue by TonyDroidd** [LegendOfMCPE/EssentialsPE#85]
When a player use a Sign Heal, the heal is not rellenated xD
the console logs this
http://i.imgur.com/h4sTnsZ.png

**Comment by iksaku** [comment]
Whe're aware of this xD expect an update soon :P

~ Jorge González

**Comment by TonyDroidd** [comment]
Oh, okey xD!! thanks.

**Comment by iksaku** [comment]
Fixed via 3ffdaebaae0460ee13cf2ff969cf47f2d56ded77

**Comment by TonyDroidd** [comment]
thanks :)
