### ISSUE TITLE
Permissions 

### ISSUE THREAD

**Issue by TheEpicCooldeal** [LegendOfMCPE/EssentialsPE#86]
Please Help! Everyone is hating my server due to a simple permissions glitch in your plugin!

Everyone is able to Teleport someone else to the spawn or to a warp with no permission needed!

For example: A User Can do /spawn Notch and Notch gets teleported to spawn and when they spam it, it gets really annoying (Same thing with Warps)

I hope you can fix this Please add (essentials.spawn.others) (essentials.warp.others)

**Comment by Georggi** [comment]
@TheEpicCooldeal  I don't see an error in /spawn command or /warp command, at least in the code, there are essentials.spawn.other and essentials.warp.other permissions (not "others"), maybe you can provide list of plugins? Also a version of essentialsPE

**Comment by TheEpicCooldeal** [comment]
I'm using the latest version (V.1.1.0 Beta 6) Plugins, PurePerms,Essentials,PureChat,RandomItem

**Comment by 64FF00** [comment]
@TheEpicCooldeal Could you please post your groups.yml here?

**Comment by Georggi** [comment]
Checked this on my own test server, with PM build 1125 EssentialsPE 1.1.0 Beta 7 it's not happening.

**Comment by TheEpicCooldeal** [comment]
... Hope we're both not dumb.. In the plugin.yml in spawn which is given to everyone by default it has a child which has essentials.spawn.other or others. maybe that's giving them it?

**Comment by iksaku** [comment]
I checked both codes, the ``spawn`` command is OK, but I found a glitch in the ``warp`` one :P sorry for the issue

**Comment by TheEpicCooldeal** [comment]
and Spawn? I made one of my friends Default and de-opped him and he was able to teleport me to spawn..
