### ISSUE TITLE
Kicked for idling more than 0 seconds

### ISSUE THREAD

**Issue by LDX-MCPE** [LegendOfMCPE/EssentialsPE#87]
![Kicked for idling more than 0 seconds.](http://i.imgur.com/bRj68Vz.png)

**Comment by iksaku** [comment]
Did you checked your config file? Please delete it and let a new one generate

**Comment by LDX-MCPE** [comment]
This was a clean install of EssentialsPE. It had never been run on this server before.

**Comment by cloud9350** [comment]
This server is running on Android?

**Comment by LDX-MCPE** [comment]
No, on a powerful Ubuntu VPS.

**Comment by iksaku** [comment]
Could you test with latest commits?

**Comment by LDX-MCPE** [comment]
Sure.

**Comment by iksaku** [comment]
Now this last commit?

30d45b7be99aef71b955a090d816ede13ae96439

**Comment by LDX-MCPE** [comment]
I can't. 😯 My Nexus broke.

**Comment by iksaku** [comment]
Fixed via 5fc8f64fe42606474b3377cc52891ff9a6148f1e
