### ISSUE TITLE
Join and leave messages

### ISSUE THREAD

**Issue by TheEpicCooldeal** [LegendOfMCPE/EssentialsPE#88]
I hope this isn't duplicated but whenever someone leaves or joins this message is broadcasted:

{%0} joined the game

{%0} left the game

Please help!

**Comment by LDX-MCPE** [comment]
It's a duplicate, but don't worry. We're working to fix it. ;)

**Comment by TheEpicCooldeal** [comment]
Alright :D

**Comment by iksaku** [comment]
In deed, it was already fixed xD
