### ISSUE TITLE
Can't place rails or flowers or mushroom block or minecart

### ISSUE THREAD

**Issue by Villefrog99** [LegendOfMCPE/EssentialsPE#89]
I downloaded the latest version of essentialsPE and the pocketmine.phar. whenever I select rails flowers mushroom block or a minecart it selcts it then automatically switches it back to the item it was before. Am I using the wrong version or is this issue already known about.
Thanks,
Ville

**Comment by iksaku** [comment]
Sorry but nothing to do with this plugin, it's pocketmine
