### ISSUE TITLE
Falling fly?

### ISSUE THREAD

**Issue by matcracker** [LegendOfMCPE/EssentialsPE#90]
Hi, with EssentialsPE beta 7 when a player use "/fly" , he can fly but if he re-write "/fly" while he's in air don't fall down.
I don't know if this bug is fixed in beta 8 because I can't test it and it isn't released yet.

Thanks!

-matcracker

**Comment by iksaku** [comment]
We haven't released Beta 8 because we haven't tested some changes made to "Warps", "Kits" and "Homes"... We will look into it ASAP. 

Thanks for the report!

**Comment by iksaku** [comment]
It appears that this bug is related to MCPE.. I will try to find a way to fix it anyways ;)

**Comment by matcracker** [comment]
Mhhh... Nice! Good work!
