### ISSUE TITLE
/summon command for spawning entities (Experimental)

### ISSUE THREAD

**Issue by 64FF00** [LegendOfMCPE/EssentialsPE#91]
...

**Comment by iksaku** [comment]
Yep, I have plans to add it :D But not yet xD
Also, it appears that PocketMine will implement by default... So IDK xD

**Comment by iksaku** [comment]
Let's follow minecraft's updates and use ``/summon`` instead of ``/spawnmob`` :3

**Comment by 64FF00** [comment]
@iksaku :+1:

**Comment by iksaku** [comment]
It will be hard to implement a correct way to use NBT tags... :$ I need to make much more research to get how they work for PocketMine-MP

**Comment by iksaku** [comment]
Well, with the new "NBT" system, I may be able to implement it... Unless @shoghicp win this race :P

**Comment by Lucario2** [comment]
help

**Comment by iksaku** [comment]
Well, I'm not going to implement this until PocketMine at least add all entitie classes, even without AI, just to not hack things around :P

**Comment by Sandertv** [comment]
Server softwares are implementing this.
