### ISSUE TITLE
ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE)

### ISSUE THREAD

**Issue by roroB20** [LegendOfMCPE/EssentialsPE#92]
When launching the last build of Pocketmine 1.5 and EssentialsPE v1.1.0 beta 8 I get this error:

18:45:37 [INFO] Enabling EssentialsPE v1.1.0 Beta 8
18:45:37 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 1" (E_NOTICE) in "/EssentialsPE_v1.1.0 Beta 8.phar/src/EssentialsPE/BaseFiles/BaseKit" at line 22
18:45:37 [INFO] Disabling EssentialsPE v1.1.0 Beta 8

**Comment by iksaku** [comment]
Thanks for the report! I will start debugging dev version for the Beta 8 release, it will be after MCPE 0.11 is released in Apple AppStore so I can get it in my iPhone :$

**Comment by iksaku** [comment]
Fixed via 5fc8f64fe42606474b3377cc52891ff9a6148f1e
