### ISSUE TITLE
Bug crash when using warp signs !

### ISSUE THREAD

**Issue by roroB20** [LegendOfMCPE/EssentialsPE#94]
When you set a warp to a location and create a warp sign for a fast access when you're tapping to the sign you get this error and the server is crashing !

Fatal error: Cannot use object of type EssentialsPE\BaseFiles\BaseLocation as array in phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/plugins/EssentialsPE_v1.1.0 Beta 8.phar/src/EssentialsPE/EventHandlers/SignEvents.php on line 191

Call Stack:
    0.0151     408856   1. {main}() C:\Users\roro974\Documents\Servs MCPE\BabaHouCraft- 0.11.0\PocketMine-MP.phar:0
    0.0170     403936   2. require('phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/PocketMine.php') C:\Users\roro974\Documents\Servs MCPE\BabaHouCraft- 0.11.0\PocketMine-MP.phar:1
    0.1448     543240   3. pocketmine\Server->__construct() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/PocketMine.php:464
    2.9027   14140376   4. pocketmine\Server->start() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:1772
    2.9189   14237504   5. pocketmine\Server->tickProcessor() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2166
   99.0683   45914456   6. pocketmine\Server->tick() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2288
   99.0684   45914520   7. pocketmine\network\Network->processInterfaces() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/Server__32bit.php:2471
   99.0684   45914520   8. pocketmine\network\RakLibInterface->process() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/network/Network.php:146
   99.0684   45914552   9. raklib\server\ServerHandler->handlePacket() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/network/RakLibInterface.php:79
   99.0685   45915544  10. pocketmine\network\RakLibInterface->handleEncapsulated() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/raklib/server/ServerHandler__32bit.php:90
   99.0689   45916144  11. pocketmine\Player->handleDataPacket() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/network/RakLibInterface.php:140
   99.0692   45916936  12. pocketmine\level\Level->useItemOn() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/Player__32bit.php:1902
   99.0694   45917464  13. pocketmine\plugin\PluginManager->callEvent() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/level/Level__32bit.php:1565
   99.0694   45917464  14. pocketmine\plugin\RegisteredListener->callEvent() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/plugin/PluginManager.php:673
   99.0694   45917464  15. pocketmine\plugin\MethodEventExecutor->execute() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/plugin/RegisteredListener.php:96
   99.0694   45917464  16. EssentialsPE\EventHandlers\SignEvents->onSignTap() phar://C:/Users/roro974/Documents/Servs MCPE/BabaHouCraft- 0.11.0/PocketMine-MP.phar/src/pocketmine/plugin/MethodEventExecutor.php:36

18:47:54 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
18:47:54 [EMERGENCY] Please upload the "C:\Users\roro974\Documents\Servs MCPE\BabaHouCraft- 0.11.0\CrashDump_Fri_Jun_5-18.47.54-AST_2015.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
18:47:57 [INFO] Disabling EssentialsPE v1.1.0 Beta 8

**Comment by iksaku** [comment]
Thanks for the report, expect a new Beta Release to fix this in less than an hour ;)

**Comment by iksaku** [comment]
Fixed via d2b7ca699aec8fd383eec0d5110830c1d8af644b
