### ISSUE TITLE
fly command doesn´t exist in beta 9

### ISSUE THREAD

**Issue by Creeperface01** [LegendOfMCPE/EssentialsPE#95]
/fly doesn´t exist!

**Comment by iksaku** [comment]
It exists :wink:

**Comment by Creeperface01** [comment]
![screenshot_2015-06-05-21-59-55](https://cloud.githubusercontent.com/assets/10363500/8014078/f69d678a-0bcd-11e5-873a-49b2081f1049.png)
![screenshot_2015-06-05-22-00-00](https://cloud.githubusercontent.com/assets/10363500/8014083/fdcebc5c-0bcd-11e5-875d-70ea25c91f49.png)
![screenshot_2015-06-05-22-00-36](https://cloud.githubusercontent.com/assets/10363500/8014086/051ea328-0bce-11e5-8502-a77e50f3676a.png)

**Comment by iksaku** [comment]
I have tested it ;) it exists :3 Also, try using "/help" and show me the list

**Comment by PEMapModder** [comment]
Perhaps EssentialsPE isn't even loaded?

**Comment by LDX-MCPE** [comment]
@PEMapModder His final screenshot shows that it is loaded.

**Comment by Creeperface01** [comment]
It was because i update essentials but didn't restart server only reload. But i have problem with homes.yml it can be loaded in version 1.0.2 but in latest beta not.

**Comment by iksaku** [comment]
Again... Don't mix the problems!

**Comment by Creeperface01** [comment]
OK so fly is not problem so lock this issue
