### ISSUE TITLE
crash on load

### ISSUE THREAD

**Issue by Creeperface01** [LegendOfMCPE/EssentialsPE#97]
18:58:04 [NOTICE] ArrayOutOfBoundsException: "Undefined offset: 3" (E_NOTICE) in "/EssentialsPE.phar/src/EssentialsPE/Loader" at line 437

**Comment by iksaku** [comment]
This happened because your "Homes" file is miss configured, not our fault

**Comment by Creeperface01** [comment]
what? homes file is originally generated by your plugin ;) but after i update plugin to new version send this error.

**Comment by Creeperface01** [comment]
this is why /fly doesn´t work

**Comment by Creeperface01** [comment]
so why it doesn´t work only in beta 9????

**Comment by Georggi** [comment]
@Creeperface01 did you update from Beta 8?

**Comment by PEMapModder** [comment]
Try deleting the configs.
@iksaku I told you to auto-update the configs.

**Comment by Creeperface01** [comment]
No i updated from 1.1.2 and i tried delete config but still doesn't work in beta 9

**Comment by iksaku** [comment]
The weird thing is that you updated from "1.1.2"... A version that doesn't exists yet xD also, i haven't changed the way config files work, just for the default config, but the ``Homes``, ``Kits`` and ``Warps`` ones has the same structure

**Comment by Creeperface01** [comment]
So i updated from 1.0.2 xD but homes file works only in 1.0.2 and when i update to beta it doesn't work. I have lots of homes in homes.yml do you think is it a reason?
