### ISSUE TITLE
vanish doesn´t work

### ISSUE THREAD

**Issue by Creeperface01** [LegendOfMCPE/EssentialsPE#98]
[CRITICAL] Unhandled exception executing command 'v' in vanish: include(phar:///hlserver/27750/plugins/EssentialsPE (1).phar/src/EssentialsPE/Events/PlayerVanishEvent.php): failed to open stream: phar error: Cannot open phar archive "/hlserver/27750/plugins/EssentialsPE (1).phar" for reading
19:10:09 [WARNING] RuntimeException: "include(phar:///hlserver/27750/plugins/EssentialsPE (1).phar/src/EssentialsPE/Events/PlayerVanishEvent.php): failed to open stream: phar error: Cannot open phar archive "/hlserver/27750/plugins/EssentialsPE (1).phar" for reading" (E_WARNING) in "/src/spl/BaseClassLoader" at line 128

**Comment by iksaku** [comment]
This bug happens because your server can't load EssentialsPE plugin PHAR file, please consider to try on a fresh server ;)

**Comment by PEMapModder** [comment]
Did you delete the plugin after starting the server?

And can you try deleting the ` (1)` suffix of the filename?

**Comment by Creeperface01** [comment]
Fly, vanish etc is because essentials can't load homes.yml
